In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/Users/krishnag02/Learning Phase/Jupyterfiles/Fortune_500.csv', encoding='latin-1')
df.head()

,Rank,Company Name,Number of Employees,Previous Rank,Revenues,Revenue Change,Profits,Profit Change,Assets,Market Value
0,1,Walmart,"23,00,000",1.0,"$4,85,873",0.8%,"$13,643.0",-7.2%,"$1,98,825","$2,18,619"
1,2,Berkshire Hathaway,"3,67,700",4.0,"$2,23,604",6.1%,"$24,074.0",0.0%,"$6,20,854","$4,11,035"
2,3,Apple,"1,16,000",3.0,"$2,15,639",-7.7%,"$45,687.0",-14.4%,"$3,21,686","$7,53,718"
3,4,Exxon Mobil,"72,700",2.0,"$2,05,004",-16.7%,"$7,840.0",-51.5%,"$3,30,314","$3,40,056"
4,5,McKesson,"68,000",5.0,"$1,92,487",6.2%,"$2,258.0",53.0%,"$56,563","$31,439"

In [3]:
data = df.to_numpy()

In [4]:
data

array([[1, 'Walmart', '23,00,000', ..., '-7.2%', '$1,98,825',
        '$2,18,619'],
       [2, 'Berkshire Hathaway', '3,67,700', ..., '0.0%', '$6,20,854',
        '$4,11,035'],
       [3, 'Apple', '1,16,000', ..., '-14.4%', '$3,21,686', '$7,53,718'],
       ...,
       [498, 'Yahoo', '8,500', ..., '-', '$48,083', '$44,391'],
       [499, 'Vistra Energy', '4,431', ..., '-', '$15,167', '$6,968'],
       [500, 'ABM Industries', '1,10,000', ..., '-25.0%', '$2,281',
        '$2,428']], shape=(500, 10), dtype=object)

#Level 1 — Basics

1. Load the CSV using Pandas and convert it into a NumPy array.
2. Print
  * shape
  * ndim
  * size
  * dtype
3. Print only the first 10 companies.
4. Print the last 15 companies.
5. Extract only the "Company Name" column using NumPy indexing.
6. Extract only the "Rank" column.
7. Print companies ranked from 50 to 100.
8. Print every 5th company.
9. Reverse the dataset using NumPy slicing.
10. Find the unique data types present in the NumPy array.

In [5]:
data.shape

(500, 10)

In [6]:
data.size

5000

In [7]:
data.ndim

2

In [8]:
data.dtype

dtype('O')

In [9]:
data[:10]

array([[1, 'Walmart', '23,00,000', 1.0, '$4,85,873', '0.8%', '$13,643.0',
        '-7.2%', '$1,98,825', '$2,18,619'],
       [2, 'Berkshire Hathaway', '3,67,700', 4.0, '$2,23,604', '6.1%',
        '$24,074.0', '0.0%', '$6,20,854', '$4,11,035'],
       [3, 'Apple', '1,16,000', 3.0, '$2,15,639', '-7.7%', '$45,687.0',
        '-14.4%', '$3,21,686', '$7,53,718'],
       [4, 'Exxon Mobil', '72,700', 2.0, '$2,05,004', '-16.7%',
        '$7,840.0', '-51.5%', '$3,30,314', '$3,40,056'],
       [5, 'McKesson', '68,000', 5.0, '$1,92,487', '6.2%', '$2,258.0',
        '53.0%', '$56,563', '$31,439'],
       [6, 'UnitedHealth Group', '2,30,000', 6.0, '$1,84,840', '17.7%',
        '$7,017.0', '20.7%', '$1,22,810', '$1,57,793'],
       [7, 'CVS Health', '2,04,000', 7.0, '$1,77,526', '15.8%',
        '$5,317.0', '1.5%', '$94,462', '$81,310'],
       [8, 'General Motors', '2,25,000', 8.0, '$1,66,380', '9.2%',
        '$9,427.0', '-2.7%', '$2,21,690', '$52,968'],
       [9, 'AT&T', '2,68,540', 10.0, '$1,63,786', '11.6%', '$12,976.0',
        '-2.8%', '$4,03,821', '$2,55,679'],
       [10, 'Ford Motor', '2,01,000', 9.0, '$1,51,800', '1.5%',
        '$4,596.0', '-37.7%', '$2,37,951', '$46,349']], dtype=object)

In [10]:
print(data[-15:])

[[486 'Seaboard' '11,781' 460.0 '$5,379' '-3.8%' '$312.0' '82.5%'
  '$4,755' '$4,881']
 [487 'Essendant' '6,600' 477.0 '$5,369' '0.1%' '$63.9' '-' '$2,164'
  '$568']
 [488 'Apache' '3,727' 388.0 '$5,354' '-19.5%' '-$1,405.0' '-' '$22,519'
  '$19,547']
 [489 'Airgas' '17,000' 484.0 '$5,314' '0.2%' '$337.5' '-8.3%' '$6,135'
  '-']
 [490 'Kelly Services' '7,500' 467.0 '$5,277' '-4.4%' '$120.8' '124.5%'
  '$2,028' '$836']
 [491 'Liberty Media' '3,626' 525.0 '$5,276' '10.0%' '$680.0' '962.5%'
  '$31,377' '$13,055']
 [492 'Rockwell Collins' '19,000' 490.0 '$5,259' '-0.1%' '$728.0' '6.1%'
  '$7,707' '$12,711']
 [493 'Robert Half International' '16,400' 503.0 '$5,250' '3.1%' '$343.4'
  '-4.0%' '$1,778' '$6,240']
 [494 'CH2M Hill' '20,000' 478.0 '$5,236' '-2.3%' '$15.0' '-81.3%'
  '$2,671' '-']
 [495 'Big Lots' '23,150' 495.0 '$5,200' '0.2%' '$152.8' '7.0%' '$1,608'
  '$2,180']
 [496 'Michaels Cos.' '31,000' 517.0 '$5,197' '5.8%' '$378.2' '4.2%'
  '$2,148' '$4,229']
 [497 'Toll Brothers' '4,200' 576.0 '$5,170' '23.9%' '$382.1' '5.2%'
  '$9,737' '$5,872']
 [498 'Yahoo' '8,500' 513.0 '$5,169' '4.0%' '-$214.3' '-' '$48,083'
  '$44,391']
 [499 'Vistra Energy' '4,431' nan '$5,164' '-' '-' '-' '$15,167' '$6,968']
 [500 'ABM Industries' '1,10,000' 485.0 '$5,145' '-2.8%' '$57.2' '-25.0%'
  '$2,281' '$2,428']]

In [11]:
data[:,1]

array(['Walmart', 'Berkshire Hathaway', 'Apple', 'Exxon Mobil',
       'McKesson', 'UnitedHealth Group', 'CVS Health', 'General Motors',
       'AT&T', 'Ford Motor', 'AmerisourceBergen', 'Amazon.com',
       'General Electric', 'Verizon', 'Cardinal Health', 'Costco',
       'Walgreens Boots Alliance', 'Kroger', 'Chevron', 'Fannie Mae',
       'J.P. Morgan Chase', 'Express Scripts Holding', 'Home Depot',
       'Boeing', 'Wells Fargo', 'Bank of America Corp.', 'Alphabet',
       'Microsoft', 'Anthem', 'Citigroup', 'Comcast', 'IBM',
       'State Farm Insurance Cos.', 'Phillips 66', 'Johnson & Johnson',
       'Procter & Gamble', 'Valero Energy', 'Target', 'Freddie Mac',
       'LoweÕs', 'Dell Technologies', 'MetLife', 'Aetna', 'PepsiCo',
       'Archer Daniels Midland', 'UPS', 'Intel', 'Prudential Financial',
       'Albertsons Cos.', 'United Technologies', 'Marathon Petroleum',
       'Disney', 'Humana', 'Pfizer', 'AIG', 'Lockheed Martin', 'Sysco',
       'FedEx', 'Hewlett Packard Enterprise', 'Cisco Systems', 'HP',
       'Dow Chemical', 'HCA Holdings', 'Coca-Cola',
       'New York Life Insurance', 'Centene', 'American Airlines Group',
       'Nationwide', 'Merck', 'Cigna', 'Delta Air Lines', 'Best Buy',
       'Honeywell International', 'Caterpillar',
       'Liberty Mutual Insurance Group', 'Morgan Stanley',
       'Massachusetts Mutual Life Insurance', 'Goldman Sachs Group',
       'Energy Transfer Equity', 'TIAA', 'Oracle', 'Tyson Foods',
       'United Continental Holdings', 'Allstate', 'Publix Super Markets',
       'American Express', 'TJX', 'Nike', 'Exelon', 'General Dynamics',
       'Rite Aid', 'Gilead Sciences', 'CHS', '3M', 'Time Warner',
       'Charter Communications', 'Northwestern Mutual', 'Facebook',
       'Travelers Cos.', 'Capital One Financial',
       'Twenty-First Century Fox', 'USAA', 'World Fuel Services',
       'Philip Morris International', 'Deere', 'Kraft Heinz', 'Tech Data',
       'Avnet', 'Avnet', 'MacyÕs', 'AbbVie', 'McDonaldÕs', 'DuPont',
       'Northrop Grumman', 'ConocoPhillips', 'Raytheon', 'Tesoro',
       'Arrow Electronics', 'Qualcomm', 'Progressive', 'Duke Energy',
       'Enterprise Products Partners', 'Amgen', 'US Foods Holding',
       'U.S. Bancorp', 'Aflac', 'Sears Holdings', 'Dollar General',
       'AutoNation', 'Community Health Systems', 'Starbucks', 'Eli Lilly',
       'International Paper', 'Tenet Healthcare', 'Abbott Laboratories',
       'Dollar Tree', 'Whirlpool', 'Southwest Airlines',
       'Emerson Electric', 'Staples', 'Plains GP Holdings',
       'Penske Automotive Group', 'Union Pacific', 'Danaher', 'Southern',
       'ManpowerGroup', 'Bristol-Myers Squibb', 'Altria Group', 'Fluor',
       'KohlÕs', 'Lear', 'Jabil Circuit',
       'Hartford Financial Services Group', 'Thermo Fisher Scientific',
       'Kimberly-Clark', 'Molina Healthcare', 'PG&E Corp.', 'Supervalu',
       'Cummins', 'CenturyLink', 'AECOM', 'Xerox',
       'Marriott International', 'Paccar', 'General Mills',
       'PNC Financial Services Group', 'American Electric Power',
       'Icahn Enterprises', 'Nucor', 'NextEra Energy',
       'Performance Food Group', 'PBF Energy', 'Halliburton', 'CarMax',
       'Freeport-McMoRan', 'Whole Foods Market',
       'Bank of New York Mellon Corp.', 'Gap', 'Omnicom Group',
       'Genuine Parts', 'DaVita HealthCare Partners', 'Colgate-Palmolive',
       'PPG Industries', 'Goodyear Tire & Rubber', 'Synchrony Financial',
       'DISH Network', 'Visa', 'Nordstrom', 'INTL FCStone', 'WestRock',
       'XPO Logistics', 'Aramark', 'CBS', 'AES', 'WellCare Health Plans',
       'FirstEnergy', 'ConAgra Foods', 'Synnex', 'CDW', 'Textron',
       'Waste Management', 'Illinois Tool Works', 'Office Depot',
       'Monsanto', 'Cognizant Technology Solutions', 'Texas Instruments',
       'Lincoln National', 'Newell Brands', 'Land OÕLakes',
       'Marsh & McLennan', 'Ecolab', 'C.H. Robinson Worldwide', 'Loews',
       'CBRE Group', 'Kinder Morgan', 'Kellogg', 'Western Digital',
       'Guardian Life Ins. Co. of America', 'Ross Stores', 'L Brands',
       'J.C. Penney', 'Farmers Insurance Exchange', 'Reynolds American',
       'Viacom', 'Becton Dickinson', 'Micron Technology',
       'Principal Financial', 'Alcoa', 'NRG Energy', 'VF', 'Devon Energy',
       'D.R. Horton', 'Bed Bath & Beyond', 'Consolidated Edison',
       'Edison International', 'Sherwin-Williams', 'NGL Energy Partners',
       'Dominion Resources', 'Ameriprise Financial', 'ADP',
       'Hilton Worldwide Holdings', 'First Data', 'Henry Schein',
       'Toys ÒRÓ Us', 'BB&T Corp.', 'Reinsurance Group of America',
       'Core-Mark Holding', 'Biogen', 'Las Vegas Sands',
       'Stanley Black & Decker', 'Parker-Hannifin', 'Stryker',
       'Estee Lauder', 'Celgene', 'BlackRock', 'Xcel Energy', 'CSX',
       'Unum Group', 'Jacobs Engineering Group', 'Lennar',
       'Group 1 Automotive', 'Leucadia National', 'Entergy',
       'PayPal Holdings', 'Applied Materials', 'Voya Financial',
       'MasterCard', 'Priceline Group', 'Liberty Interactive', 'AutoZone',
       'State Street Corp.', 'DTE Energy', 'L-3 Communications',
       'HollyFrontier', 'Praxair', 'Universal Health Services',
       'Discover Financial Services', 'Occidental Petroleum',
       'United States Steel', 'Sempra Energy', 'Baxter International',
       'W.W. Grainger', 'Autoliv', 'Norfolk Southern', 'Baker Hughes',
       'Ally Financial', 'Sonic Automotive', 'Owens & Minor', 'Huntsman',
       'Laboratory Corp. of America', 'Murphy USA', 'Advance Auto Parts',
       'Fidelity National Financial', 'Air Products & Chemicals',
       'Hormel Foods', 'Hertz Global Holdings',
       'MGM Resorts International', 'Corning', 'Republic Services',
       'Alcoa', 'Fidelity National Information Services', 'Pacific Life',
       'SunTrust Banks', 'LKQ', 'BorgWarner', 'Ball', 'CST Brands',
       'Public Service Enterprise Group', 'Eastman Chemical', 'eBay',
       'Mohawk Industries', 'Oneok', 'Frontier Communications', 'Netflix',
       'American Family Insurance Group',
       'Thrivent Financial for Lutherans', 'Expedia', 'Lithia Motors',
       'Avis Budget Group', 'Reliance Steel & Aluminum', 'GameStop',
       'Tenneco', 'OÕReilly Automotive', 'Peter Kiewit SonsÕ',
       'United Natural Foods', 'salesforce.com', 'Boston Scientific',
       'Newmont Mining', 'Genworth Financial',
       'Live Nation Entertainment', 'Veritiv', 'News Corp.',
       'Crown Holdings', 'Global Partners', 'PVH',
       'Level 3 Communications', 'Navistar International', 'Univar',
       'Campbell Soup', 'DickÕs Sporting Goods', 'Weyerhaeuser',
       'Mutual of Omaha Insurance', 'Chesapeake Energy',
       'Anadarko Petroleum', 'Interpublic Group', 'J.M. Smucker',
       'Steel Dynamics', 'Foot Locker', 'Western Refining', 'SpartanNash',
       'Dean Foods', 'Zimmer Biomet Holdings', 'PulteGroup',
       'W.R. Berkley', 'Quanta Services', 'EOG Resources',
       'Charles Schwab', 'Eversource Energy', 'Anixter International',
       'EMCOR Group', 'Assurant', 'CenterPoint Energy', 'Harris',
       'HD Supply Holdings', 'PPL', 'Quest Diagnostics', 'Williams',
       'WEC Energy Group', 'Hershey', 'AGCO', 'Ralph Lauren', 'Masco',
       'WESCO International', 'LifePoint Health',
       'National Oilwell Varco', 'Kindred Healthcare', 'Mosaic',
       'Alliance Data Systems', 'Computer Sciences',
       'Huntington Ingalls Industries', 'Leidos Holdings',
       'Erie Insurance Group', 'Tesla', 'Ascena Retail Group',
       'Darden Restaurants', 'Harman International Industries', 'Nvidia',
       'R.R. Donnelley & Sons', 'Fifth Third Bancorp',
       'Quintiles Transnational Holdings', 'Jones Lang LaSalle', 'Dover',
       'Spirit AeroSystems Holdings', 'Ryder System',
       'A-Mark Precious Metals', 'Tractor Supply', 'Sealed Air',
       'Auto-Owners Insurance', 'Yum China Holdings', 'Calpine',
       'Owens-Illinois', 'Targa Resources', 'JetBlue Airways',
       'Jones Financial', 'Franklin Resources', 'Activision Blizzard',
       'J.B. Hunt Transport Services', 'Constellation Brands', 'NCR',
       'Asbury Automotive Group', 'American Financial Group',
       'Discovery Communications', 'Berry Global Group', 'Sanmina',
       'CalAtlantic Group', 'Dr Pepper Snapple Group', 'DillardÕs',
       'HRG Group', 'CMS Energy', 'Graybar Electric',
       'Builders FirstSource', 'Yum Brands', 'CaseyÕs General Stores',
       'Amphenol', 'Oshkosh', 'iHeartMedia', 'TreeHouse Foods',
       'Alleghany', 'Expeditors International of Washington',
       'Avery Dennison', 'Ameren', 'Hanesbrands', 'Motorola Solutions',
       'St. Jude Medical', 'Harley-Davidson', 'Regions Financial',
       'Intercontinental Exchange', 'Alaska Air Group',
       'Old Republic International', 'Lam Research', 'AK Steel Holding',
       'Rockwell Automation', 'Adobe Systems', 'Avon Products', 'Terex',
       'NVR', 'Dana Holding', 'Realogy Holdings', 'American Tower',
       'Packaging Corp. of America', 'Citizens Financial Group',
       'United Rentals', 'Clorox', 'Genesis Healthcare', 'M&T Bank Corp.',
       'Ingredion', 'UGI', 'Owens Corning', 'S&P Global', 'Markel',
       'Wyndham Worldwide', 'Arthur J. Gallagher', 'Burlington Stores',
       'First American Financial', 'Symantec', 'Patterson', 'Olin',
       'NetApp', 'Raymond James Financial', 'TravelCenters of America',
       'Fiserv', 'Host Hotels & Resorts', 'Insight Enterprises', 'Mattel',
       'AmTrust Financial Services', 'Cincinnati Financial',
       'Simon Property Group', 'Western Union', 'KeyCorp',
       'Delek US Holdings', 'Booz Allen Hamilton Holding', 'Chemours',
       'Western & Southern Financial Group', 'Regions Financial',
       'Windstream Holdings', 'Seaboard', 'Essendant', 'Apache', 'Airgas',
       'Kelly Services', 'Liberty Media', 'Rockwell Collins',
       'Robert Half International', 'CH2M Hill', 'Big Lots',
       'Michaels Cos.', 'Toll Brothers', 'Yahoo', 'Vistra Energy',
       'ABM Industries'], dtype=object)

In [12]:
data[:,0]

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70,
       71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87,
       88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181,
       182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194,
       195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207,
       208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220,
       221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233,
       234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246,
       247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259,
       260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272,
       273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285,
       286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298,
       299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311,
       312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324,
       325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337,
       338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350,
       351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363,
       364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376,
       377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389,
       390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402,
       403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415,
       416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428,
       429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441,
       442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454,
       455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467,
       468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480,
       481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493,
       494, 495, 496, 497, 498, 499, 500], dtype=object)

In [13]:
data[50:101]

array([[51, 'Marathon Petroleum', '44,460', 42.0, '$55,858', '-13.5%',
        '$1,174.0', '-58.8%', '$44,413', '$26,679'],
       [52, 'Disney', '1,95,000', 53.0, '$55,632', '6.0%', '$9,391.0',
        '12.0%', '$92,033', '$1,79,298'],
       [53, 'Humana', '51,600', 52.0, '$54,379', '0.2%', '$614.0',
        '-51.9%', '$25,396', '$29,743'],
       [54, 'Pfizer', '96,500', 55.0, '$52,824', '8.1%', '$7,215.0',
        '3.7%', '$1,71,615', '$2,03,725'],
       [55, 'AIG', '56,400', 49.0, '$52,367', '-10.2%', '-$849.0',
        '-138.7%', '$4,98,264', '$61,154'],
       [56, 'Lockheed Martin', '97,000', 60.0, '$50,658', '9.8%',
        '$5,302.0', '47.1%', '$47,806', '$77,557'],
       [57, 'Sysco', '51,900', 57.0, '$50,367', '3.5%', '$949.6',
        '38.3%', '$16,722', '$28,048'],
       [58, 'FedEx', '3,35,767', 58.0, '$50,365', '6.1%', '$1,820.0',
        '73.3%', '$46,064', '$52,178'],
       [59, 'Hewlett Packard Enterprise', '1,95,000', nan, '$50,123',
        '-', '$3,161.0', '-', '$79,679', '$39,288'],
       [60, 'Cisco Systems', '73,700', 54.0, '$49,247', '0.2%',
        '$10,739.0', '19.6%', '$1,21,652', '$1,69,266'],
       [61, 'HP', '49,000', 20.0, '$48,238', '-53.3%', '$2,496.0',
        '-45.2%', '$29,010', '$30,231'],
       [62, 'Dow Chemical', '56,000', 56.0, '$48,158', '-1.3%',
        '$4,318.0', '-43.8%', '$79,511', '$77,460'],
       [63, 'HCA Holdings', '2,10,500', 63.0, '$44,747', '2.7%',
        '$2,890.0', '35.7%', '$33,758', '$32,966'],
       [64, 'Coca-Cola', '1,00,300', 62.0, '$41,863', '-5.5%',
        '$6,527.0', '-11.2%', '$87,270', '$1,82,153'],
       [65, 'New York Life Insurance', '11,320', 61.0, '$40,787',
        '-11.1%', '$1,088.1', '324.1%', '$2,87,196', '-'],
       [66, 'Centene', '30,500', 124.0, '$40,721', '78.6%', '$562.0',
        '58.3%', '$20,197', '$12,271'],
       [67, 'American Airlines Group', '1,22,300', 67.0, '$40,180',
        '-2.0%', '$2,676.0', '-64.8%', '$51,274', '$21,326'],
       [68, 'Nationwide', '34,320', 69.0, '$40,074', '-0.4%', '$334.3',
        '-42.4%', '$1,97,790', '-'],
       [69, 'Merck', '68,000', 72.0, '$39,807', '0.8%', '$3,920.0',
        '-11.8%', '$95,377', '$1,74,454'],
       [70, 'Cigna', '41,000', 79.0, '$39,668', '4.7%', '$1,867.0',
        '-10.8%', '$59,360', '$37,604'],
       [71, 'Delta Air Lines', '83,756', 68.0, '$39,639', '-2.6%',
        '$4,373.0', '-3.4%', '$51,261', '$33,586'],
       [72, 'Best Buy', '1,25,000', 71.0, '$39,403', '-0.9%', '$1,228.0',
        '36.9%', '$13,856', '$15,193'],
       [73, 'Honeywell International', '1,31,000', 75.0, '$39,302',
        '1.9%', '$4,809.0', '0.9%', '$54,146', '$94,991'],
       [74, 'Caterpillar', '95,400', 59.0, '$38,537', '-18.0%', '-$67.0',
        '-103.2%', '$74,704', '$54,402'],
       [75, 'Liberty Mutual Insurance Group', '50,000', 73.0, '$38,308',
        '-2.9%', '$1,006.0', '95.7%', '$1,25,592', '-'],
       [76, 'Morgan Stanley', '55,311', 78.0, '$37,949', '0.1%',
        '$5,979.0', '-2.4%', '$8,14,949', '$79,947'],
       [77, 'Massachusetts Mutual Life Insurance', '11,737', 76.0,
        '$37,788', '-1.2%', '$1,273.5', '-10.6%', '$2,71,040', '-'],
       [78, 'Goldman Sachs Group', '34,400', 74.0, '$37,712', '-3.8%',
        '$7,398.0', '21.6%', '$8,60,165', '$91,380'],
       [79, 'Energy Transfer Equity', '30,992', 65.0, '$37,504',
        '-11.0%', '$995.0', '-16.3%', '$79,011', '$21,292'],
       [80, 'TIAA', '12,997', 82.0, '$37,105', '5.5%', '$1,492.3',
        '22.9%', '$5,23,194', '-'],
       [81, 'Oracle', '1,36,000', 77.0, '$37,047', '-3.1%', '$8,901.0',
        '-10.4%', '$1,12,180', '$1,83,556'],
       [82, 'Tyson Foods', '1,14,000', 66.0, '$36,881', '-10.9%',
        '$1,768.0', '44.9%', '$22,373', '$22,028'],
       [83, 'United Continental Holdings', '88,000', 80.0, '$36,556',
        '-3.5%', '$2,263.0', '-69.2%', '$40,140', '$22,225'],
       [84, 'Allstate', '43,275', 81.0, '$36,534', '2.5%', '$1,877.0',
        '-13.5%', '$1,08,610', '$29,754'],
       [85, 'Publix Super Markets', '1,91,000', 87.0, '$34,274', '5.1%',
        '$2,025.7', '3.1%', '$17,464', '-'],
       [86, 'American Express', '56,400', 85.0, '$33,823', '-1.8%',
        '$5,408.0', '4.7%', '$1,58,893', '$71,193'],
       [87, 'TJX', '2,35,000', 89.0, '$33,184', '7.2%', '$2,298.2',
        '0.9%', '$12,884', '$51,053'],
       [88, 'Nike', '70,700', 91.0, '$32,376', '5.8%', '$3,760.0',
        '14.9%', '$21,396', '$92,204'],
       [89, 'Exelon', '34,396', 95.0, '$31,360', '6.5%', '$1,134.0',
        '-50.0%', '$1,14,904', '$33,309'],
       [90, 'General Dynamics', '98,800', 88.0, '$31,353', '-0.4%',
        '$2,955.0', '-0.3%', '$32,872', '$56,791'],
       [91, 'Rite Aid', '70,580', 107.0, '$30,737', '15.9%', '$165.5',
        '-92.2%', '$11,277', '$4,473'],
       [92, 'Gilead Sciences', '9,000', 86.0, '$30,390', '-6.9%',
        '$13,501.0', '-25.4%', '$56,977', '$88,788'],
       [93, 'CHS', '12,157', 84.0, '$30,347', '-12.2%', '$424.2',
        '-45.7%', '$17,318', '-'],
       [94, '3M', '91,584', 93.0, '$30,109', '-0.5%', '$5,050.0', '4.5%',
        '$32,906', '$1,14,338'],
       [95, 'Time Warner', '25,000', 99.0, '$29,318', '4.3%', '$3,926.0',
        '2.4%', '$65,966', '$75,660'],
       [96, 'Charter Communications', '91,500', 292.0, '$29,003',
        '197.3%', '$3,522.0', '-', '$1,49,067', '$1,00,595'],
       [97, 'Northwestern Mutual', '5,646', 100.0, '$28,799', '2.4%',
        '$818.0', '0.4%', '$2,50,441', '-'],
       [98, 'Facebook', '17,048', 157.0, '$27,638', '54.2%', '$10,217.0',
        '177.0%', '$64,961', '$4,10,522'],
       [99, 'Travelers Cos.', '30,900', 105.0, '$27,625', '3.1%',
        '$3,014.0', '-12.4%', '$1,00,245', '$33,689'],
       [100, 'Capital One Financial', '47,300', 112.0, '$27,519', '9.6%',
        '$3,751.0', '-7.4%', '$3,57,033', '$41,831'],
       [101, 'Twenty-First Century Fox', '21,500', 96.0, '$27,326',
        '-5.7%', '$2,755.0', '-66.8%', '$48,365', '$59,949']],
      dtype=object)

In [14]:
data[::5]

array([[1, 'Walmart', '23,00,000', 1.0, '$4,85,873', '0.8%', '$13,643.0',
        '-7.2%', '$1,98,825', '$2,18,619'],
       [6, 'UnitedHealth Group', '2,30,000', 6.0, '$1,84,840', '17.7%',
        '$7,017.0', '20.7%', '$1,22,810', '$1,57,793'],
       [11, 'AmerisourceBergen', '18,500', 12.0, '$1,46,850', '8.0%',
        '$1,427.9', '-', '$33,656', '$19,229'],
       [16, 'Costco', '1,72,000', 15.0, '$1,18,719', '2.2%', '$2,350.0',
        '-1.1%', '$33,163', '$73,606'],
       [21, 'J.P. Morgan Chase', '2,43,355', 23.0, '$1,05,486', '4.4%',
        '$24,733.0', '1.2%', '$24,90,972', '$3,13,761'],
       [26, 'Bank of America Corp.', '2,08,024', 26.0, '$93,662', '0.7%',
        '$17,906.0', '12.7%', '$21,87,702', '$2,36,182'],
       [31, 'Comcast', '1,59,000', 37.0, '$80,403', '7.9%', '$8,695.0',
        '6.5%', '$1,80,500', '$1,78,258'],
       [36, 'Procter & Gamble', '1,05,000', 34.0, '$71,726', '-8.9%',
        '$10,508.0', '49.3%', '$1,27,136', '$2,29,700'],
       [41, 'Dell Technologies', '1,38,000', nan, '$64,806', '18.1%',
        '-$1,672.0', '-', '$1,18,206', '-'],
       [46, 'UPS', '3,35,520', 48.0, '$60,906', '4.4%', '$3,431.0',
        '-29.2%', '$40,377', '$93,276'],
       [51, 'Marathon Petroleum', '44,460', 42.0, '$55,858', '-13.5%',
        '$1,174.0', '-58.8%', '$44,413', '$26,679'],
       [56, 'Lockheed Martin', '97,000', 60.0, '$50,658', '9.8%',
        '$5,302.0', '47.1%', '$47,806', '$77,557'],
       [61, 'HP', '49,000', 20.0, '$48,238', '-53.3%', '$2,496.0',
        '-45.2%', '$29,010', '$30,231'],
       [66, 'Centene', '30,500', 124.0, '$40,721', '78.6%', '$562.0',
        '58.3%', '$20,197', '$12,271'],
       [71, 'Delta Air Lines', '83,756', 68.0, '$39,639', '-2.6%',
        '$4,373.0', '-3.4%', '$51,261', '$33,586'],
       [76, 'Morgan Stanley', '55,311', 78.0, '$37,949', '0.1%',
        '$5,979.0', '-2.4%', '$8,14,949', '$79,947'],
       [81, 'Oracle', '1,36,000', 77.0, '$37,047', '-3.1%', '$8,901.0',
        '-10.4%', '$1,12,180', '$1,83,556'],
       [86, 'American Express', '56,400', 85.0, '$33,823', '-1.8%',
        '$5,408.0', '4.7%', '$1,58,893', '$71,193'],
       [91, 'Rite Aid', '70,580', 107.0, '$30,737', '15.9%', '$165.5',
        '-92.2%', '$11,277', '$4,473'],
       [96, 'Charter Communications', '91,500', 292.0, '$29,003',
        '197.3%', '$3,522.0', '-', '$1,49,067', '$1,00,595'],
       [101, 'Twenty-First Century Fox', '21,500', 96.0, '$27,326',
        '-5.7%', '$2,755.0', '-66.8%', '$48,365', '$59,949'],
       [106, 'Kraft Heinz', '41,000', 153.0, '$26,487', '44.4%',
        '$3,632.0', '472.9%', '$1,20,480', '$1,10,528'],
       [111, 'AbbVie', '30,000', 123.0, '$25,638', '12.2%', '$5,953.0',
        '15.7%', '$66,099', '$1,03,838'],
       [116, 'Raytheon', '63,000', 120.0, '$24,069', '3.5%', '$2,211.0',
        '6.6%', '$30,052', '$44,664'],
       [121, 'Duke Energy', '28,798', 115.0, '$23,369', '-1.0%',
        '$2,152.0', '-23.6%', '$1,32,761', '$57,397'],
       [126, 'Aflac', '10,212', 135.0, '$22,559', '8.1%', '$2,659.0',
        '5.0%', '$1,29,819', '$29,053'],
       [131, 'Starbucks', '2,54,000', 146.0, '$21,316', '11.2%',
        '$2,817.7', '2.2%', '$14,330', '$85,092'],
       [136, 'Dollar Tree', '1,16,050', 180.0, '$20,719', '33.7%',
        '$896.2', '217.4%', '$15,702', '$18,540'],
       [141, 'Plains GP Holdings', '5,100', 121.0, '$20,182', '-12.8%',
        '$94.0', '-20.3%', '$26,103', '$9,127'],
       [146, 'ManpowerGroup', '28,000', 144.0, '$19,654', '1.7%',
        '$443.7', '5.8%', '$7,574', '$6,938'],
       [151, 'Lear', '1,48,400', 154.0, '$18,558', '1.9%', '$975.1',
        '30.8%', '$9,901', '$9,726'],
       [156, 'Molina Healthcare', '21,000', 201.0, '$17,782', '25.4%',
        '$52.0', '-63.6%', '$7,449', '$2,601'],
       [161, 'AECOM', '87,000', 156.0, '$17,411', '-3.2%', '$96.1', '-',
        '$13,727', '$5,528'],
       [166, 'PNC Financial Services Group', '50,683', 171.0, '$16,423',
        '0.9%', '$3,903.0', '-4.9%', '$3,66,380', '$58,455'],
       [171, 'Performance Food Group', '13,000', 185.0, '$16,105',
        '5.5%', '$68.3', '20.9%', '$3,455', '$2,464'],
       [176, 'Whole Foods Market', '73,515', 181.0, '$15,724', '2.2%',
        '$507.0', '-5.4%', '$6,341', '$9,468'],
       [181, 'DaVita HealthCare Partners', '70,300', 200.0, '$15,197',
        '6.9%', '$879.9', '226.2%', '$18,741', '$13,227'],
       [186, 'DISH Network', '16,000', 187.0, '$15,095', '0.2%',
        '$1,449.9', '94.1%', '$28,092', '$29,547'],
       [191, 'XPO Logistics', '87,000', 353.0, '$14,619', '91.8%',
        '$69.0', '-', '$11,698', '$5,338'],
       [196, 'FirstEnergy', '15,707', 188.0, '$14,156', '-3.1%',
        '-$6,177.0', '-', '$43,148', '$14,118'],
       [201, 'Waste Management', '41,200', 221.0, '$13,609', '5.0%',
        '$1,182.0', '57.0%', '$20,859', '$32,216'],
       [206, 'Texas Instruments', '29,865', 219.0, '$13,370', '2.8%',
        '$3,595.0', '20.4%', '$16,431', '$80,531'],
       [211, 'Ecolab', '47,565', 206.0, '$13,153', '-2.9%', '$1,229.6',
        '22.7%', '$18,330', '$36,356'],
       [216, 'Kellogg', '37,369', 207.0, '$13,014', '-3.8%', '$694.0',
        '13.0%', '$15,111', '$25,417'],
       [221, 'J.C. Penney', '1,06,000', 228.0, '$12,547', '-0.6%',
        '$1.0', '-', '$9,314', '$1,901'],
       [226, 'Micron Technology', '31,400', 173.0, '$12,399', '-23.4%',
        '-$276.0', '-109.5%', '$27,540', '$31,972'],
       [231, 'Devon Energy', '3,545', 216.0, '$12,197', '-7.2%',
        '-$3,302.0', '-', '$25,913', '$21,886'],
       [236, 'Sherwin-Williams', '42,550', 253.0, '$11,856', '4.6%',
        '$1,132.7', '7.5%', '$6,753', '$28,891'],
       [241, 'Hilton Worldwide Holdings', '1,69,000', 254.0, '$11,663',
        '3.5%', '$348.0', '-75.2%', '$26,211', '$19,276'],
       [246, 'Reinsurance Group of America', '2,371', 271.0, '$11,522',
        '10.6%', '$701.4', '39.7%', '$53,098', '$8,169'],
       [251, 'Parker-Hannifin', '48,950', 224.0, '$11,361', '-10.6%',
        '$806.8', '-20.3%', '$12,057', '$21,370'],
       [256, 'Xcel Energy', '11,476', 257.0, '$11,107', '0.7%',
        '$1,123.4', '14.1%', '$41,155', '$22,546'],
       [261, 'Group 1 Automotive', '13,500', 267.0, '$10,888', '2.4%',
        '$147.1', '56.5%', '$4,462', '$1,584'],
       [266, 'Voya Financial', '6,700', 252.0, '$10,782', '-4.9%',
        '-$428.0', '-204.8%', '$2,14,235', '$7,191'],
       [271, 'State Street Corp.', '33,783', 264.0, '$10,635', '-1.2%',
        '$2,143.0', '8.2%', '$2,42,698', '$30,406'],
       [276, 'Universal Health Services', '70,863', 290.0, '$10,508',
        '7.4%', '$702.4', '3.2%', '$10,318', '$12,022'],
       [281, 'Baxter International', '48,000', 286.0, '$10,163', '2.0%',
        '$4,965.0', '412.9%', '$15,546', '$28,106'],
       [286, 'Ally Financial', '7,600', 298.0, '$9,835', '3.1%',
        '$1,067.0', '-17.2%', '$1,63,728', '$9,437'],
       [291, 'Murphy USA', '6,600', 258.0, '$9,633', '-11.5%', '$221.5',
        '25.6%', '$2,089', '$2,706'],
       [296, 'Hertz Global Holdings', '36,000', 269.0, '$9,480',
        '-10.0%', '-$491.0', '-279.9%', '$19,155', '$1,456'],
       [301, 'Fidelity National Information Services', '55,000', 392.0,
        '$9,241', '40.1%', '$568.0', '-10.1%', '$26,031', '$26,178'],
       [306, 'Ball', '18,450', 341.0, '$9,061', '13.3%', '$263.0',
        '-6.4%', '$16,173', '$13,000'],
       [311, 'Mohawk Industries', '37,800', 338.0, '$8,959', '11.0%',
        '$930.4', '51.2%', '$10,231', '$17,025'],
       [316, 'Thrivent Financial for Lutherans', '3,282', 318.0,
        '$8,777', '-0.1%', '$587.8', '-23.6%', '$88,561', '-'],
       [321, 'GameStop', '41,750', 302.0, '$8,608', '-8.1%', '$353.2',
        '-12.3%', '$4,976', '$2,282'],
       [326, 'salesforce.com', '25,000', 386.0, '$8,392', '25.9%',
        '$179.6', '-', '$17,585', '$58,362'],
       [331, 'Veritiv', '8,700', 323.0, '$8,327', '-4.5%', '$21.0',
        '-21.3%', '$2,484', '$813'],
       [336, 'Level 3 Communications', '12,600', 333.0, '$8,172',
        '-0.7%', '$677.0', '-80.3%', '$24,888', '$20,638'],
       [341, 'Weyerhaeuser', '10,400', 373.0, '$7,902', '11.6%',
        '$1,027.0', '103.0%', '$19,243', '$25,451'],
       [346, 'J.M. Smucker', '6,910', 452.0, '$7,811', '37.2%', '$688.7',
        '99.7%', '$15,984', '$15,263'],
       [351, 'Dean Foods', '17,000', 336.0, '$7,710', '-5.1%', '$119.9',
        '-', '$2,606', '$1,786'],
       [356, 'EOG Resources', '2,650', 322.0, '$7,651', '-12.6%',
        '-$1,096.7', '-', '$29,459', '$56,302'],
       [361, 'Assurant', '14,700', 275.0, '$7,532', '-27.1%', '$565.4',
        '299.4%', '$29,709', '$5,298'],
       [366, 'Quest Diagnostics', '43,000', 358.0, '$7,515', '0.3%',
        '$645.0', '-9.0%', '$10,100', '$13,501'],
       [371, 'Ralph Lauren', '20,500', 354.0, '$7,405', '-2.8%',
        '$396.0', '-43.6%', '$6,213', '$6,710'],
       [376, 'Kindred Healthcare', '76,650', 372.0, '$7,227', '1.8%',
        '-$664.2', '-', '$6,113', '$711'],
       [381, 'Leidos Holdings', '32,000', 504.0, '$7,043', '38.5%',
        '$244.0', '-3.9%', '$9,132', '$7,696'],
       [386, 'Harman International Industries', '26,000', 419.0,
        '$6,912', '12.3%', '$361.7', '5.6%', '$6,054', '-'],
       [391, 'Jones Lang LaSalle', '77,300', 436.0, '$6,804', '14.0%',
        '$318.2', '-27.5%', '$7,629', '$5,043'],
       [396, 'Tractor Supply', '19,500', 415.0, '$6,780', '8.9%',
        '$437.1', '6.5%', '$2,675', '$8,960'],
       [401, 'Owens-Illinois', '27,000', 418.0, '$6,702', '8.9%',
        '$209.0', '54.8%', '$9,135', '$3,316'],
       [406, 'Activision Blizzard', '9,500', 532.0, '$6,608', '41.7%',
        '$966.0', '8.3%', '$17,452', '$37,487'],
       [411, 'American Financial Group', '7,600', 421.0, '$6,498',
        '5.7%', '$649.0', '84.4%', '$55,072', '$8,303'],
       [416, 'Dr Pepper Snapple Group', '20,000', 413.0, '$6,440',
        '2.5%', '$847.0', '10.9%', '$9,791', '$17,997'],
       [421, 'Builders FirstSource', '14,000', 637.0, '$6,367', '78.6%',
        '$144.3', '-', '$2,910', '$1,669'],
       [426, 'iHeartMedia', '18,700', 414.0, '$6,274', '0.5%', '-$296.3',
        '-', '$12,862', '$330'],
       [431, 'Ameren', '8,629', 425.0, '$6,076', '-0.4%', '$653.0',
        '3.7%', '$24,699', '$13,245'],
       [436, 'Regions Financial', '22,166', 453.0, '$5,967', '5.2%',
        '$1,163.0', '9.5%', '$1,25,968', '$17,512'],
       [441, 'AK Steel Holding', '8,500', 383.0, '$5,883', '-12.1%',
        '-$7.8', '-', '$4,036', '$2,263'],
       [446, 'NVR', '4,900', 498.0, '$5,835', '12.9%', '$425.3', '11.1%',
        '$2,644', '$7,851'],
       [451, 'Citizens Financial Group', '17,600', 486.0, '$5,763',
        '9.2%', '$1,045.0', '24.4%', '$1,49,520', '$17,597'],
       [456, 'Ingredion', '11,000', 456.0, '$5,704', '1.5%', '$484.9',
        '20.6%', '$5,782', '$8,646'],
       [461, 'Wyndham Worldwide', '37,800', 466.0, '$5,599', '1.1%',
        '$611.0', '-0.2%', '$9,819', '$8,829'],
       [466, 'Patterson', '7,000', 559.0, '$5,555', '27.0%', '$187.2',
        '-16.2%', '$3,521', '$4,393'],
       [471, 'Fiserv', '23,000', 492.0, '$5,505', '4.8%', '$930.0',
        '30.6%', '$9,743', '$24,741'],
       [476, 'Cincinnati Financial', '4,754', 499.0, '$5,449', '6.0%',
        '$590.7', '-6.8%', '$20,386', '$11,911'],
       [481, 'Booz Allen Hamilton Holding', '22,600', 487.0, '$5,406',
        '2.5%', '$294.1', '26.5%', '$3,010', '$5,307'],
       [486, 'Seaboard', '11,781', 460.0, '$5,379', '-3.8%', '$312.0',
        '82.5%', '$4,755', '$4,881'],
       [491, 'Liberty Media', '3,626', 525.0, '$5,276', '10.0%',
        '$680.0', '962.5%', '$31,377', '$13,055'],
       [496, 'Michaels Cos.', '31,000', 517.0, '$5,197', '5.8%',
        '$378.2', '4.2%', '$2,148', '$4,229']], dtype=object)

In [15]:
data[::-1]

array([[500, 'ABM Industries', '1,10,000', ..., '-25.0%', '$2,281',
        '$2,428'],
       [499, 'Vistra Energy', '4,431', ..., '-', '$15,167', '$6,968'],
       [498, 'Yahoo', '8,500', ..., '-', '$48,083', '$44,391'],
       ...,
       [3, 'Apple', '1,16,000', ..., '-14.4%', '$3,21,686', '$7,53,718'],
       [2, 'Berkshire Hathaway', '3,67,700', ..., '0.0%', '$6,20,854',
        '$4,11,035'],
       [1, 'Walmart', '23,00,000', ..., '-7.2%', '$1,98,825',
        '$2,18,619']], shape=(500, 10), dtype=object)

In [16]:
data.flatten()

array([1, 'Walmart', '23,00,000', ..., '-25.0%', '$2,281', '$2,428'],
      shape=(5000,), dtype=object)

In [17]:
set(type(x) for x in data.flatten())

{float, int, str}

#Level 2 — Indexing & Slicing

11. Extract only these columns:
  * Rank
  * Company Name
  * Revenues
12. Extract rows 100–150.
13. Print the first 20 rows and first 5 columns.
14. Print the last 20 rows and last 4 columns.
15. Select companies whose rank is less than 20.
16. Select companies whose rank is between 100 and 150.
17. Print every alternate company.
18. Print every 10th company.
19. Extract the top 50 companies.
20. Extract the bottom 50 companies.

In [18]:
index = [0,1,4]
data[:,index]

array([[1, 'Walmart', '$4,85,873'],
       [2, 'Berkshire Hathaway', '$2,23,604'],
       [3, 'Apple', '$2,15,639'],
       ...,
       [498, 'Yahoo', '$5,169'],
       [499, 'Vistra Energy', '$5,164'],
       [500, 'ABM Industries', '$5,145']], shape=(500, 3), dtype=object)

In [19]:
data[99:150]

array([[100, 'Capital One Financial', '47,300', 112.0, '$27,519', '9.6%',
        '$3,751.0', '-7.4%', '$3,57,033', '$41,831'],
       [101, 'Twenty-First Century Fox', '21,500', 96.0, '$27,326',
        '-5.7%', '$2,755.0', '-66.8%', '$48,365', '$59,949'],
       [102, 'USAA', '29,943', 114.0, '$27,131', '11.4%', '$1,779.1',
        '-21.7%', '$1,47,290', '-'],
       [103, 'World Fuel Services', '5,000', 92.0, '$27,016', '-11.1%',
        '$126.5', '-27.5%', '$5,413', '$2,535'],
       [104, 'Philip Morris International', '79,500', 106.0, '$26,685',
        '-0.4%', '$6,967.0', '1.4%', '$36,851', '$1,75,349'],
       [105, 'Deere', '56,767', 97.0, '$26,644', '-7.7%', '$1,523.9',
        '-21.4%', '$57,981', '$34,648'],
       [106, 'Kraft Heinz', '41,000', 153.0, '$26,487', '44.4%',
        '$3,632.0', '472.9%', '$1,20,480', '$1,10,528'],
       [107, 'Tech Data', '9,500', 108.0, '$26,235', '-0.5%', '$195.1',
        '-26.6%', '$7,932', '$3,569'],
       [108, 'Avnet', '17,700', 102.0, '$26,219', '-6.1%', '$506.5',
        '-11.4%', '$11,240', '$5,898'],
       [109, 'Avnet', '90,000', 102.0, '$25,923', '-12.5%', '$1,659.0',
        '-77.2%', '$61,538', '$65,676'],
       [110, 'MacyÕs', '1,48,300', 103.0, '$25,778', '-4.8%', '$619.0',
        '-42.3%', '$19,851', '$9,046'],
       [111, 'AbbVie', '30,000', 123.0, '$25,638', '12.2%', '$5,953.0',
        '15.7%', '$66,099', '$1,03,838'],
       [112, 'McDonaldÕs', '3,75,000', 109.0, '$24,622', '-3.1%',
        '$4,686.5', '3.5%', '$31,024', '$1,06,150'],
       [113, 'DuPont', '46,000', 101.0, '$24,594', '-12.0%', '$2,513.0',
        '28.7%', '$39,964', '$69,451'],
       [114, 'Northrop Grumman', '67,000', 118.0, '$24,508', '4.2%',
        '$2,200.0', '10.6%', '$25,614', '$41,577'],
       [115, 'ConocoPhillips', '13,300', 90.0, '$24,360', '-21.3%',
        '-$3,615.0', '-', '$89,772', '$61,692'],
       [116, 'Raytheon', '63,000', 120.0, '$24,069', '3.5%', '$2,211.0',
        '6.6%', '$30,052', '$44,664'],
       [117, 'Tesoro', '6,308', 98.0, '$24,005', '-14.7%', '$734.0',
        '-52.3%', '$20,398', '$9,515'],
       [118, 'Arrow Electronics', '18,700', 119.0, '$23,825', '2.3%',
        '$522.8', '5.0%', '$14,206', '$6,546'],
       [119, 'Qualcomm', '30,500', 110.0, '$23,554', '-6.8%', '$5,705.0',
        '8.2%', '$52,359', '$84,694'],
       [120, 'Progressive', '31,721', 137.0, '$23,441', '12.4%',
        '$1,031.0', '-18.7%', '$33,428', '$22,760'],
       [121, 'Duke Energy', '28,798', 115.0, '$23,369', '-1.0%',
        '$2,152.0', '-23.6%', '$1,32,761', '$57,397'],
       [122, 'Enterprise Products Partners', '6,800', 104.0, '$23,022',
        '-14.8%', '$2,513.1', '-0.3%', '$52,194', '$58,522'],
       [123, 'Amgen', '19,200', 130.0, '$22,991', '6.1%', '$7,722.0',
        '11.3%', '$77,626', '$1,20,830'],
       [124, 'US Foods Holding', '25,000', 122.0, '$22,919', '-0.9%',
        '$209.8', '25.2%', '$8,945', '$6,207'],
       [125, 'U.S. Bancorp', '71,191', 131.0, '$22,744', '5.8%',
        '$5,888.0', '0.2%', '$4,45,964', '$87,201'],
       [126, 'Aflac', '10,212', 135.0, '$22,559', '8.1%', '$2,659.0',
        '5.0%', '$1,29,819', '$29,053'],
       [127, 'Sears Holdings', '1,40,000', 111.0, '$22,138', '-12.0%',
        '-$2,221.0', '-', '$9,362', '$1,231'],
       [128, 'Dollar General', '1,21,000', 139.0, '$21,987', '7.9%',
        '$1,251.1', '7.4%', '$11,672', '$19,182'],
       [129, 'AutoNation', '26,000', 136.0, '$21,609', '3.6%', '$430.5',
        '-2.7%', '$10,060', '$4,268'],
       [130, 'Community Health Systems', '1,08,000', 125.0, '$21,374',
        '-5.8%', '-$1,721.0', '-', '$21,944', '$1,010'],
       [131, 'Starbucks', '2,54,000', 146.0, '$21,316', '11.2%',
        '$2,817.7', '2.2%', '$14,330', '$85,092'],
       [132, 'Eli Lilly', '41,975', 141.0, '$21,222', '6.3%', '$2,737.6',
        '13.7%', '$38,806', '$92,803'],
       [133, 'International Paper', '55,000', 127.0, '$21,079', '-5.8%',
        '$904.0', '-3.6%', '$33,345', '$20,884'],
       [134, 'Tenet Healthcare', '1,16,475', 140.0, '$21,070', '4.8%',
        '-$192.0', '-', '$24,701', '$1,777'],
       [135, 'Abbott Laboratories', '75,000', 138.0, '$20,853', '0.9%',
        '$1,400.0', '-68.3%', '$52,666', '$76,740'],
       [136, 'Dollar Tree', '1,16,050', 180.0, '$20,719', '33.7%',
        '$896.2', '217.4%', '$15,702', '$18,540'],
       [137, 'Whirlpool', '93,000', 134.0, '$20,718', '-0.8%', '$888.0',
        '13.4%', '$19,153', '$12,762'],
       [138, 'Southwest Airlines', '53,536', 142.0, '$20,425', '3.1%',
        '$2,244.0', '2.9%', '$23,286', '$33,076'],
       [139, 'Emerson Electric', '1,03,500', 128.0, '$20,268', '-9.1%',
        '$1,635.0', '-39.7%', '$21,743', '$38,614'],
       [140, 'Staples', '61,503', 132.0, '$20,217', '-4.0%', '-$1,497.0',
        '-494.8%', '$8,271', '$5,723'],
       [141, 'Plains GP Holdings', '5,100', 121.0, '$20,182', '-12.8%',
        '$94.0', '-20.3%', '$26,103', '$9,127'],
       [142, 'Penske Automotive Group', '24,000', 143.0, '$20,143',
        '4.0%', '$342.9', '5.2%', '$8,861', '$4,001'],
       [143, 'Union Pacific', '42,919', 129.0, '$19,941', '-8.6%',
        '$4,233.0', '-11.3%', '$55,718', '$85,911'],
       [144, 'Danaher', '62,000', 133.0, '$19,912', '-4.8%', '$2,553.7',
        '-23.9%', '$45,295', '$59,359'],
       [145, 'Southern', '32,015', 162.0, '$19,896', '13.8%', '$2,448.0',
        '3.4%', '$1,09,697', '$49,335'],
       [146, 'ManpowerGroup', '28,000', 144.0, '$19,654', '1.7%',
        '$443.7', '5.8%', '$7,574', '$6,938'],
       [147, 'Bristol-Myers Squibb', '25,000', 168.0, '$19,427', '17.3%',
        '$4,457.0', '184.8%', '$33,707', '$89,591'],
       [148, 'Altria Group', '8,300', 149.0, '$19,337', '2.6%',
        '$14,239.0', '171.7%', '$45,932', '$1,38,513'],
       [149, 'Fluor', '61,551', 155.0, '$19,037', '5.1%', '$281.4',
        '-31.8%', '$9,216', '$7,353'],
       [150, 'KohlÕs', '85,000', 145.0, '$18,686', '-2.7%', '$556.0',
        '-17.4%', '$13,574', '$6,862']], dtype=object)

In [20]:
data[:20,:5]

array([[1, 'Walmart', '23,00,000', 1.0, '$4,85,873'],
       [2, 'Berkshire Hathaway', '3,67,700', 4.0, '$2,23,604'],
       [3, 'Apple', '1,16,000', 3.0, '$2,15,639'],
       [4, 'Exxon Mobil', '72,700', 2.0, '$2,05,004'],
       [5, 'McKesson', '68,000', 5.0, '$1,92,487'],
       [6, 'UnitedHealth Group', '2,30,000', 6.0, '$1,84,840'],
       [7, 'CVS Health', '2,04,000', 7.0, '$1,77,526'],
       [8, 'General Motors', '2,25,000', 8.0, '$1,66,380'],
       [9, 'AT&T', '2,68,540', 10.0, '$1,63,786'],
       [10, 'Ford Motor', '2,01,000', 9.0, '$1,51,800'],
       [11, 'AmerisourceBergen', '18,500', 12.0, '$1,46,850'],
       [12, 'Amazon.com', '3,41,400', 18.0, '$1,35,987'],
       [13, 'General Electric', '2,95,000', 11.0, '$1,26,661'],
       [14, 'Verizon', '1,60,900', 13.0, '$1,25,980'],
       [15, 'Cardinal Health', '37,300', 21.0, '$1,21,546'],
       [16, 'Costco', '1,72,000', 15.0, '$1,18,719'],
       [17, 'Walgreens Boots Alliance', '3,00,000', 19.0, '$1,17,351'],
       [18, 'Kroger', '4,43,000', 17.0, '$1,15,337'],
       [19, 'Chevron', '55,200', 14.0, '$1,07,567'],
       [20, 'Fannie Mae', '7,000', 16.0, '$1,07,162']], dtype=object)

In [21]:
data[-20:,-4:]

array([['$294.1', '26.5%', '$3,010', '$5,307'],
       ['$7.0', '-', '$6,060', '$7,080'],
       ['$241.2', '-47.2%', '$43,831', '-'],
       ['$900.0', '196.1%', '$8,357', '$12,643'],
       ['-$383.5', '-', '$11,770', '$1,038'],
       ['$312.0', '82.5%', '$4,755', '$4,881'],
       ['$63.9', '-', '$2,164', '$568'],
       ['-$1,405.0', '-', '$22,519', '$19,547'],
       ['$337.5', '-8.3%', '$6,135', '-'],
       ['$120.8', '124.5%', '$2,028', '$836'],
       ['$680.0', '962.5%', '$31,377', '$13,055'],
       ['$728.0', '6.1%', '$7,707', '$12,711'],
       ['$343.4', '-4.0%', '$1,778', '$6,240'],
       ['$15.0', '-81.3%', '$2,671', '-'],
       ['$152.8', '7.0%', '$1,608', '$2,180'],
       ['$378.2', '4.2%', '$2,148', '$4,229'],
       ['$382.1', '5.2%', '$9,737', '$5,872'],
       ['-$214.3', '-', '$48,083', '$44,391'],
       ['-', '-', '$15,167', '$6,968'],
       ['$57.2', '-25.0%', '$2,281', '$2,428']], dtype=object)

In [22]:
result = data[:,0] < 20
data[result]

array([[1, 'Walmart', '23,00,000', 1.0, '$4,85,873', '0.8%', '$13,643.0',
        '-7.2%', '$1,98,825', '$2,18,619'],
       [2, 'Berkshire Hathaway', '3,67,700', 4.0, '$2,23,604', '6.1%',
        '$24,074.0', '0.0%', '$6,20,854', '$4,11,035'],
       [3, 'Apple', '1,16,000', 3.0, '$2,15,639', '-7.7%', '$45,687.0',
        '-14.4%', '$3,21,686', '$7,53,718'],
       [4, 'Exxon Mobil', '72,700', 2.0, '$2,05,004', '-16.7%',
        '$7,840.0', '-51.5%', '$3,30,314', '$3,40,056'],
       [5, 'McKesson', '68,000', 5.0, '$1,92,487', '6.2%', '$2,258.0',
        '53.0%', '$56,563', '$31,439'],
       [6, 'UnitedHealth Group', '2,30,000', 6.0, '$1,84,840', '17.7%',
        '$7,017.0', '20.7%', '$1,22,810', '$1,57,793'],
       [7, 'CVS Health', '2,04,000', 7.0, '$1,77,526', '15.8%',
        '$5,317.0', '1.5%', '$94,462', '$81,310'],
       [8, 'General Motors', '2,25,000', 8.0, '$1,66,380', '9.2%',
        '$9,427.0', '-2.7%', '$2,21,690', '$52,968'],
       [9, 'AT&T', '2,68,540', 10.0, '$1,63,786', '11.6%', '$12,976.0',
        '-2.8%', '$4,03,821', '$2,55,679'],
       [10, 'Ford Motor', '2,01,000', 9.0, '$1,51,800', '1.5%',
        '$4,596.0', '-37.7%', '$2,37,951', '$46,349'],
       [11, 'AmerisourceBergen', '18,500', 12.0, '$1,46,850', '8.0%',
        '$1,427.9', '-', '$33,656', '$19,229'],
       [12, 'Amazon.com', '3,41,400', 18.0, '$1,35,987', '27.1%',
        '$2,371.0', '297.8%', '$83,402', '$4,23,031'],
       [13, 'General Electric', '2,95,000', 11.0, '$1,26,661', '-9.8%',
        '$8,831.0', '-', '$3,65,183', '$2,59,520'],
       [14, 'Verizon', '1,60,900', 13.0, '$1,25,980', '-4.3%',
        '$13,127.0', '-26.6%', '$2,44,180', '$1,98,900'],
       [15, 'Cardinal Health', '37,300', 21.0, '$1,21,546', '18.5%',
        '$1,427.0', '17.4%', '$34,122', '$25,725'],
       [16, 'Costco', '1,72,000', 15.0, '$1,18,719', '2.2%', '$2,350.0',
        '-1.1%', '$33,163', '$73,606'],
       [17, 'Walgreens Boots Alliance', '3,00,000', 19.0, '$1,17,351',
        '13.4%', '$4,173.0', '-1.1%', '$72,688', '$89,645'],
       [18, 'Kroger', '4,43,000', 17.0, '$1,15,337', '5.0%', '$1,975.0',
        '-3.1%', '$36,505', '$26,961'],
       [19, 'Chevron', '55,200', 14.0, '$1,07,567', '-18.0%', '-$497.0',
        '-110.8%', '$2,60,078', '$2,03,263']], dtype=object)

In [23]:
result = (data[:,0]>= 100) & (data[:,0] <=150)
data[result]

array([[100, 'Capital One Financial', '47,300', 112.0, '$27,519', '9.6%',
        '$3,751.0', '-7.4%', '$3,57,033', '$41,831'],
       [101, 'Twenty-First Century Fox', '21,500', 96.0, '$27,326',
        '-5.7%', '$2,755.0', '-66.8%', '$48,365', '$59,949'],
       [102, 'USAA', '29,943', 114.0, '$27,131', '11.4%', '$1,779.1',
        '-21.7%', '$1,47,290', '-'],
       [103, 'World Fuel Services', '5,000', 92.0, '$27,016', '-11.1%',
        '$126.5', '-27.5%', '$5,413', '$2,535'],
       [104, 'Philip Morris International', '79,500', 106.0, '$26,685',
        '-0.4%', '$6,967.0', '1.4%', '$36,851', '$1,75,349'],
       [105, 'Deere', '56,767', 97.0, '$26,644', '-7.7%', '$1,523.9',
        '-21.4%', '$57,981', '$34,648'],
       [106, 'Kraft Heinz', '41,000', 153.0, '$26,487', '44.4%',
        '$3,632.0', '472.9%', '$1,20,480', '$1,10,528'],
       [107, 'Tech Data', '9,500', 108.0, '$26,235', '-0.5%', '$195.1',
        '-26.6%', '$7,932', '$3,569'],
       [108, 'Avnet', '17,700', 102.0, '$26,219', '-6.1%', '$506.5',
        '-11.4%', '$11,240', '$5,898'],
       [109, 'Avnet', '90,000', 102.0, '$25,923', '-12.5%', '$1,659.0',
        '-77.2%', '$61,538', '$65,676'],
       [110, 'MacyÕs', '1,48,300', 103.0, '$25,778', '-4.8%', '$619.0',
        '-42.3%', '$19,851', '$9,046'],
       [111, 'AbbVie', '30,000', 123.0, '$25,638', '12.2%', '$5,953.0',
        '15.7%', '$66,099', '$1,03,838'],
       [112, 'McDonaldÕs', '3,75,000', 109.0, '$24,622', '-3.1%',
        '$4,686.5', '3.5%', '$31,024', '$1,06,150'],
       [113, 'DuPont', '46,000', 101.0, '$24,594', '-12.0%', '$2,513.0',
        '28.7%', '$39,964', '$69,451'],
       [114, 'Northrop Grumman', '67,000', 118.0, '$24,508', '4.2%',
        '$2,200.0', '10.6%', '$25,614', '$41,577'],
       [115, 'ConocoPhillips', '13,300', 90.0, '$24,360', '-21.3%',
        '-$3,615.0', '-', '$89,772', '$61,692'],
       [116, 'Raytheon', '63,000', 120.0, '$24,069', '3.5%', '$2,211.0',
        '6.6%', '$30,052', '$44,664'],
       [117, 'Tesoro', '6,308', 98.0, '$24,005', '-14.7%', '$734.0',
        '-52.3%', '$20,398', '$9,515'],
       [118, 'Arrow Electronics', '18,700', 119.0, '$23,825', '2.3%',
        '$522.8', '5.0%', '$14,206', '$6,546'],
       [119, 'Qualcomm', '30,500', 110.0, '$23,554', '-6.8%', '$5,705.0',
        '8.2%', '$52,359', '$84,694'],
       [120, 'Progressive', '31,721', 137.0, '$23,441', '12.4%',
        '$1,031.0', '-18.7%', '$33,428', '$22,760'],
       [121, 'Duke Energy', '28,798', 115.0, '$23,369', '-1.0%',
        '$2,152.0', '-23.6%', '$1,32,761', '$57,397'],
       [122, 'Enterprise Products Partners', '6,800', 104.0, '$23,022',
        '-14.8%', '$2,513.1', '-0.3%', '$52,194', '$58,522'],
       [123, 'Amgen', '19,200', 130.0, '$22,991', '6.1%', '$7,722.0',
        '11.3%', '$77,626', '$1,20,830'],
       [124, 'US Foods Holding', '25,000', 122.0, '$22,919', '-0.9%',
        '$209.8', '25.2%', '$8,945', '$6,207'],
       [125, 'U.S. Bancorp', '71,191', 131.0, '$22,744', '5.8%',
        '$5,888.0', '0.2%', '$4,45,964', '$87,201'],
       [126, 'Aflac', '10,212', 135.0, '$22,559', '8.1%', '$2,659.0',
        '5.0%', '$1,29,819', '$29,053'],
       [127, 'Sears Holdings', '1,40,000', 111.0, '$22,138', '-12.0%',
        '-$2,221.0', '-', '$9,362', '$1,231'],
       [128, 'Dollar General', '1,21,000', 139.0, '$21,987', '7.9%',
        '$1,251.1', '7.4%', '$11,672', '$19,182'],
       [129, 'AutoNation', '26,000', 136.0, '$21,609', '3.6%', '$430.5',
        '-2.7%', '$10,060', '$4,268'],
       [130, 'Community Health Systems', '1,08,000', 125.0, '$21,374',
        '-5.8%', '-$1,721.0', '-', '$21,944', '$1,010'],
       [131, 'Starbucks', '2,54,000', 146.0, '$21,316', '11.2%',
        '$2,817.7', '2.2%', '$14,330', '$85,092'],
       [132, 'Eli Lilly', '41,975', 141.0, '$21,222', '6.3%', '$2,737.6',
        '13.7%', '$38,806', '$92,803'],
       [133, 'International Paper', '55,000', 127.0, '$21,079', '-5.8%',
        '$904.0', '-3.6%', '$33,345', '$20,884'],
       [134, 'Tenet Healthcare', '1,16,475', 140.0, '$21,070', '4.8%',
        '-$192.0', '-', '$24,701', '$1,777'],
       [135, 'Abbott Laboratories', '75,000', 138.0, '$20,853', '0.9%',
        '$1,400.0', '-68.3%', '$52,666', '$76,740'],
       [136, 'Dollar Tree', '1,16,050', 180.0, '$20,719', '33.7%',
        '$896.2', '217.4%', '$15,702', '$18,540'],
       [137, 'Whirlpool', '93,000', 134.0, '$20,718', '-0.8%', '$888.0',
        '13.4%', '$19,153', '$12,762'],
       [138, 'Southwest Airlines', '53,536', 142.0, '$20,425', '3.1%',
        '$2,244.0', '2.9%', '$23,286', '$33,076'],
       [139, 'Emerson Electric', '1,03,500', 128.0, '$20,268', '-9.1%',
        '$1,635.0', '-39.7%', '$21,743', '$38,614'],
       [140, 'Staples', '61,503', 132.0, '$20,217', '-4.0%', '-$1,497.0',
        '-494.8%', '$8,271', '$5,723'],
       [141, 'Plains GP Holdings', '5,100', 121.0, '$20,182', '-12.8%',
        '$94.0', '-20.3%', '$26,103', '$9,127'],
       [142, 'Penske Automotive Group', '24,000', 143.0, '$20,143',
        '4.0%', '$342.9', '5.2%', '$8,861', '$4,001'],
       [143, 'Union Pacific', '42,919', 129.0, '$19,941', '-8.6%',
        '$4,233.0', '-11.3%', '$55,718', '$85,911'],
       [144, 'Danaher', '62,000', 133.0, '$19,912', '-4.8%', '$2,553.7',
        '-23.9%', '$45,295', '$59,359'],
       [145, 'Southern', '32,015', 162.0, '$19,896', '13.8%', '$2,448.0',
        '3.4%', '$1,09,697', '$49,335'],
       [146, 'ManpowerGroup', '28,000', 144.0, '$19,654', '1.7%',
        '$443.7', '5.8%', '$7,574', '$6,938'],
       [147, 'Bristol-Myers Squibb', '25,000', 168.0, '$19,427', '17.3%',
        '$4,457.0', '184.8%', '$33,707', '$89,591'],
       [148, 'Altria Group', '8,300', 149.0, '$19,337', '2.6%',
        '$14,239.0', '171.7%', '$45,932', '$1,38,513'],
       [149, 'Fluor', '61,551', 155.0, '$19,037', '5.1%', '$281.4',
        '-31.8%', '$9,216', '$7,353'],
       [150, 'KohlÕs', '85,000', 145.0, '$18,686', '-2.7%', '$556.0',
        '-17.4%', '$13,574', '$6,862']], dtype=object)

In [24]:
data[::2]

array([[1, 'Walmart', '23,00,000', ..., '-7.2%', '$1,98,825',
        '$2,18,619'],
       [3, 'Apple', '1,16,000', ..., '-14.4%', '$3,21,686', '$7,53,718'],
       [5, 'McKesson', '68,000', ..., '53.0%', '$56,563', '$31,439'],
       ...,
       [495, 'Big Lots', '23,150', ..., '7.0%', '$1,608', '$2,180'],
       [497, 'Toll Brothers', '4,200', ..., '5.2%', '$9,737', '$5,872'],
       [499, 'Vistra Energy', '4,431', ..., '-', '$15,167', '$6,968']],
      shape=(250, 10), dtype=object)

In [25]:
data[::10]

array([[1, 'Walmart', '23,00,000', 1.0, '$4,85,873', '0.8%', '$13,643.0',
        '-7.2%', '$1,98,825', '$2,18,619'],
       [11, 'AmerisourceBergen', '18,500', 12.0, '$1,46,850', '8.0%',
        '$1,427.9', '-', '$33,656', '$19,229'],
       [21, 'J.P. Morgan Chase', '2,43,355', 23.0, '$1,05,486', '4.4%',
        '$24,733.0', '1.2%', '$24,90,972', '$3,13,761'],
       [31, 'Comcast', '1,59,000', 37.0, '$80,403', '7.9%', '$8,695.0',
        '6.5%', '$1,80,500', '$1,78,258'],
       [41, 'Dell Technologies', '1,38,000', nan, '$64,806', '18.1%',
        '-$1,672.0', '-', '$1,18,206', '-'],
       [51, 'Marathon Petroleum', '44,460', 42.0, '$55,858', '-13.5%',
        '$1,174.0', '-58.8%', '$44,413', '$26,679'],
       [61, 'HP', '49,000', 20.0, '$48,238', '-53.3%', '$2,496.0',
        '-45.2%', '$29,010', '$30,231'],
       [71, 'Delta Air Lines', '83,756', 68.0, '$39,639', '-2.6%',
        '$4,373.0', '-3.4%', '$51,261', '$33,586'],
       [81, 'Oracle', '1,36,000', 77.0, '$37,047', '-3.1%', '$8,901.0',
        '-10.4%', '$1,12,180', '$1,83,556'],
       [91, 'Rite Aid', '70,580', 107.0, '$30,737', '15.9%', '$165.5',
        '-92.2%', '$11,277', '$4,473'],
       [101, 'Twenty-First Century Fox', '21,500', 96.0, '$27,326',
        '-5.7%', '$2,755.0', '-66.8%', '$48,365', '$59,949'],
       [111, 'AbbVie', '30,000', 123.0, '$25,638', '12.2%', '$5,953.0',
        '15.7%', '$66,099', '$1,03,838'],
       [121, 'Duke Energy', '28,798', 115.0, '$23,369', '-1.0%',
        '$2,152.0', '-23.6%', '$1,32,761', '$57,397'],
       [131, 'Starbucks', '2,54,000', 146.0, '$21,316', '11.2%',
        '$2,817.7', '2.2%', '$14,330', '$85,092'],
       [141, 'Plains GP Holdings', '5,100', 121.0, '$20,182', '-12.8%',
        '$94.0', '-20.3%', '$26,103', '$9,127'],
       [151, 'Lear', '1,48,400', 154.0, '$18,558', '1.9%', '$975.1',
        '30.8%', '$9,901', '$9,726'],
       [161, 'AECOM', '87,000', 156.0, '$17,411', '-3.2%', '$96.1', '-',
        '$13,727', '$5,528'],
       [171, 'Performance Food Group', '13,000', 185.0, '$16,105',
        '5.5%', '$68.3', '20.9%', '$3,455', '$2,464'],
       [181, 'DaVita HealthCare Partners', '70,300', 200.0, '$15,197',
        '6.9%', '$879.9', '226.2%', '$18,741', '$13,227'],
       [191, 'XPO Logistics', '87,000', 353.0, '$14,619', '91.8%',
        '$69.0', '-', '$11,698', '$5,338'],
       [201, 'Waste Management', '41,200', 221.0, '$13,609', '5.0%',
        '$1,182.0', '57.0%', '$20,859', '$32,216'],
       [211, 'Ecolab', '47,565', 206.0, '$13,153', '-2.9%', '$1,229.6',
        '22.7%', '$18,330', '$36,356'],
       [221, 'J.C. Penney', '1,06,000', 228.0, '$12,547', '-0.6%',
        '$1.0', '-', '$9,314', '$1,901'],
       [231, 'Devon Energy', '3,545', 216.0, '$12,197', '-7.2%',
        '-$3,302.0', '-', '$25,913', '$21,886'],
       [241, 'Hilton Worldwide Holdings', '1,69,000', 254.0, '$11,663',
        '3.5%', '$348.0', '-75.2%', '$26,211', '$19,276'],
       [251, 'Parker-Hannifin', '48,950', 224.0, '$11,361', '-10.6%',
        '$806.8', '-20.3%', '$12,057', '$21,370'],
       [261, 'Group 1 Automotive', '13,500', 267.0, '$10,888', '2.4%',
        '$147.1', '56.5%', '$4,462', '$1,584'],
       [271, 'State Street Corp.', '33,783', 264.0, '$10,635', '-1.2%',
        '$2,143.0', '8.2%', '$2,42,698', '$30,406'],
       [281, 'Baxter International', '48,000', 286.0, '$10,163', '2.0%',
        '$4,965.0', '412.9%', '$15,546', '$28,106'],
       [291, 'Murphy USA', '6,600', 258.0, '$9,633', '-11.5%', '$221.5',
        '25.6%', '$2,089', '$2,706'],
       [301, 'Fidelity National Information Services', '55,000', 392.0,
        '$9,241', '40.1%', '$568.0', '-10.1%', '$26,031', '$26,178'],
       [311, 'Mohawk Industries', '37,800', 338.0, '$8,959', '11.0%',
        '$930.4', '51.2%', '$10,231', '$17,025'],
       [321, 'GameStop', '41,750', 302.0, '$8,608', '-8.1%', '$353.2',
        '-12.3%', '$4,976', '$2,282'],
       [331, 'Veritiv', '8,700', 323.0, '$8,327', '-4.5%', '$21.0',
        '-21.3%', '$2,484', '$813'],
       [341, 'Weyerhaeuser', '10,400', 373.0, '$7,902', '11.6%',
        '$1,027.0', '103.0%', '$19,243', '$25,451'],
       [351, 'Dean Foods', '17,000', 336.0, '$7,710', '-5.1%', '$119.9',
        '-', '$2,606', '$1,786'],
       [361, 'Assurant', '14,700', 275.0, '$7,532', '-27.1%', '$565.4',
        '299.4%', '$29,709', '$5,298'],
       [371, 'Ralph Lauren', '20,500', 354.0, '$7,405', '-2.8%',
        '$396.0', '-43.6%', '$6,213', '$6,710'],
       [381, 'Leidos Holdings', '32,000', 504.0, '$7,043', '38.5%',
        '$244.0', '-3.9%', '$9,132', '$7,696'],
       [391, 'Jones Lang LaSalle', '77,300', 436.0, '$6,804', '14.0%',
        '$318.2', '-27.5%', '$7,629', '$5,043'],
       [401, 'Owens-Illinois', '27,000', 418.0, '$6,702', '8.9%',
        '$209.0', '54.8%', '$9,135', '$3,316'],
       [411, 'American Financial Group', '7,600', 421.0, '$6,498',
        '5.7%', '$649.0', '84.4%', '$55,072', '$8,303'],
       [421, 'Builders FirstSource', '14,000', 637.0, '$6,367', '78.6%',
        '$144.3', '-', '$2,910', '$1,669'],
       [431, 'Ameren', '8,629', 425.0, '$6,076', '-0.4%', '$653.0',
        '3.7%', '$24,699', '$13,245'],
       [441, 'AK Steel Holding', '8,500', 383.0, '$5,883', '-12.1%',
        '-$7.8', '-', '$4,036', '$2,263'],
       [451, 'Citizens Financial Group', '17,600', 486.0, '$5,763',
        '9.2%', '$1,045.0', '24.4%', '$1,49,520', '$17,597'],
       [461, 'Wyndham Worldwide', '37,800', 466.0, '$5,599', '1.1%',
        '$611.0', '-0.2%', '$9,819', '$8,829'],
       [471, 'Fiserv', '23,000', 492.0, '$5,505', '4.8%', '$930.0',
        '30.6%', '$9,743', '$24,741'],
       [481, 'Booz Allen Hamilton Holding', '22,600', 487.0, '$5,406',
        '2.5%', '$294.1', '26.5%', '$3,010', '$5,307'],
       [491, 'Liberty Media', '3,626', 525.0, '$5,276', '10.0%',
        '$680.0', '962.5%', '$31,377', '$13,055']], dtype=object)

In [26]:
data[:50,1]

array(['Walmart', 'Berkshire Hathaway', 'Apple', 'Exxon Mobil',
       'McKesson', 'UnitedHealth Group', 'CVS Health', 'General Motors',
       'AT&T', 'Ford Motor', 'AmerisourceBergen', 'Amazon.com',
       'General Electric', 'Verizon', 'Cardinal Health', 'Costco',
       'Walgreens Boots Alliance', 'Kroger', 'Chevron', 'Fannie Mae',
       'J.P. Morgan Chase', 'Express Scripts Holding', 'Home Depot',
       'Boeing', 'Wells Fargo', 'Bank of America Corp.', 'Alphabet',
       'Microsoft', 'Anthem', 'Citigroup', 'Comcast', 'IBM',
       'State Farm Insurance Cos.', 'Phillips 66', 'Johnson & Johnson',
       'Procter & Gamble', 'Valero Energy', 'Target', 'Freddie Mac',
       'LoweÕs', 'Dell Technologies', 'MetLife', 'Aetna', 'PepsiCo',
       'Archer Daniels Midland', 'UPS', 'Intel', 'Prudential Financial',
       'Albertsons Cos.', 'United Technologies'], dtype=object)

In [27]:
data[-50:,1]

array(['Citizens Financial Group', 'United Rentals', 'Clorox',
       'Genesis Healthcare', 'M&T Bank Corp.', 'Ingredion', 'UGI',
       'Owens Corning', 'S&P Global', 'Markel', 'Wyndham Worldwide',
       'Arthur J. Gallagher', 'Burlington Stores',
       'First American Financial', 'Symantec', 'Patterson', 'Olin',
       'NetApp', 'Raymond James Financial', 'TravelCenters of America',
       'Fiserv', 'Host Hotels & Resorts', 'Insight Enterprises', 'Mattel',
       'AmTrust Financial Services', 'Cincinnati Financial',
       'Simon Property Group', 'Western Union', 'KeyCorp',
       'Delek US Holdings', 'Booz Allen Hamilton Holding', 'Chemours',
       'Western & Southern Financial Group', 'Regions Financial',
       'Windstream Holdings', 'Seaboard', 'Essendant', 'Apache', 'Airgas',
       'Kelly Services', 'Liberty Media', 'Rockwell Collins',
       'Robert Half International', 'CH2M Hill', 'Big Lots',
       'Michaels Cos.', 'Toll Brothers', 'Yahoo', 'Vistra Energy',
       'ABM Industries'], dtype=object)

#Level 3 — Data Cleaning

Before solving these questions, clean these columns:

* Revenues
* Profits
* Assets
* Market Value

Remove:

* $
* commas

Convert them into float.

Then solve:

21. Find the maximum revenue.
22. Find the minimum revenue.
23. Find the average revenue.
24. Find the median revenue.
25. Find the standard deviation of revenue.
26. Find the company having maximum revenue.
27. Find the company having minimum revenue.
28. Find total profits.
29. Find average assets.
30. Find total market value.
31. Find company with highest assets.
32. Find company with lowest assets.
33. Count companies having profit greater than average profit.
34. Count companies having assets greater than average assets.
35. Find top 10 revenues.

In [28]:
clean_data = np.char.replace(np.char.replace(data[:,[4,6,8,9]].astype(str), "$", ""), ",", "")

In [29]:
clean_data[clean_data == '-'] = np.nan

In [30]:
clean_data = clean_data.astype(float)

In [31]:
clean_data[:,0].max()

np.float64(485873.0)

In [32]:
clean_data[:,0].min()

np.float64(5145.0)

In [33]:
clean_data[:,0].mean()

np.float64(24111.748)

In [34]:
np.median(clean_data[:,0])

np.float64(11384.0)

In [35]:
np.std(clean_data[:,0])

np.float64(38298.996795327366)

In [36]:
idx = clean_data[:,0].argmax()
data[idx, 1]

'Walmart'

In [37]:
idx = clean_data[:,0].argmin()
data[idx, 1]

'ABM Industries'

In [38]:
np.nansum(clean_data[:,1])

np.float64(889954.2)

In [39]:
np.nanmean(clean_data[:,2])

np.float64(80389.34)

In [40]:
np.nansum(clean_data[:,3])

np.float64(19421527.0)

In [41]:
np.nanmax(clean_data[:,2])

np.float64(3287968.0)

In [42]:
np.nanmin(clean_data[:,2])

np.float64(437.0)

In [43]:
np.count_nonzero(clean_data[:,3] > np.nanmean(clean_data[:,3]))

np.int64(119)

In [44]:
np.count_nonzero(clean_data[:,2] > np.nanmean(clean_data[:,2]))

np.int64(85)

In [45]:
sort_data = np.sort(clean_data[:,0])

In [46]:
sort_data[-10:]

array([151800., 163786., 166380., 177526., 184840., 192487., 205004.,
       215639., 223604., 485873.])

#Level 4 — Boolean Indexing

36. Companies having revenue greater than 100000.
37. Companies having profits greater than 10000.
38. Companies with market value greater than assets.
39. Companies having employee count greater than 100000.
40. Companies ranked below 50.
41. Companies ranked above 450.
42. Companies with profits less than zero (loss-making).
43. Companies with revenue above average.
44. Companies with assets below average.
45. Companies having market value above average.
46. Companies having profit greater than revenue (if any).
47. Companies whose previous rank is better than current rank.
48. Companies whose previous rank is worse than current rank.
49. Companies whose current rank remained unchanged.
50. Count all three categories above.

In [47]:
revenue = clean_data[:,0]
profits = clean_data[:,1]
assets = clean_data[:,2]
market_value = clean_data[:,3]

In [48]:
rev_great = revenue > 100000
data[rev_great,1]

array(['Walmart', 'Berkshire Hathaway', 'Apple', 'Exxon Mobil',
       'McKesson', 'UnitedHealth Group', 'CVS Health', 'General Motors',
       'AT&T', 'Ford Motor', 'AmerisourceBergen', 'Amazon.com',
       'General Electric', 'Verizon', 'Cardinal Health', 'Costco',
       'Walgreens Boots Alliance', 'Kroger', 'Chevron', 'Fannie Mae',
       'J.P. Morgan Chase', 'Express Scripts Holding'], dtype=object)

In [49]:
profit = profits > 10000
data[profit,1]

array(['Walmart', 'Berkshire Hathaway', 'Apple', 'AT&T', 'Verizon',
       'Fannie Mae', 'J.P. Morgan Chase', 'Wells Fargo',
       'Bank of America Corp.', 'Alphabet', 'Microsoft', 'Citigroup',
       'IBM', 'Johnson & Johnson', 'Procter & Gamble', 'Intel',
       'Cisco Systems', 'Gilead Sciences', 'Facebook', 'Altria Group'],
      dtype=object)

In [50]:
market_value_greater_than_assets = market_value > assets
data[market_value_greater_than_assets,1]

array(['Walmart', 'Apple', 'Exxon Mobil', 'UnitedHealth Group',
       'Amazon.com', 'Costco', 'Walgreens Boots Alliance', 'Home Depot',
       'Boeing', 'Alphabet', 'Microsoft', 'IBM', 'Johnson & Johnson',
       'Procter & Gamble', 'LoweÕs', 'PepsiCo', 'UPS', 'Intel',
       'United Technologies', 'Disney', 'Humana', 'Pfizer',
       'Lockheed Martin', 'Sysco', 'FedEx', 'Cisco Systems', 'HP',
       'Coca-Cola', 'Merck', 'Best Buy', 'Honeywell International',
       'Oracle', 'TJX', 'Nike', 'General Dynamics', 'Gilead Sciences',
       '3M', 'Time Warner', 'Facebook', 'Twenty-First Century Fox',
       'Philip Morris International', 'Avnet', 'AbbVie', 'McDonaldÕs',
       'DuPont', 'Northrop Grumman', 'Raytheon', 'Qualcomm',
       'Enterprise Products Partners', 'Amgen', 'Dollar General',
       'Starbucks', 'Eli Lilly', 'Abbott Laboratories', 'Dollar Tree',
       'Southwest Airlines', 'Emerson Electric', 'Union Pacific',
       'Danaher', 'Bristol-Myers Squibb', 'Altria Group',
       'Thermo Fisher Scientific', 'Kimberly-Clark', 'Cummins',
       'Marriott International', 'Paccar', 'General Mills', 'Nucor',
       'Halliburton', 'Whole Foods Market', 'Gap', 'Genuine Parts',
       'Colgate-Palmolive', 'PPG Industries', 'DISH Network', 'Visa',
       'CBS', 'WellCare Health Plans', 'ConAgra Foods', 'CDW',
       'Waste Management', 'Illinois Tool Works', 'Monsanto',
       'Cognizant Technology Solutions', 'Texas Instruments',
       'Marsh & McLennan', 'Ecolab', 'C.H. Robinson Worldwide',
       'CBRE Group', 'Kellogg', 'Ross Stores', 'L Brands',
       'Reynolds American', 'Becton Dickinson', 'Micron Technology', 'VF',
       'D.R. Horton', 'Sherwin-Williams', 'ADP', 'Henry Schein', 'Biogen',
       'Las Vegas Sands', 'Stanley Black & Decker', 'Parker-Hannifin',
       'Stryker', 'Estee Lauder', 'Celgene', 'CSX', 'PayPal Holdings',
       'Applied Materials', 'MasterCard', 'Priceline Group', 'AutoZone',
       'L-3 Communications', 'Praxair', 'Universal Health Services',
       'Occidental Petroleum', 'Baxter International', 'W.W. Grainger',
       'Autoliv', 'Baker Hughes', 'Laboratory Corp. of America',
       'Murphy USA', 'Advance Auto Parts', 'Air Products & Chemicals',
       'Hormel Foods', 'Republic Services',
       'Fidelity National Information Services', 'LKQ', 'BorgWarner',
       'eBay', 'Mohawk Industries', 'Netflix', 'Expedia',
       'OÕReilly Automotive', 'salesforce.com', 'Boston Scientific',
       'Campbell Soup', 'DickÕs Sporting Goods', 'Weyerhaeuser',
       'Steel Dynamics', 'Foot Locker', 'Quanta Services',
       'EOG Resources', 'Harris', 'HD Supply Holdings',
       'Quest Diagnostics', 'Hershey', 'Ralph Lauren', 'Masco',
       'Computer Sciences', 'Huntington Ingalls Industries', 'Tesla',
       'Darden Restaurants', 'Nvidia', 'Dover',
       'Spirit AeroSystems Holdings', 'Tractor Supply', 'Sealed Air',
       'Yum China Holdings', 'Franklin Resources', 'Activision Blizzard',
       'J.B. Hunt Transport Services', 'Constellation Brands',
       'Dr Pepper Snapple Group', 'Yum Brands', 'CaseyÕs General Stores',
       'Amphenol', 'Oshkosh', 'Expeditors International of Washington',
       'Avery Dennison', 'Hanesbrands', 'Motorola Solutions',
       'Harley-Davidson', 'Alaska Air Group', 'Lam Research',
       'Rockwell Automation', 'Adobe Systems', 'NVR', 'American Tower',
       'Packaging Corp. of America', 'Clorox', 'Ingredion', 'S&P Global',
       'Burlington Stores', 'Symantec', 'Patterson', 'NetApp', 'Fiserv',
       'Host Hotels & Resorts', 'Mattel', 'Simon Property Group',
       'Western Union', 'Booz Allen Hamilton Holding', 'Chemours',
       'Regions Financial', 'Seaboard', 'Rockwell Collins',
       'Robert Half International', 'Big Lots', 'Michaels Cos.',
       'ABM Industries'], dtype=object)

In [51]:
No_of_employees = np.char.replace(data[:,2].astype(str), ",", "").astype(float)

employee_count = No_of_employees > 100000
data[employee_count,1]

array(['Walmart', 'Berkshire Hathaway', 'Apple', 'UnitedHealth Group',
       'CVS Health', 'General Motors', 'AT&T', 'Ford Motor', 'Amazon.com',
       'General Electric', 'Verizon', 'Costco',
       'Walgreens Boots Alliance', 'Kroger', 'J.P. Morgan Chase',
       'Home Depot', 'Boeing', 'Wells Fargo', 'Bank of America Corp.',
       'Microsoft', 'Citigroup', 'Comcast', 'IBM', 'Johnson & Johnson',
       'Procter & Gamble', 'Target', 'LoweÕs', 'Dell Technologies',
       'PepsiCo', 'UPS', 'Intel', 'Albertsons Cos.',
       'United Technologies', 'Disney', 'FedEx',
       'Hewlett Packard Enterprise', 'HCA Holdings', 'Coca-Cola',
       'American Airlines Group', 'Best Buy', 'Honeywell International',
       'Oracle', 'Tyson Foods', 'Publix Super Markets', 'TJX', 'MacyÕs',
       'McDonaldÕs', 'Sears Holdings', 'Dollar General',
       'Community Health Systems', 'Starbucks', 'Tenet Healthcare',
       'Dollar Tree', 'Emerson Electric', 'Lear', 'Jabil Circuit',
       'Xerox', 'Marriott International', 'Gap', 'Aramark', 'Synnex',
       'Cognizant Technology Solutions', 'J.C. Penney',
       'Hilton Worldwide Holdings', 'Darden Restaurants',
       'Yum China Holdings', 'Host Hotels & Resorts', 'ABM Industries'],
      dtype=object)

In [52]:
rank = data[:,0].astype(float)

companies_rank_below_50 = rank < 50
data[companies_rank_below_50, 1]

array(['Walmart', 'Berkshire Hathaway', 'Apple', 'Exxon Mobil',
       'McKesson', 'UnitedHealth Group', 'CVS Health', 'General Motors',
       'AT&T', 'Ford Motor', 'AmerisourceBergen', 'Amazon.com',
       'General Electric', 'Verizon', 'Cardinal Health', 'Costco',
       'Walgreens Boots Alliance', 'Kroger', 'Chevron', 'Fannie Mae',
       'J.P. Morgan Chase', 'Express Scripts Holding', 'Home Depot',
       'Boeing', 'Wells Fargo', 'Bank of America Corp.', 'Alphabet',
       'Microsoft', 'Anthem', 'Citigroup', 'Comcast', 'IBM',
       'State Farm Insurance Cos.', 'Phillips 66', 'Johnson & Johnson',
       'Procter & Gamble', 'Valero Energy', 'Target', 'Freddie Mac',
       'LoweÕs', 'Dell Technologies', 'MetLife', 'Aetna', 'PepsiCo',
       'Archer Daniels Midland', 'UPS', 'Intel', 'Prudential Financial',
       'Albertsons Cos.'], dtype=object)

In [53]:
companies_rank_above_450 = rank > 450
data[companies_rank_above_450, 1]

array(['Citizens Financial Group', 'United Rentals', 'Clorox',
       'Genesis Healthcare', 'M&T Bank Corp.', 'Ingredion', 'UGI',
       'Owens Corning', 'S&P Global', 'Markel', 'Wyndham Worldwide',
       'Arthur J. Gallagher', 'Burlington Stores',
       'First American Financial', 'Symantec', 'Patterson', 'Olin',
       'NetApp', 'Raymond James Financial', 'TravelCenters of America',
       'Fiserv', 'Host Hotels & Resorts', 'Insight Enterprises', 'Mattel',
       'AmTrust Financial Services', 'Cincinnati Financial',
       'Simon Property Group', 'Western Union', 'KeyCorp',
       'Delek US Holdings', 'Booz Allen Hamilton Holding', 'Chemours',
       'Western & Southern Financial Group', 'Regions Financial',
       'Windstream Holdings', 'Seaboard', 'Essendant', 'Apache', 'Airgas',
       'Kelly Services', 'Liberty Media', 'Rockwell Collins',
       'Robert Half International', 'CH2M Hill', 'Big Lots',
       'Michaels Cos.', 'Toll Brothers', 'Yahoo', 'Vistra Energy',
       'ABM Industries'], dtype=object)

In [54]:
loss_making_companies = profits < 0
data[loss_making_companies, 1]

array(['Chevron', 'Dell Technologies', 'Albertsons Cos.', 'AIG',
       'Caterpillar', 'ConocoPhillips', 'Sears Holdings',
       'Community Health Systems', 'Tenet Healthcare', 'Staples', 'Xerox',
       'Icahn Enterprises', 'Halliburton', 'Freeport-McMoRan', 'WestRock',
       'AES', 'FirstEnergy', 'ConAgra Foods',
       'Farmers Insurance Exchange', 'Micron Technology', 'Alcoa',
       'NRG Energy', 'Devon Energy', 'NGL Energy Partners', 'Toys ÒRÓ Us',
       'Entergy', 'Voya Financial', 'HollyFrontier',
       'Occidental Petroleum', 'United States Steel', 'Baker Hughes',
       'Hertz Global Holdings', 'Alcoa', 'Frontier Communications',
       'Newmont Mining', 'Genworth Financial', 'Global Partners',
       'Navistar International', 'Univar', 'Chesapeake Energy',
       'Anadarko Petroleum', 'EOG Resources', 'Williams',
       'National Oilwell Varco', 'Kindred Healthcare', 'Tesla',
       'Ascena Retail Group', 'R.R. Donnelley & Sons', 'Targa Resources',
       'HRG Group', 'iHeartMedia', 'TreeHouse Foods', 'AK Steel Holding',
       'Avon Products', 'Terex', 'Genesis Healthcare', 'Olin',
       'TravelCenters of America', 'Delek US Holdings',
       'Windstream Holdings', 'Apache', 'Yahoo'], dtype=object)

In [55]:
companies_above_average_revenue = revenue > np.nanmean(revenue)
data[companies_above_average_revenue, 1]

array(['Walmart', 'Berkshire Hathaway', 'Apple', 'Exxon Mobil',
       'McKesson', 'UnitedHealth Group', 'CVS Health', 'General Motors',
       'AT&T', 'Ford Motor', 'AmerisourceBergen', 'Amazon.com',
       'General Electric', 'Verizon', 'Cardinal Health', 'Costco',
       'Walgreens Boots Alliance', 'Kroger', 'Chevron', 'Fannie Mae',
       'J.P. Morgan Chase', 'Express Scripts Holding', 'Home Depot',
       'Boeing', 'Wells Fargo', 'Bank of America Corp.', 'Alphabet',
       'Microsoft', 'Anthem', 'Citigroup', 'Comcast', 'IBM',
       'State Farm Insurance Cos.', 'Phillips 66', 'Johnson & Johnson',
       'Procter & Gamble', 'Valero Energy', 'Target', 'Freddie Mac',
       'LoweÕs', 'Dell Technologies', 'MetLife', 'Aetna', 'PepsiCo',
       'Archer Daniels Midland', 'UPS', 'Intel', 'Prudential Financial',
       'Albertsons Cos.', 'United Technologies', 'Marathon Petroleum',
       'Disney', 'Humana', 'Pfizer', 'AIG', 'Lockheed Martin', 'Sysco',
       'FedEx', 'Hewlett Packard Enterprise', 'Cisco Systems', 'HP',
       'Dow Chemical', 'HCA Holdings', 'Coca-Cola',
       'New York Life Insurance', 'Centene', 'American Airlines Group',
       'Nationwide', 'Merck', 'Cigna', 'Delta Air Lines', 'Best Buy',
       'Honeywell International', 'Caterpillar',
       'Liberty Mutual Insurance Group', 'Morgan Stanley',
       'Massachusetts Mutual Life Insurance', 'Goldman Sachs Group',
       'Energy Transfer Equity', 'TIAA', 'Oracle', 'Tyson Foods',
       'United Continental Holdings', 'Allstate', 'Publix Super Markets',
       'American Express', 'TJX', 'Nike', 'Exelon', 'General Dynamics',
       'Rite Aid', 'Gilead Sciences', 'CHS', '3M', 'Time Warner',
       'Charter Communications', 'Northwestern Mutual', 'Facebook',
       'Travelers Cos.', 'Capital One Financial',
       'Twenty-First Century Fox', 'USAA', 'World Fuel Services',
       'Philip Morris International', 'Deere', 'Kraft Heinz', 'Tech Data',
       'Avnet', 'Avnet', 'MacyÕs', 'AbbVie', 'McDonaldÕs', 'DuPont',
       'Northrop Grumman', 'ConocoPhillips'], dtype=object)

In [56]:
companies_below_average_assets = assets < np.nanmean(assets)
data[companies_below_average_assets, 1]

array(['McKesson', 'AmerisourceBergen', 'Cardinal Health', 'Costco',
       'Walgreens Boots Alliance', 'Kroger', 'Express Scripts Holding',
       'Home Depot', 'Anthem', 'Phillips 66', 'Valero Energy', 'Target',
       'LoweÕs', 'Aetna', 'PepsiCo', 'Archer Daniels Midland', 'UPS',
       'Albertsons Cos.', 'Marathon Petroleum', 'Humana',
       'Lockheed Martin', 'Sysco', 'FedEx', 'Hewlett Packard Enterprise',
       'HP', 'Dow Chemical', 'HCA Holdings', 'Centene',
       'American Airlines Group', 'Cigna', 'Delta Air Lines', 'Best Buy',
       'Honeywell International', 'Caterpillar', 'Energy Transfer Equity',
       'Tyson Foods', 'United Continental Holdings',
       'Publix Super Markets', 'TJX', 'Nike', 'General Dynamics',
       'Rite Aid', 'Gilead Sciences', 'CHS', '3M', 'Time Warner',
       'Facebook', 'Twenty-First Century Fox', 'World Fuel Services',
       'Philip Morris International', 'Deere', 'Tech Data', 'Avnet',
       'Avnet', 'MacyÕs', 'AbbVie', 'McDonaldÕs', 'DuPont',
       'Northrop Grumman', 'Raytheon', 'Tesoro', 'Arrow Electronics',
       'Qualcomm', 'Progressive', 'Enterprise Products Partners', 'Amgen',
       'US Foods Holding', 'Sears Holdings', 'Dollar General',
       'AutoNation', 'Community Health Systems', 'Starbucks', 'Eli Lilly',
       'International Paper', 'Tenet Healthcare', 'Abbott Laboratories',
       'Dollar Tree', 'Whirlpool', 'Southwest Airlines',
       'Emerson Electric', 'Staples', 'Plains GP Holdings',
       'Penske Automotive Group', 'Union Pacific', 'Danaher',
       'ManpowerGroup', 'Bristol-Myers Squibb', 'Altria Group', 'Fluor',
       'KohlÕs', 'Lear', 'Jabil Circuit', 'Thermo Fisher Scientific',
       'Kimberly-Clark', 'Molina Healthcare', 'PG&E Corp.', 'Supervalu',
       'Cummins', 'CenturyLink', 'AECOM', 'Xerox',
       'Marriott International', 'Paccar', 'General Mills',
       'American Electric Power', 'Icahn Enterprises', 'Nucor',
       'Performance Food Group', 'PBF Energy', 'Halliburton', 'CarMax',
       'Freeport-McMoRan', 'Whole Foods Market', 'Gap', 'Omnicom Group',
       'Genuine Parts', 'DaVita HealthCare Partners', 'Colgate-Palmolive',
       'PPG Industries', 'Goodyear Tire & Rubber', 'DISH Network', 'Visa',
       'Nordstrom', 'INTL FCStone', 'WestRock', 'XPO Logistics',
       'Aramark', 'CBS', 'AES', 'WellCare Health Plans', 'FirstEnergy',
       'ConAgra Foods', 'Synnex', 'CDW', 'Textron', 'Waste Management',
       'Illinois Tool Works', 'Office Depot', 'Monsanto',
       'Cognizant Technology Solutions', 'Texas Instruments',
       'Newell Brands', 'Land OÕLakes', 'Marsh & McLennan', 'Ecolab',
       'C.H. Robinson Worldwide', 'Loews', 'CBRE Group', 'Kinder Morgan',
       'Kellogg', 'Western Digital', 'Guardian Life Ins. Co. of America',
       'Ross Stores', 'L Brands', 'J.C. Penney',
       'Farmers Insurance Exchange', 'Reynolds American', 'Viacom',
       'Becton Dickinson', 'Micron Technology', 'Alcoa', 'NRG Energy',
       'VF', 'Devon Energy', 'D.R. Horton', 'Bed Bath & Beyond',
       'Consolidated Edison', 'Edison International', 'Sherwin-Williams',
       'NGL Energy Partners', 'Dominion Resources', 'ADP',
       'Hilton Worldwide Holdings', 'First Data', 'Henry Schein',
       'Toys ÒRÓ Us', 'Reinsurance Group of America', 'Core-Mark Holding',
       'Biogen', 'Las Vegas Sands', 'Stanley Black & Decker',
       'Parker-Hannifin', 'Stryker', 'Estee Lauder', 'Celgene',
       'Xcel Energy', 'CSX', 'Unum Group', 'Jacobs Engineering Group',
       'Lennar', 'Group 1 Automotive', 'Leucadia National', 'Entergy',
       'PayPal Holdings', 'Applied Materials', 'MasterCard',
       'Priceline Group', 'Liberty Interactive', 'AutoZone', 'DTE Energy',
       'L-3 Communications', 'HollyFrontier', 'Praxair',
       'Universal Health Services', 'Occidental Petroleum',
       'United States Steel', 'Sempra Energy', 'Baxter International',
       'W.W. Grainger', 'Autoliv', 'Norfolk Southern', 'Baker Hughes',
       'Sonic Automotive', 'Owens & Minor', 'Huntsman',
       'Laboratory Corp. of America', 'Murphy USA', 'Advance Auto Parts',
       'Fidelity National Financial', 'Air Products & Chemicals',
       'Hormel Foods', 'Hertz Global Holdings',
       'MGM Resorts International', 'Corning', 'Republic Services',
       'Alcoa', 'Fidelity National Information Services', 'LKQ',
       'BorgWarner', 'Ball', 'CST Brands',
       'Public Service Enterprise Group', 'Eastman Chemical', 'eBay',
       'Mohawk Industries', 'Oneok', 'Frontier Communications', 'Netflix',
       'American Family Insurance Group', 'Expedia', 'Lithia Motors',
       'Avis Budget Group', 'Reliance Steel & Aluminum', 'GameStop',
       'Tenneco', 'OÕReilly Automotive', 'Peter Kiewit SonsÕ',
       'United Natural Foods', 'salesforce.com', 'Boston Scientific',
       'Newmont Mining', 'Live Nation Entertainment', 'Veritiv',
       'News Corp.', 'Crown Holdings', 'Global Partners', 'PVH',
       'Level 3 Communications', 'Navistar International', 'Univar',
       'Campbell Soup', 'DickÕs Sporting Goods', 'Weyerhaeuser',
       'Mutual of Omaha Insurance', 'Chesapeake Energy',
       'Anadarko Petroleum', 'Interpublic Group', 'J.M. Smucker',
       'Steel Dynamics', 'Foot Locker', 'Western Refining', 'SpartanNash',
       'Dean Foods', 'Zimmer Biomet Holdings', 'PulteGroup',
       'W.R. Berkley', 'Quanta Services', 'EOG Resources',
       'Eversource Energy', 'Anixter International', 'EMCOR Group',
       'Assurant', 'CenterPoint Energy', 'Harris', 'HD Supply Holdings',
       'PPL', 'Quest Diagnostics', 'Williams', 'WEC Energy Group',
       'Hershey', 'AGCO', 'Ralph Lauren', 'Masco', 'WESCO International',
       'LifePoint Health', 'National Oilwell Varco', 'Kindred Healthcare',
       'Mosaic', 'Alliance Data Systems', 'Computer Sciences',
       'Huntington Ingalls Industries', 'Leidos Holdings',
       'Erie Insurance Group', 'Tesla', 'Ascena Retail Group',
       'Darden Restaurants', 'Harman International Industries', 'Nvidia',
       'R.R. Donnelley & Sons', 'Quintiles Transnational Holdings',
       'Jones Lang LaSalle', 'Dover', 'Spirit AeroSystems Holdings',
       'Ryder System', 'A-Mark Precious Metals', 'Tractor Supply',
       'Sealed Air', 'Auto-Owners Insurance', 'Yum China Holdings',
       'Calpine', 'Owens-Illinois', 'Targa Resources', 'JetBlue Airways',
       'Jones Financial', 'Franklin Resources', 'Activision Blizzard',
       'J.B. Hunt Transport Services', 'Constellation Brands', 'NCR',
       'Asbury Automotive Group', 'American Financial Group',
       'Discovery Communications', 'Berry Global Group', 'Sanmina',
       'CalAtlantic Group', 'Dr Pepper Snapple Group', 'DillardÕs',
       'HRG Group', 'CMS Energy', 'Graybar Electric',
       'Builders FirstSource', 'Yum Brands', 'CaseyÕs General Stores',
       'Amphenol', 'Oshkosh', 'iHeartMedia', 'TreeHouse Foods',
       'Alleghany', 'Expeditors International of Washington',
       'Avery Dennison', 'Ameren', 'Hanesbrands', 'Motorola Solutions',
       'St. Jude Medical', 'Harley-Davidson', 'Alaska Air Group',
       'Old Republic International', 'Lam Research', 'AK Steel Holding',
       'Rockwell Automation', 'Adobe Systems', 'Avon Products', 'Terex',
       'NVR', 'Dana Holding', 'Realogy Holdings', 'American Tower',
       'Packaging Corp. of America', 'United Rentals', 'Clorox',
       'Genesis Healthcare', 'Ingredion', 'UGI', 'Owens Corning',
       'S&P Global', 'Markel', 'Wyndham Worldwide', 'Arthur J. Gallagher',
       'Burlington Stores', 'First American Financial', 'Symantec',
       'Patterson', 'Olin', 'NetApp', 'Raymond James Financial',
       'TravelCenters of America', 'Fiserv', 'Host Hotels & Resorts',
       'Insight Enterprises', 'Mattel', 'AmTrust Financial Services',
       'Cincinnati Financial', 'Simon Property Group', 'Western Union',
       'Delek US Holdings', 'Booz Allen Hamilton Holding', 'Chemours',
       'Western & Southern Financial Group', 'Regions Financial',
       'Windstream Holdings', 'Seaboard', 'Essendant', 'Apache', 'Airgas',
       'Kelly Services', 'Liberty Media', 'Rockwell Collins',
       'Robert Half International', 'CH2M Hill', 'Big Lots',
       'Michaels Cos.', 'Toll Brothers', 'Yahoo', 'Vistra Energy',
       'ABM Industries'], dtype=object)

In [57]:
companies_above_average_market_value = market_value > np.nanmean(market_value)
data[companies_above_average_market_value, 1]

array(['Walmart', 'Berkshire Hathaway', 'Apple', 'Exxon Mobil',
       'UnitedHealth Group', 'CVS Health', 'General Motors', 'AT&T',
       'Ford Motor', 'Amazon.com', 'General Electric', 'Verizon',
       'Costco', 'Walgreens Boots Alliance', 'Chevron',
       'J.P. Morgan Chase', 'Home Depot', 'Boeing', 'Wells Fargo',
       'Bank of America Corp.', 'Alphabet', 'Microsoft', 'Anthem',
       'Citigroup', 'Comcast', 'IBM', 'Johnson & Johnson',
       'Procter & Gamble', 'LoweÕs', 'MetLife', 'Aetna', 'PepsiCo', 'UPS',
       'Intel', 'Prudential Financial', 'United Technologies', 'Disney',
       'Pfizer', 'AIG', 'Lockheed Martin', 'FedEx', 'Cisco Systems',
       'Dow Chemical', 'Coca-Cola', 'Merck', 'Honeywell International',
       'Caterpillar', 'Morgan Stanley', 'Goldman Sachs Group', 'Oracle',
       'American Express', 'TJX', 'Nike', 'General Dynamics',
       'Gilead Sciences', '3M', 'Time Warner', 'Charter Communications',
       'Facebook', 'Capital One Financial', 'Twenty-First Century Fox',
       'Philip Morris International', 'Kraft Heinz', 'Avnet', 'AbbVie',
       'McDonaldÕs', 'DuPont', 'Northrop Grumman', 'ConocoPhillips',
       'Raytheon', 'Qualcomm', 'Duke Energy',
       'Enterprise Products Partners', 'Amgen', 'U.S. Bancorp',
       'Starbucks', 'Eli Lilly', 'Abbott Laboratories', 'Union Pacific',
       'Danaher', 'Southern', 'Bristol-Myers Squibb', 'Altria Group',
       'Thermo Fisher Scientific', 'Kimberly-Clark',
       'PNC Financial Services Group', 'NextEra Energy', 'Halliburton',
       'Bank of New York Mellon Corp.', 'Colgate-Palmolive', 'Visa',
       'Illinois Tool Works', 'Monsanto', 'Texas Instruments',
       'Kinder Morgan', 'Reynolds American', 'Dominion Resources', 'ADP',
       'Biogen', 'Las Vegas Sands', 'Stryker', 'Celgene', 'BlackRock',
       'CSX', 'PayPal Holdings', 'Applied Materials', 'MasterCard',
       'Priceline Group', 'Occidental Petroleum', 'Netflix',
       'salesforce.com', 'EOG Resources', 'Charles Schwab', 'Tesla',
       'Nvidia', 'Adobe Systems', 'American Tower',
       'Simon Property Group', 'Yahoo'], dtype=object)

In [58]:
companies_having_profit_greater_than_revenue = profits > revenue
data[companies_having_profit_greater_than_revenue, 1]

array([], dtype=object)

In [59]:
prev_rank = data[:, 3].astype(float)

worsen_companies = rank < prev_rank
data[worsen_companies,1]

array(['Berkshire Hathaway', 'AT&T', 'AmerisourceBergen', 'Amazon.com',
       'Cardinal Health', 'Walgreens Boots Alliance', 'J.P. Morgan Chase',
       'Home Depot', 'Wells Fargo', 'Alphabet', 'Anthem', 'Comcast',
       'State Farm Insurance Cos.', 'Johnson & Johnson', 'Freddie Mac',
       'LoweÕs', 'Aetna', 'UPS', 'Intel', 'Prudential Financial',
       'Disney', 'Pfizer', 'Lockheed Martin', 'Centene', 'Nationwide',
       'Merck', 'Cigna', 'Honeywell International', 'Morgan Stanley',
       'TIAA', 'Publix Super Markets', 'TJX', 'Nike', 'Exelon',
       'Rite Aid', 'Time Warner', 'Charter Communications',
       'Northwestern Mutual', 'Facebook', 'Travelers Cos.',
       'Capital One Financial', 'USAA', 'Philip Morris International',
       'Kraft Heinz', 'Tech Data', 'AbbVie', 'Northrop Grumman',
       'Raytheon', 'Arrow Electronics', 'Progressive', 'Amgen',
       'U.S. Bancorp', 'Aflac', 'Dollar General', 'AutoNation',
       'Starbucks', 'Eli Lilly', 'Tenet Healthcare',
       'Abbott Laboratories', 'Dollar Tree', 'Southwest Airlines',
       'Penske Automotive Group', 'Southern', 'Bristol-Myers Squibb',
       'Altria Group', 'Fluor', 'Lear', 'Jabil Circuit',
       'Thermo Fisher Scientific', 'Molina Healthcare', 'PG&E Corp.',
       'Supervalu', 'Marriott International',
       'PNC Financial Services Group', 'Icahn Enterprises', 'Nucor',
       'Performance Food Group', 'PBF Energy', 'CarMax',
       'Whole Foods Market', 'Bank of New York Mellon Corp.',
       'Omnicom Group', 'Genuine Parts', 'DaVita HealthCare Partners',
       'DISH Network', 'Visa', 'Nordstrom', 'WestRock', 'XPO Logistics',
       'Aramark', 'CBS', 'WellCare Health Plans', 'Synnex', 'CDW',
       'Textron', 'Waste Management', 'Illinois Tool Works',
       'Cognizant Technology Solutions', 'Texas Instruments',
       'Newell Brands', 'Land OÕLakes', 'Marsh & McLennan', 'CBRE Group',
       'Guardian Life Ins. Co. of America', 'Ross Stores', 'L Brands',
       'J.C. Penney', 'Farmers Insurance Exchange', 'Reynolds American',
       'Becton Dickinson', 'Principal Financial', 'VF', 'D.R. Horton',
       'Bed Bath & Beyond', 'Edison International', 'Sherwin-Williams',
       'Dominion Resources', 'ADP', 'Hilton Worldwide Holdings',
       'First Data', 'Henry Schein', 'BB&T Corp.',
       'Reinsurance Group of America', 'Core-Mark Holding', 'Biogen',
       'Stanley Black & Decker', 'Stryker', 'Estee Lauder', 'Celgene',
       'Xcel Energy', 'Unum Group', 'Lennar', 'Group 1 Automotive',
       'PayPal Holdings', 'Applied Materials', 'MasterCard',
       'Priceline Group', 'Liberty Interactive', 'AutoZone', 'DTE Energy',
       'Universal Health Services', 'Discover Financial Services',
       'Baxter International', 'W.W. Grainger', 'Autoliv',
       'Ally Financial', 'Sonic Automotive', 'Owens & Minor',
       'Laboratory Corp. of America', 'Advance Auto Parts',
       'Fidelity National Financial', 'Hormel Foods',
       'MGM Resorts International', 'Corning', 'Republic Services',
       'Fidelity National Information Services', 'Pacific Life',
       'SunTrust Banks', 'LKQ', 'BorgWarner', 'Ball', 'Mohawk Industries',
       'Oneok', 'Frontier Communications', 'Netflix',
       'American Family Insurance Group',
       'Thrivent Financial for Lutherans', 'Expedia', 'Lithia Motors',
       'Avis Budget Group', 'Tenneco', 'OÕReilly Automotive',
       'United Natural Foods', 'salesforce.com', 'Boston Scientific',
       'Newmont Mining', 'Live Nation Entertainment', 'PVH',
       'DickÕs Sporting Goods', 'Weyerhaeuser',
       'Mutual of Omaha Insurance', 'Interpublic Group', 'J.M. Smucker',
       'Steel Dynamics', 'Foot Locker', 'SpartanNash',
       'Zimmer Biomet Holdings', 'PulteGroup', 'W.R. Berkley',
       'Charles Schwab', 'Anixter International', 'EMCOR Group',
       'CenterPoint Energy', 'Harris', 'WEC Energy Group',
       'LifePoint Health', 'Alliance Data Systems', 'Leidos Holdings',
       'Erie Insurance Group', 'Tesla', 'Ascena Retail Group',
       'Harman International Industries', 'Nvidia',
       'Quintiles Transnational Holdings', 'Jones Lang LaSalle',
       'Ryder System', 'A-Mark Precious Metals', 'Tractor Supply',
       'Calpine', 'Owens-Illinois', 'JetBlue Airways',
       'Activision Blizzard', 'J.B. Hunt Transport Services',
       'Constellation Brands', 'American Financial Group',
       'Berry Global Group', 'CalAtlantic Group', 'HRG Group',
       'Graybar Electric', 'Builders FirstSource', 'Amphenol',
       'TreeHouse Foods', 'Alleghany', 'Avery Dennison', 'Hanesbrands',
       'Motorola Solutions', 'St. Jude Medical', 'Regions Financial',
       'Intercontinental Exchange', 'Alaska Air Group',
       'Old Republic International', 'Lam Research', 'Adobe Systems',
       'NVR', 'Realogy Holdings', 'American Tower',
       'Citizens Financial Group', 'Clorox', 'Genesis Healthcare',
       'M&T Bank Corp.', 'Owens Corning', 'S&P Global', 'Markel',
       'Wyndham Worldwide', 'Arthur J. Gallagher', 'Burlington Stores',
       'First American Financial', 'Patterson', 'Olin',
       'Raymond James Financial', 'Fiserv', 'Insight Enterprises',
       'AmTrust Financial Services', 'Cincinnati Financial',
       'Simon Property Group', 'KeyCorp', 'Booz Allen Hamilton Holding',
       'Liberty Media', 'Robert Half International', 'Michaels Cos.',
       'Toll Brothers', 'Yahoo'], dtype=object)

In [60]:
improved_companies = rank > prev_rank
data[improved_companies,1]

array(['Exxon Mobil', 'Ford Motor', 'General Electric', 'Verizon',
       'Costco', 'Kroger', 'Chevron', 'Fannie Mae', 'Microsoft',
       'Citigroup', 'IBM', 'Phillips 66', 'Procter & Gamble',
       'Valero Energy', 'MetLife', 'Archer Daniels Midland',
       'United Technologies', 'Marathon Petroleum', 'Humana', 'AIG',
       'Cisco Systems', 'HP', 'Dow Chemical', 'Coca-Cola',
       'New York Life Insurance', 'Delta Air Lines', 'Best Buy',
       'Caterpillar', 'Liberty Mutual Insurance Group',
       'Massachusetts Mutual Life Insurance', 'Goldman Sachs Group',
       'Energy Transfer Equity', 'Oracle', 'Tyson Foods',
       'United Continental Holdings', 'Allstate', 'American Express',
       'General Dynamics', 'Gilead Sciences', 'CHS', '3M',
       'Twenty-First Century Fox', 'World Fuel Services', 'Deere',
       'Avnet', 'Avnet', 'MacyÕs', 'McDonaldÕs', 'DuPont',
       'ConocoPhillips', 'Tesoro', 'Qualcomm', 'Duke Energy',
       'Enterprise Products Partners', 'US Foods Holding',
       'Sears Holdings', 'Community Health Systems',
       'International Paper', 'Whirlpool', 'Emerson Electric', 'Staples',
       'Plains GP Holdings', 'Union Pacific', 'Danaher', 'ManpowerGroup',
       'KohlÕs', 'Hartford Financial Services Group', 'Kimberly-Clark',
       'Cummins', 'CenturyLink', 'AECOM', 'Xerox', 'Paccar',
       'General Mills', 'American Electric Power', 'NextEra Energy',
       'Halliburton', 'Gap', 'Colgate-Palmolive', 'PPG Industries',
       'Goodyear Tire & Rubber', 'INTL FCStone', 'AES', 'FirstEnergy',
       'ConAgra Foods', 'Office Depot', 'Monsanto', 'Lincoln National',
       'Ecolab', 'C.H. Robinson Worldwide', 'Loews', 'Kinder Morgan',
       'Kellogg', 'Western Digital', 'Viacom', 'Micron Technology',
       'Alcoa', 'NRG Energy', 'Devon Energy', 'Consolidated Edison',
       'NGL Energy Partners', 'Ameriprise Financial', 'Toys ÒRÓ Us',
       'Las Vegas Sands', 'Parker-Hannifin', 'BlackRock', 'CSX',
       'Jacobs Engineering Group', 'Leucadia National', 'Entergy',
       'Voya Financial', 'State Street Corp.', 'L-3 Communications',
       'HollyFrontier', 'Praxair', 'Occidental Petroleum',
       'United States Steel', 'Sempra Energy', 'Norfolk Southern',
       'Baker Hughes', 'Huntsman', 'Murphy USA',
       'Air Products & Chemicals', 'Hertz Global Holdings', 'CST Brands',
       'Public Service Enterprise Group', 'Eastman Chemical', 'eBay',
       'Reliance Steel & Aluminum', 'GameStop', 'Peter Kiewit SonsÕ',
       'Genworth Financial', 'Veritiv', 'News Corp.', 'Crown Holdings',
       'Global Partners', 'Level 3 Communications',
       'Navistar International', 'Univar', 'Campbell Soup',
       'Chesapeake Energy', 'Anadarko Petroleum', 'Western Refining',
       'Dean Foods', 'Quanta Services', 'EOG Resources',
       'Eversource Energy', 'Assurant', 'HD Supply Holdings', 'PPL',
       'Quest Diagnostics', 'Williams', 'Hershey', 'AGCO', 'Ralph Lauren',
       'Masco', 'WESCO International', 'National Oilwell Varco',
       'Kindred Healthcare', 'Mosaic', 'Computer Sciences',
       'Huntington Ingalls Industries', 'Darden Restaurants',
       'R.R. Donnelley & Sons', 'Fifth Third Bancorp', 'Dover',
       'Spirit AeroSystems Holdings', 'Sealed Air', 'Targa Resources',
       'Jones Financial', 'Franklin Resources', 'Asbury Automotive Group',
       'Discovery Communications', 'Sanmina', 'Dr Pepper Snapple Group',
       'DillardÕs', 'CMS Energy', 'Yum Brands', 'CaseyÕs General Stores',
       'Oshkosh', 'iHeartMedia', 'Expeditors International of Washington',
       'Ameren', 'Harley-Davidson', 'AK Steel Holding',
       'Rockwell Automation', 'Avon Products', 'Terex', 'Dana Holding',
       'Packaging Corp. of America', 'United Rentals', 'UGI', 'Symantec',
       'NetApp', 'TravelCenters of America', 'Mattel', 'Western Union',
       'Delek US Holdings', 'Western & Southern Financial Group',
       'Regions Financial', 'Windstream Holdings', 'Seaboard',
       'Essendant', 'Apache', 'Airgas', 'Kelly Services',
       'Rockwell Collins', 'CH2M Hill', 'ABM Industries'], dtype=object)

In [61]:
No_rank_changed_companies = rank == prev_rank
data[No_rank_changed_companies,1]

array(['Walmart', 'Apple', 'McKesson', 'UnitedHealth Group', 'CVS Health',
       'General Motors', 'Express Scripts Holding', 'Boeing',
       'Bank of America Corp.', 'Target', 'PepsiCo', 'Sysco', 'FedEx',
       'HCA Holdings', 'American Airlines Group', 'Freeport-McMoRan',
       'Auto-Owners Insurance', 'NCR', 'Ingredion',
       'Host Hotels & Resorts', 'Big Lots'], dtype=object)

In [62]:
data[worsen_companies,1].size

262

In [63]:
data[improved_companies,1].size

209

In [64]:
data[No_rank_changed_companies,1].size

21

#Level 5 — NumPy Functions

51. Sort companies by revenue.
52. Sort companies by profits.
53. Sort companies by market value.
54. Find indices of top 10 revenues.
55. Find indices of top 20 profits.
56. Find bottom 20 market values.
57. Use np.argsort() to sort companies by assets.
58. Use np.argmin() to find lowest revenue company.
59. Use np.argmax() to find highest market value company.
60. Find second highest revenue.
61. Find third highest profit.
62. Find top 5 assets.
63. Find bottom 5 assets.
64. Count NaN values (if any).
65. Replace NaN values using NumPy.

In [65]:
revenue_sort = np.argsort(revenue)
data[revenue_sort]

array([[500, 'ABM Industries', '1,10,000', ..., '-25.0%', '$2,281',
        '$2,428'],
       [499, 'Vistra Energy', '4,431', ..., '-', '$15,167', '$6,968'],
       [498, 'Yahoo', '8,500', ..., '-', '$48,083', '$44,391'],
       ...,
       [3, 'Apple', '1,16,000', ..., '-14.4%', '$3,21,686', '$7,53,718'],
       [2, 'Berkshire Hathaway', '3,67,700', ..., '0.0%', '$6,20,854',
        '$4,11,035'],
       [1, 'Walmart', '23,00,000', ..., '-7.2%', '$1,98,825',
        '$2,18,619']], shape=(500, 10), dtype=object)

In [66]:
profit_sort = np.argsort(profits)
data[profit_sort]

array([[196, 'FirstEnergy', '15,707', ..., '-', '$43,148', '$14,118'],
       [173, 'Halliburton', '50,000', ..., '-', '$27,000', '$42,662'],
       [343, 'Chesapeake Energy', '3,300', ..., '-', '$13,028', '$5,394'],
       ...,
       [21, 'J.P. Morgan Chase', '2,43,355', ..., '1.2%', '$24,90,972',
        '$3,13,761'],
       [3, 'Apple', '1,16,000', ..., '-14.4%', '$3,21,686', '$7,53,718'],
       [499, 'Vistra Energy', '4,431', ..., '-', '$15,167', '$6,968']],
      shape=(500, 10), dtype=object)

In [67]:
sort_market_value = np.argsort(market_value)
data[sort_market_value]

array([[395, 'A-Mark Precious Metals', '83,000', ..., '31.5%', '$437',
        '$120'],
       [470, 'TravelCenters of America', '20,259', ..., '-107.3%',
        '$1,660', '$241'],
       [426, 'iHeartMedia', '18,700', ..., '-', '$12,862', '$330'],
       ...,
       [382, 'Erie Insurance Group', '4,988', ..., '10.7%', '$18,417',
        '-'],
       [244, 'Toys ÒRÓ Us', '64,000', ..., '-', '$6,908', '-'],
       [420, 'Graybar Electric', '8,500', ..., '2.2%', '$2,099', '-']],
      shape=(500, 10), dtype=object)

In [68]:
top_10_revenue = np.argsort(revenue)[-10:]
top_10_revenue

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [69]:
top_20_profit = np.argsort(profits)[-20:]
top_20_profit

array([ 46,  35,  59,  31,  19,   8,  13,  91,   0, 147,  29,  34,  27,
        25,  26,  24,   1,  20,   2, 498])

In [70]:
bottom_20_market_value = np.argsort(market_value)[:20]
data[bottom_20_market_value]

array([[395, 'A-Mark Precious Metals', '83,000', 426.0, '$6,784',
        '11.8%', '$9.3', '31.5%', '$437', '$120'],
       [470, 'TravelCenters of America', '20,259', 439.0, '$5,511',
        '-5.8%', '-$2.0', '-107.3%', '$1,660', '$241'],
       [426, 'iHeartMedia', '18,700', 414.0, '$6,274', '0.5%', '-$296.3',
        '-', '$12,862', '$330'],
       [454, 'Genesis Healthcare', '82,000', 457.0, '$5,733', '2.0%',
        '-$64.0', '-', '$5,779', '$408'],
       [487, 'Essendant', '6,600', 477.0, '$5,369', '0.1%', '$63.9', '-',
        '$2,164', '$568'],
       [334, 'Global Partners', '1,770', 276.0, '$8,240', '-20.1%',
        '-$199.4', '-557.8%', '$2,564', '$663'],
       [189, 'INTL FCStone', '1,464', 83.0, '$14,755', '-57.5%', '$54.7',
        '-1.8%', '$5,951', '$708'],
       [376, 'Kindred Healthcare', '76,650', 372.0, '$7,227', '1.8%',
        '-$664.2', '-', '$6,113', '$711'],
       [331, 'Veritiv', '8,700', 323.0, '$8,327', '-4.5%', '$21.0',
        '-21.3%', '$2,484', '$813'],
       [384, 'Ascena Retail Group', '41,000', 523.0, '$6,995', '45.6%',
        '-$11.9', '-', '$5,506', '$830'],
       [490, 'Kelly Services', '7,500', 467.0, '$5,277', '-4.4%',
        '$120.8', '124.5%', '$2,028', '$836'],
       [388, 'R.R. Donnelley & Sons', '44,360', 255.0, '$6,896',
        '-38.7%', '-$495.9', '-428.2%', '$4,285', '$846'],
       [287, 'Sonic Automotive', '9,800', 297.0, '$9,732', '1.1%',
        '$93.2', '8.0%', '$3,639', '$900'],
       [130, 'Community Health Systems', '1,08,000', 125.0, '$21,374',
        '-5.8%', '-$1,721.0', '-', '$21,944', '$1,010'],
       [158, 'Supervalu', '38,000', 160.0, '$17,529', '-1.6%', '$178.0',
        '-7.3%', '$4,370', '$1,033'],
       [485, 'Windstream Holdings', '11,870', 443.0, '$5,387', '-6.6%',
        '-$383.5', '-', '$11,770', '$1,038'],
       [127, 'Sears Holdings', '1,40,000', 111.0, '$22,138', '-12.0%',
        '-$2,221.0', '-', '$9,362', '$1,231'],
       [410, 'Asbury Automotive Group', '7,900', 393.0, '$6,528',
        '-0.9%', '$167.2', '-1.2%', '$2,336', '$1,271'],
       [350, 'SpartanNash', '11,500', 351.0, '$7,735', '1.1%', '$56.8',
        '-9.4%', '$1,930', '$1,313'],
       [247, 'Core-Mark Holding', '7,688', 317.0, '$11,507', '29.9%',
        '$54.2', '5.2%', '$1,497', '$1,445']], dtype=object)

In [71]:
Sort_assets = np.argsort(assets)
data[Sort_assets]

array([[395, 'A-Mark Precious Metals', '83,000', ..., '31.5%', '$437',
        '$120'],
       [247, 'Core-Mark Holding', '7,688', ..., '5.2%', '$1,497',
        '$1,445'],
       [495, 'Big Lots', '23,150', ..., '7.0%', '$1,608', '$2,180'],
       ...,
       [26, 'Bank of America Corp.', '2,08,024', ..., '12.7%',
        '$21,87,702', '$2,36,182'],
       [21, 'J.P. Morgan Chase', '2,43,355', ..., '1.2%', '$24,90,972',
        '$3,13,761'],
       [20, 'Fannie Mae', '7,000', ..., '12.4%', '$32,87,968', '$3,011']],
      shape=(500, 10), dtype=object)

In [72]:
lowest_revenue_company = np.argmin(revenue)
data[lowest_revenue_company]

array([500, 'ABM Industries', '1,10,000', 485.0, '$5,145', '-2.8%',
       '$57.2', '-25.0%', '$2,281', '$2,428'], dtype=object)

In [73]:
highest_market_value_company = np.argmax(market_value)
data[highest_market_value_company]

array([33, 'State Farm Insurance Cos.', '68,234', 35.0, '$76,132', '0.6%',
       '$350.3', '-94.4%', '$2,56,030', '-'], dtype=object)

In [74]:
data[np.argsort(revenue)[-2]]

array([2, 'Berkshire Hathaway', '3,67,700', 4.0, '$2,23,604', '6.1%',
       '$24,074.0', '0.0%', '$6,20,854', '$4,11,035'], dtype=object)

In [75]:
data[np.argsort(profits)[-3]]

array([21, 'J.P. Morgan Chase', '2,43,355', 23.0, '$1,05,486', '4.4%',
       '$24,733.0', '1.2%', '$24,90,972', '$3,13,761'], dtype=object)

In [76]:
data[np.argsort(assets)[-5:]]

array([[25, 'Wells Fargo', '2,69,100', 27.0, '$94,176', '4.6%',
        '$21,938.0', '-4.2%', '$19,30,115', '$2,78,516'],
       [39, 'Freddie Mac', '5,982', 43.0, '$65,665', '3.4%', '$7,815.0',
        '22.6%', '$20,23,376', '$1,612'],
       [26, 'Bank of America Corp.', '2,08,024', 26.0, '$93,662', '0.7%',
        '$17,906.0', '12.7%', '$21,87,702', '$2,36,182'],
       [21, 'J.P. Morgan Chase', '2,43,355', 23.0, '$1,05,486', '4.4%',
        '$24,733.0', '1.2%', '$24,90,972', '$3,13,761'],
       [20, 'Fannie Mae', '7,000', 16.0, '$1,07,162', '-2.9%',
        '$12,313.0', '12.4%', '$32,87,968', '$3,011']], dtype=object)

In [77]:
data[np.argsort(assets)[:5]]

array([[395, 'A-Mark Precious Metals', '83,000', 426.0, '$6,784',
        '11.8%', '$9.3', '31.5%', '$437', '$120'],
       [247, 'Core-Mark Holding', '7,688', 317.0, '$11,507', '29.9%',
        '$54.2', '5.2%', '$1,497', '$1,445'],
       [495, 'Big Lots', '23,150', 495.0, '$5,200', '0.2%', '$152.8',
        '7.0%', '$1,608', '$2,180'],
       [470, 'TravelCenters of America', '20,259', 439.0, '$5,511',
        '-5.8%', '-$2.0', '-107.3%', '$1,660', '$241'],
       [493, 'Robert Half International', '16,400', 503.0, '$5,250',
        '3.1%', '$343.4', '-4.0%', '$1,778', '$6,240']], dtype=object)

In [78]:
np.count_nonzero(np.isnan(clean_data))

np.int64(31)

In [79]:
for i in range(clean_data.shape[1]):
    column = clean_data[:, i]

    # find NaN values
    mask = np.isnan(column)

    # calculate column mean
    mean = np.nanmean(column)

    # replace NaN
    column[mask] = mean

# Level 6 — Advanced NumPy

66. Normalize revenues using Min-Max Scaling.
67. Standardize profits using Z-score normalization.
68. Create a NumPy array containing only:
- Revenue
- Profit
- Assets
69. Compute column-wise mean.
70. Compute row-wise mean.
71. Compute covariance matrix.
72. Compute correlation matrix.
73. Find percentile values:
- 25th
- 50th
- 75th
74. Find Interquartile Range (IQR).
75. Detect revenue outliers using IQR.
76. Detect profit outliers.
77. Find revenue quartiles.
78. Split data into 5 equal chunks using NumPy.
79. Randomly sample 25 companies.
80. Shuffle the dataset using NumPy.

In [80]:
revenue_scaled = (revenue - np.nanmin(revenue))/(np.nanmax(revenue)-np.nanmin(revenue))
revenue_scaled

array([1.00000000e+00, 4.54433692e-01, 4.37865071e-01, 4.15742374e-01,
       3.89704781e-01, 3.73797657e-01, 3.58583232e-01, 3.35397564e-01,
       3.30001581e-01, 3.05068563e-01, 2.94771680e-01, 2.72174702e-01,
       2.52774958e-01, 2.51358356e-01, 2.42134845e-01, 2.36254181e-01,
       2.33408497e-01, 2.29219018e-01, 2.13056032e-01, 2.12213559e-01,
       2.08727180e-01, 1.97914413e-01, 1.86071958e-01, 1.86022033e-01,
       1.85200363e-01, 1.84131151e-01, 1.77079346e-01, 1.66778303e-01,
       1.65827661e-01, 1.60675059e-01, 1.56550066e-01, 1.55543259e-01,
       1.47665624e-01, 1.39894077e-01, 1.38841507e-01, 1.38500358e-01,
       1.35255279e-01, 1.33859480e-01, 1.25892397e-01, 1.24544441e-01,
       1.24105523e-01, 1.21338886e-01, 1.20671149e-01, 1.19930605e-01,
       1.18988284e-01, 1.15992828e-01, 1.12833037e-01, 1.11568288e-01,
       1.11474680e-01, 1.08375214e-01, 1.05492087e-01, 1.05021967e-01,
       1.02415503e-01, 9.91808257e-02, 9.82301842e-02, 9.46751593e-02,
       9.40698274e-02, 9.40656671e-02, 9.35622639e-02, 9.17400276e-02,
       8.96411276e-02, 8.94747134e-02, 8.23792248e-02, 7.63799903e-02,
       7.41417184e-02, 7.40044266e-02, 7.28790501e-02, 7.26585512e-02,
       7.21031436e-02, 7.18139988e-02, 7.17536736e-02, 7.12627515e-02,
       7.10526535e-02, 6.94613170e-02, 6.89849561e-02, 6.82381721e-02,
       6.79032634e-02, 6.77451698e-02, 6.73124927e-02, 6.64825015e-02,
       6.63618512e-02, 6.60165416e-02, 6.53404836e-02, 6.52947197e-02,
       6.05935165e-02, 5.96553560e-02, 5.83261220e-02, 5.66453379e-02,
       5.45318767e-02, 5.45173154e-02, 5.32359255e-02, 5.25141036e-02,
       5.24246559e-02, 5.19295735e-02, 5.02841524e-02, 4.96288962e-02,
       4.92045398e-02, 4.67894527e-02, 4.67624103e-02, 4.65419114e-02,
       4.61404370e-02, 4.57348022e-02, 4.54955817e-02, 4.48070427e-02,
       4.47217553e-02, 4.43951673e-02, 4.38709624e-02, 4.38376795e-02,
       4.32219467e-02, 4.29203208e-02, 4.26290959e-02, 4.05156346e-02,
       4.04573896e-02, 4.02784943e-02, 3.99706279e-02, 3.93652960e-02,
       3.92321646e-02, 3.88577324e-02, 3.82940041e-02, 3.80589439e-02,
       3.79091711e-02, 3.71873492e-02, 3.71228637e-02, 3.69730908e-02,
       3.66090596e-02, 3.62242266e-02, 3.53484715e-02, 3.50343645e-02,
       3.42480571e-02, 3.37592152e-02, 3.36385648e-02, 3.34430281e-02,
       3.31455626e-02, 3.31268410e-02, 3.26754422e-02, 3.23966983e-02,
       3.23946182e-02, 3.17851259e-02, 3.14585379e-02, 3.13524488e-02,
       3.12796425e-02, 3.11985156e-02, 3.07783195e-02, 3.07179944e-02,
       3.06847115e-02, 3.01813083e-02, 2.97091079e-02, 2.95218918e-02,
       2.88978383e-02, 2.81676957e-02, 2.79014328e-02, 2.74749963e-02,
       2.73647468e-02, 2.73106622e-02, 2.71608893e-02, 2.62872144e-02,
       2.60459137e-02, 2.57609293e-02, 2.57193257e-02, 2.56381987e-02,
       2.55154682e-02, 2.49226174e-02, 2.48102877e-02, 2.47291608e-02,
       2.37514769e-02, 2.34602520e-02, 2.33708043e-02, 2.33042386e-02,
       2.30130136e-02, 2.29027641e-02, 2.27987552e-02, 2.24139222e-02,
       2.23452763e-02, 2.22329467e-02, 2.21414188e-02, 2.20062073e-02,
       2.19209199e-02, 2.15735301e-02, 2.13675925e-02, 2.12074187e-02,
       2.09099532e-02, 2.09057929e-02, 2.08704298e-02, 2.08288263e-02,
       2.07539399e-02, 2.06977750e-02, 2.06707327e-02, 1.99946747e-02,
       1.99905144e-02, 1.98885856e-02, 1.97076101e-02, 1.92853339e-02,
       1.92229286e-02, 1.90169909e-02, 1.89129820e-02, 1.87444875e-02,
       1.86987236e-02, 1.85489508e-02, 1.83825365e-02, 1.79789819e-02,
       1.76066299e-02, 1.75858282e-02, 1.75567057e-02, 1.73840509e-02,
       1.73528482e-02, 1.71094673e-02, 1.70262602e-02, 1.68889684e-02,
       1.68244829e-02, 1.67787189e-02, 1.66580686e-02, 1.66393470e-02,
       1.65582200e-02, 1.64895741e-02, 1.64604516e-02, 1.63689238e-02,
       1.63273202e-02, 1.61713069e-02, 1.60631376e-02, 1.54536453e-02,
       1.53974805e-02, 1.53267544e-02, 1.53059526e-02, 1.52747500e-02,
       1.52643491e-02, 1.50896141e-02, 1.50792132e-02, 1.50792132e-02,
       1.49897655e-02, 1.46902198e-02, 1.46694180e-02, 1.45862109e-02,
       1.44759615e-02, 1.44156363e-02, 1.39871195e-02, 1.39600772e-02,
       1.37229369e-02, 1.37125360e-02, 1.37083756e-02, 1.35690037e-02,
       1.35586028e-02, 1.33942687e-02, 1.33693066e-02, 1.33027408e-02,
       1.32985805e-02, 1.32652976e-02, 1.32340950e-02, 1.31134446e-02,
       1.30323177e-02, 1.30260771e-02, 1.29303889e-02, 1.28555025e-02,
       1.27244512e-02, 1.26558054e-02, 1.25018722e-02, 1.24020236e-02,
       1.23229768e-02, 1.22772129e-02, 1.21045581e-02, 1.20754356e-02,
       1.19464645e-02, 1.19194222e-02, 1.18590970e-02, 1.18507763e-02,
       1.18154133e-02, 1.17259656e-02, 1.17134845e-02, 1.16448387e-02,
       1.14451415e-02, 1.14222596e-02, 1.14201794e-02, 1.14097785e-02,
       1.13411326e-02, 1.12142417e-02, 1.12100814e-02, 1.11559967e-02,
       1.11331148e-02, 1.09271771e-02, 1.06421927e-02, 1.04799388e-02,
       1.04383352e-02, 1.03842506e-02, 1.02531993e-02, 9.86628613e-03,
       9.76851775e-03, 9.75603668e-03, 9.54177830e-03, 9.52305670e-03,
       9.38576492e-03, 9.35456225e-03, 9.33584064e-03, 9.20062905e-03,
       9.17150655e-03, 9.10910120e-03, 9.10702102e-03, 9.01757335e-03,
       8.96556889e-03, 8.83035729e-03, 8.82619693e-03, 8.68058445e-03,
       8.52041071e-03, 8.37063787e-03, 8.35399644e-03, 8.18966235e-03,
       8.16678038e-03, 8.14597860e-03, 8.14597860e-03, 8.14597860e-03,
       8.03572914e-03, 7.97540397e-03, 7.93380040e-03, 7.85475362e-03,
       7.80274916e-03, 7.66753757e-03, 7.66337721e-03, 7.55520793e-03,
       7.54896740e-03, 7.34927027e-03, 7.30974688e-03, 7.21405868e-03,
       7.20365779e-03, 7.18493618e-03, 7.17245511e-03, 7.13085154e-03,
       6.91659317e-03, 6.75433925e-03, 6.74185818e-03, 6.72729693e-03,
       6.70649515e-03, 6.67737265e-03, 6.61912766e-03, 6.60248623e-03,
       6.52967999e-03, 6.43815214e-03, 6.36118554e-03, 6.29670000e-03,
       6.16980912e-03, 6.09284252e-03, 5.85778236e-03, 5.77665541e-03,
       5.73505184e-03, 5.72881130e-03, 5.67264649e-03, 5.66640595e-03,
       5.62064203e-03, 5.54575560e-03, 5.47502954e-03, 5.45214758e-03,
       5.40430347e-03, 5.38766205e-03, 5.33565759e-03, 5.28157295e-03,
       5.25037027e-03, 5.21916760e-03, 5.21292706e-03, 5.21292706e-03,
       5.19836581e-03, 5.18796492e-03, 5.15884242e-03, 5.00698940e-03,
       4.96538583e-03, 4.95706512e-03, 4.95498494e-03, 4.94874440e-03,
       4.93418316e-03, 4.93002280e-03, 4.89673994e-03, 4.84057513e-03,
       4.77400942e-03, 4.71368425e-03, 4.70120318e-03, 4.60135461e-03,
       4.55767087e-03, 4.42869981e-03, 4.38085570e-03, 4.33093142e-03,
       4.19780000e-03, 4.14579554e-03, 4.07922983e-03, 4.00018306e-03,
       3.94817860e-03, 3.89201378e-03, 3.85873092e-03, 3.84833003e-03,
       3.72143915e-03, 3.67567523e-03, 3.67151487e-03, 3.64239237e-03,
       3.62783112e-03, 3.60494916e-03, 3.45101596e-03, 3.43021418e-03,
       3.42813400e-03, 3.41565293e-03, 3.40941239e-03, 3.40109168e-03,
       3.39693132e-03, 3.39069079e-03, 3.34284668e-03, 3.26796026e-03,
       3.23883776e-03, 3.21595580e-03, 3.09322527e-03, 3.09322527e-03,
       3.06410278e-03, 3.04330099e-03, 2.93513172e-03, 2.91849029e-03,
       2.90808940e-03, 2.87688672e-03, 2.81448137e-03, 2.81240119e-03,
       2.79575976e-03, 2.77911834e-03, 2.77079762e-03, 2.69383102e-03,
       2.64806710e-03, 2.61686442e-03, 2.60854371e-03, 2.57942121e-03,
       2.54197800e-03, 2.53989782e-03, 2.41092676e-03, 2.37348355e-03,
       2.35892230e-03, 2.34852141e-03, 2.14258375e-03, 2.05105590e-03,
       1.98241001e-03, 1.95952805e-03, 1.93664609e-03, 1.90960377e-03,
       1.85759931e-03, 1.78687324e-03, 1.77231199e-03, 1.70990664e-03,
       1.69118504e-03, 1.63502022e-03, 1.57261487e-03, 1.54141219e-03,
       1.53517166e-03, 1.52893112e-03, 1.47484648e-03, 1.47276630e-03,
       1.44780416e-03, 1.43532309e-03, 1.41660149e-03, 1.38331863e-03,
       1.33339435e-03, 1.31883310e-03, 1.28555025e-03, 1.28347007e-03,
       1.28138989e-03, 1.22314490e-03, 1.20026293e-03, 1.16281972e-03,
       1.12537651e-03, 1.10665491e-03, 1.07337205e-03, 9.71443311e-04,
       9.44400992e-04, 9.36080278e-04, 9.27759565e-04, 8.96556889e-04,
       8.79915462e-04, 8.52873142e-04, 8.44552429e-04, 8.34151537e-04,
       7.80066899e-04, 7.61345293e-04, 7.48864223e-04, 7.13501190e-04,
       7.09340833e-04, 6.49015660e-04, 6.36534589e-04, 6.32374232e-04,
       6.03251735e-04, 5.78289594e-04, 5.76209416e-04, 5.59567989e-04,
       5.42926561e-04, 5.30445491e-04, 5.26285134e-04, 5.07563529e-04,
       5.03403172e-04, 4.86761745e-04, 4.65959961e-04, 4.34757285e-04,
       3.51550149e-04, 2.74583548e-04, 2.72503370e-04, 2.37140337e-04,
       2.18418732e-04, 1.89296234e-04, 1.14409812e-04, 1.08169277e-04,
       5.20044599e-05, 4.99242815e-05, 3.95233895e-05, 0.00000000e+00])

In [81]:
profits_z_score = (profits - np.nanmean(profits))/np.nanstd(profits)
profits_z_score

array([ 3.01569067e+00,  5.66812998e+00,  1.11639761e+01,  1.54007900e+00,
        1.20664158e-01,  1.33080304e+00,  8.98519766e-01,  1.94362815e+00,
        2.84608305e+00,  7.15180801e-01, -9.04172215e-02,  1.49398281e-01,
        1.79207472e+00,  2.88447998e+00, -9.06460773e-02,  1.44058312e-01,
        6.07618551e-01,  4.87017072e-02, -5.79889029e-01,  2.67749258e+00,
        5.83570332e+00,  4.12175655e-01,  1.56983026e+00,  7.91211800e-01,
        5.12497876e+00,  4.09970455e+00,  4.49943943e+00,  3.81795757e+00,
        1.74521568e-01,  3.33837742e+00,  1.75749206e+00,  2.56535321e+00,
       -3.64433960e-01, -5.80976897e-02,  3.75235222e+00,  2.21850945e+00,
        1.28546971e-01,  2.42466327e-01,  1.53372189e+00,  3.32991531e-01,
       -8.78673056e-01, -2.50082320e-01,  1.23969854e-01,  1.15585546e+00,
       -1.28280151e-01,  4.18939617e-01,  2.16968687e+00,  6.57203985e-01,
       -5.81211307e-01,  8.31897285e-01, -1.54980000e-01,  1.93447392e+00,
       -2.97379196e-01,  1.38115133e+00, -6.69397095e-01,  8.94705502e-01,
       -2.12041392e-01,  9.28764409e-03,  3.50282861e-01,  2.27724912e+00,
        1.81183816e-01,  6.44489772e-01,  2.81371822e-01,  1.20620374e+00,
       -1.76823019e-01, -3.10601978e-01,  2.26954986e-01, -3.68502508e-01,
        5.43284629e-01,  2.12390052e-02,  6.58475407e-01, -1.41248649e-01,
        7.69343352e-01, -4.70546789e-01, -1.97699759e-01,  1.06685596e+00,
       -1.29678714e-01,  1.42768535e+00, -2.00496886e-01, -7.40413139e-02,
        1.80987462e+00, -3.93513839e-03,  1.21935579e-01,  2.37818480e-02,
        6.15939202e-02,  9.21659635e-01,  1.30886386e-01,  5.02599144e-01,
       -1.65151371e-01,  2.97900300e-01, -4.11425695e-01,  2.97958230e+00,
       -3.45642352e-01,  8.30625863e-01,  5.44810334e-01,  4.42079486e-01,
       -2.45505203e-01,  2.14451273e+00,  3.12903073e-01,  5.00310586e-01,
        2.47043444e-01, -1.11258290e-03, -4.21342781e-01,  1.31808883e+00,
       -6.60059307e-02,  4.70050757e-01, -4.03898880e-01, -3.24714756e-01,
       -3.16521247e-02, -2.96107774e-01,  1.06024457e+00,  7.38193528e-01,
        1.85506649e-01,  1.05915670e-01, -1.37274741e+00,  1.08712797e-01,
       -2.66865082e-01, -3.20569922e-01,  9.97182066e-01, -1.91342652e-01,
        9.37100245e-02,  1.85532077e-01,  1.51007346e+00, -4.00160901e-01,
        1.04371609e+00,  2.22632154e-01, -1.01827512e+00, -1.35374682e-01,
       -3.44040361e-01, -8.91132986e-01,  2.62987069e-01,  2.42618898e-01,
       -2.23636755e-01, -5.02332324e-01, -9.75117528e-02, -2.25620172e-01,
       -2.27705303e-01,  1.17104178e-01, -3.77549474e-02, -8.34173307e-01,
       -4.29607020e-01, -3.66315664e-01,  6.22875608e-01,  1.95856019e-01,
        1.68978171e-01, -3.40683808e-01,  6.79835286e-01,  3.16724410e+00,
       -3.81954147e-01, -3.12127684e-01, -2.05557143e-01, -3.88896107e-01,
       -2.25671029e-01,  6.06022115e-02,  9.72700044e-02, -4.40286960e-01,
       -9.92917428e-02, -4.08247141e-01, -9.90374585e-02, -2.94327784e-01,
       -4.29073023e-01, -5.74803343e-01, -2.55168005e-01, -3.20849635e-01,
       -2.18876084e-02,  5.38961796e-01, -2.98167477e-01, -7.40342409e-01,
       -2.51023172e-01,  2.86966076e-01, -4.36142126e-01, -4.10077988e-01,
       -1.91895004e+00, -2.94988923e-01, -1.50980664e+00, -3.24587613e-01,
        4.48436593e-01, -2.81613570e-01, -1.61438820e-01, -2.78765586e-01,
       -2.29765006e-01,  1.67198181e-01, -2.30502430e-01, -1.32094415e-01,
        1.18884168e-01, -8.48229673e-02,  1.06990737e+00, -3.63493108e-01,
       -4.39600393e-01, -5.54282602e-01, -4.35964127e-01, -3.80326727e-01,
       -1.32857268e-01, -7.40850977e-01, -3.91947519e-01, -2.02422373e+00,
       -6.25660199e-01, -3.93778366e-01, -3.45591495e-01, -2.08888267e-01,
       -1.52945726e-01,  6.39587639e-02, -3.18993359e-01, -1.13785947e-01,
       -5.86062582e-02,  4.60642238e-01, -1.50402883e-01, -3.19298500e-01,
       -3.91235523e-01, -3.93513839e-03, -1.40841794e-01, -3.22960194e-01,
       -2.87207825e-01, -3.08059135e-01, -2.73476473e-01, -2.77036453e-01,
       -3.91972947e-01, -3.86404122e-01, -1.69296205e-01, -1.59023120e-01,
       -4.53255458e-01, -4.91118387e-01,  1.09075868e+00, -8.78489503e-02,
       -2.05328287e-01, -5.23692203e-01, -1.18744490e-01, -6.92791249e-01,
       -6.50325774e-01, -1.80382999e-01, -1.29315643e+00, -2.28137587e-01,
       -2.39529522e-01, -1.36925816e-01, -1.20143054e-01, -1.65481940e-01,
       -5.04086886e-01,  8.63357804e-02, -1.19380201e-01, -7.39904571e-02,
       -3.65018814e-01, -3.46710346e-01, -3.24638470e-01, -4.62663977e-01,
        1.63383917e-01, -2.75154750e-01, -4.39727535e-01,  4.88054083e-01,
       -2.88549977e-02, -2.08049129e-01, -2.48353187e-01, -3.47035361e-02,
       -1.70084486e-01,  5.48553868e-02,  3.53079988e-01, -1.67846784e-01,
       -1.76664894e-02, -2.16669366e-01, -3.99982902e-01, -2.21653338e-01,
       -4.16104525e-01, -4.20452786e-01, -6.01910047e-01, -9.72574686e-02,
       -1.58864995e-02, -5.62343414e-01,  5.78630143e-01,  8.93871918e-02,
       -1.39468659e-01, -1.37942953e-01,  9.14214660e-02, -2.32790989e-01,
       -2.72967905e-01, -5.19750797e-01, -7.20833250e-02, -2.74900465e-01,
        1.54992536e-01, -5.99468918e-01, -5.65394825e-01, -1.05140281e-01,
        8.09011700e-01, -2.99438898e-01, -3.09305128e-01, -2.93635662e-02,
       -1.14974010e+00, -1.82188418e-01, -4.29810448e-01, -4.25843613e-01,
       -3.70613068e-01, -2.67348222e-01, -3.97185775e-01, -3.36640688e-01,
       -2.88224962e-01, -2.93030935e-01, -2.27171306e-01, -5.78363323e-01,
       -1.73441038e-01,  4.86070666e-01, -2.97735194e-01, -5.55223454e-01,
       -3.09076272e-01, -2.43979497e-01,  2.40361322e-02, -3.35521837e-01,
       -4.23377056e-01, -3.86632977e-01, -3.71121636e-01, -2.27959588e-01,
       -2.36350969e-01,  1.39411982e+00, -2.16923650e-01, -3.64001677e-01,
       -5.48357778e-01, -4.06034868e-01, -3.70714782e-01, -3.04041444e-01,
       -3.81852433e-01, -4.03390311e-01, -4.12061405e-01, -3.76131037e-01,
       -3.63696535e-01, -3.61204550e-01, -1.89638947e-01, -3.52813168e-01,
       -4.21520780e-01, -4.07840286e-01, -3.65273098e-01, -6.12945985e-01,
       -5.23946488e-01, -4.52772318e-01, -4.48169773e-01, -4.07992857e-01,
       -3.27384741e-01, -5.04214028e-01, -3.13907674e-01, -2.81359286e-01,
       -4.78175318e-01, -4.70902787e-01, -3.10347694e-01, -3.80428441e-01,
       -1.92359789e-01, -3.62831969e-01, -1.57261485e+00, -1.23441676e+00,
       -2.98777759e-01, -2.78384160e-01, -3.56347720e-01, -2.84664982e-01,
       -4.21749636e-01, -4.39066396e-01, -4.23021058e-01, -3.75724182e-01,
       -3.00252608e-01, -3.00456035e-01, -4.03059742e-01, -7.32383311e-01,
        2.68332593e-02, -2.13897667e-01, -4.22868487e-01, -4.07255432e-01,
       -3.09737412e-01, -3.43658934e-01, -3.71121636e-01, -4.03670024e-01,
        3.01389549e-02, -2.89496383e-01, -5.61326277e-01, -2.14736805e-01,
       -2.70425062e-01, -4.12798830e-01, -3.52813168e-01, -3.28656162e-01,
       -4.27674460e-01, -4.22512489e-01, -1.06684342e+00, -6.22405360e-01,
       -3.77783884e-01, -3.22349912e-01, -3.89684389e-01, -3.07804851e-01,
       -3.91464379e-01, -2.64856236e-01, -6.25126202e-01, -4.56535726e-01,
       -3.58153138e-01, -3.61535119e-01, -2.98721348e-02, -5.79609316e-01,
       -5.58091312e-02, -4.24267051e-01, -3.72596485e-01, -3.24104473e-01,
       -3.34072417e-01, -3.86760120e-01, -4.51144899e-01, -3.42362085e-01,
       -3.29825870e-01, -2.73908757e-01, -3.25859035e-01, -4.30115589e-01,
       -4.00364328e-01, -5.01137188e-01, -2.60507975e-01, -2.63813671e-01,
       -1.44370791e-02, -2.07871130e-01, -3.43633506e-01, -1.85265257e-01,
       -3.84852987e-01, -4.10993411e-01, -2.88479246e-01, -1.49894314e-01,
       -3.93498653e-01, -4.05755155e-01, -3.30258153e-01, -2.38130959e-01,
       -4.10484843e-01, -5.04061457e-01, -3.13399105e-01, -4.29835876e-01,
       -4.16816521e-01, -4.18234959e-02, -3.96041496e-01, -2.44259210e-01,
       -3.98482625e-01, -5.28854174e-01, -5.11639129e-01, -3.37327256e-01,
       -3.43964075e-01, -3.71960775e-01, -2.87462109e-01, -3.16348803e-01,
       -3.11110547e-01, -2.66865082e-01, -2.77494165e-01, -1.57777127e-01,
       -9.19174987e-02, -2.46522340e-01, -3.34784413e-01, -2.21093912e-01,
       -4.55493160e-01, -2.67958505e-01, -1.56302278e-01, -4.80870731e-01,
       -4.98289204e-01, -3.45362639e-01, -2.90767804e-01, -3.99347191e-01,
       -2.10312259e-01, -3.39183531e-01, -1.87782672e-01, -3.09584841e-01,
       -2.88733530e-01, -4.69783936e-01, -1.19100488e-01, -3.30207296e-01,
       -3.60772266e-01, -3.53576021e-01,  8.20129477e-02, -3.37632397e-01,
       -2.98142049e-01, -3.48134338e-01, -3.98609767e-01, -3.66290235e-01,
        1.79149542e-01, -4.05907726e-01, -4.54501451e-01, -3.95278643e-01,
       -3.18891646e-01, -4.54018311e-01, -2.17025364e-01, -2.59745122e-01,
       -4.31971864e-01, -3.72647342e-01, -3.48998904e-01, -3.03304019e-01,
        1.40936170e-02, -3.89124963e-01, -2.52370878e-01, -4.92593236e-01,
       -3.78724736e-01, -4.51729753e-01, -3.92176375e-01, -2.24653892e-01,
       -5.51027763e-01, -3.74173048e-01, -4.37260977e-01, -8.10779154e-01,
       -3.67688799e-01, -4.22792202e-01, -2.80596433e-01, -2.68390788e-01,
       -3.66188521e-01, -4.49695478e-01, -4.14655105e-01, -3.57339429e-01,
       -3.56347720e-01, -5.08002863e-01,  0.00000000e+00, -4.38964682e-01])

In [82]:
New_array = np.array(clean_data[:,0:3])

In [83]:
np.nanmean(New_array, axis=0)

array([24111.748    ,  1783.4753507, 80389.34     ])

In [84]:
np.nanmean(New_array, axis=1)

array([ 232780.33333333,  289510.66666667,  194337.33333333,
        181052.66666667,   83769.33333333,  104889.        ,
         92435.        ,  132499.        ,  193527.66666667,
        131449.        ,   60644.63333333,   73920.        ,
        166891.66666667,  127762.33333333,   52365.        ,
         51410.66666667,   64737.33333333,   51272.33333333,
        122382.66666667, 1135814.33333333,  873730.33333333,
         51812.46666667,   48506.        ,   63154.33333333,
        682076.33333333,  766423.33333333,   92415.66666667,
         98604.        ,   50805.26666667,  629791.66666667,
         89866.        ,   69753.66666667,  110837.43333333,
         41868.        ,   76546.        ,   69790.        ,
         39542.66666667,   36554.33333333,  698952.        ,
         34172.66666667,   60446.66666667,  321013.33333333,
         44857.33333333,   47752.33333333,   34464.66666667,
         34904.66666667,   61010.        ,  282369.66666667,
         27333.93333333,   50668.33333333,   33815.        ,
         52352.        ,   26796.33333333,   77218.        ,
        183260.66666667,   34588.66666667,   22679.53333333,
         32749.66666667,   44321.        ,   60546.        ,
         26581.33333333,   43995.66666667,   27131.66666667,
         45220.        ,  109690.36666667,   20493.33333333,
         31376.66666667,   79399.43333333,   46368.        ,
         33631.66666667,   31757.66666667,   18162.33333333,
         32752.33333333,   37724.66666667,   54968.66666667,
        286292.33333333,  103367.16666667,  301758.33333333,
         39170.        ,  187263.76666667,   52709.33333333,
         20340.66666667,   26319.66666667,   49007.        ,
         17921.23333333,   66041.33333333,   16122.06666667,
         19177.33333333,   49132.66666667,   22393.33333333,
         14059.83333333,   33622.66666667,   16029.73333333,
         22688.33333333,   33070.        ,   60530.66666667,
         93352.66666667,   34272.        ,   43628.        ,
        129434.33333333,   26148.66666667,   58733.36666667,
         10851.83333333,   23501.        ,   28716.3       ,
         50199.66666667,   11454.03333333,   12655.16666667,
         29706.66666667,   15416.        ,   32563.33333333,
         20110.83333333,   22357.        ,   17440.66666667,
         36839.        ,   18777.33333333,   15045.66666667,
         12851.26666667,   27206.        ,   19300.        ,
         52760.66666667,   25909.7       ,   36113.        ,
         10691.26666667,  158198.66666667,   51679.        ,
          9759.66666667,   11636.7       ,   10699.83333333,
         13865.66666667,   12821.23333333,   20921.86666667,
         18442.66666667,   15193.        ,   24973.        ,
         12439.06666667,   13586.33333333,   15318.33333333,
         14548.66666667,    8997.        ,   15459.66666667,
          9782.3       ,   26630.66666667,   22586.9       ,
         44013.66666667,    9223.9       ,   19197.        ,
         26502.66666667,    9511.46666667,   10938.66666667,
          9811.36666667,    9643.36666667,   80876.        ,
         22067.93333333,   11656.66666667,    8427.66666667,
         29219.        ,    7359.        ,   11304.66666667,
         21704.33333333,   10411.36666667,   11598.        ,
         13997.33333333,   12731.23333333,   13324.13333333,
        128902.        ,   26819.63333333,   16185.        ,
         10742.76666667,   36353.33333333,    6542.76666667,
          7904.26666667,   12374.66666667,   10312.8       ,
         16317.33333333,    7524.        ,  117566.33333333,
          7934.        ,   13243.53333333,    8295.4       ,
         11605.96666667,    9919.66666667,   10608.        ,
         10977.66666667,   35860.        ,   14878.96666667,
         28369.33333333,    7656.33333333,    6920.23333333,
         12449.23333333,    8795.33333333,    8428.6       ,
         13295.        ,   16425.33333333,    6877.36666667,
         17042.33333333,    8949.33333333,    6506.63333333,
          7118.13333333,   10036.        ,   11883.33333333,
         10278.33333333,    6551.33333333,   11524.66666667,
          9767.33333333,   11132.        ,   92049.66666667,
         15876.6       ,    7260.96666667,   11056.33333333,
         10904.2       ,    5781.8       ,   30117.66666667,
          8141.33333333,   31357.        ,    9606.33333333,
         15366.        ,   27840.63333333,    6431.23333333,
          7300.7       ,    7287.33333333,    9474.03333333,
         23223.66666667,   12144.66666667,   13015.        ,
         13221.        ,   80574.83333333,   10497.        ,
         13977.33333333,    7673.36666667,   11602.66666667,
          8200.76666667,    6481.5       ,   20525.        ,
         21499.66666667,    6580.56666667,    5701.03333333,
         28490.        ,   50956.66666667,   18943.5       ,
         12740.66666667,   17432.        ,    6269.6       ,
          6137.33333333,   77746.66666667,   21773.8       ,
          4352.73333333,   12676.26666667,   11183.        ,
          9335.76666667,    8074.93333333,   11135.66666667,
          7199.86666667,   13771.4       ,   78168.        ,
         17795.13333333,   16065.66666667,   24640.13333333,
          6178.16666667,    9074.6       ,    5165.7       ,
         18692.        ,   18722.13333333,   15115.33333333,
          9044.66666667,   74863.        ,   11170.        ,
         10905.66666667,   10745.66666667,    6825.66666667,
         85158.66666667,   14513.        ,    7724.        ,
          6570.5       ,   10455.33333333,    7176.13333333,
         35066.        ,   17644.33333333,    6327.        ,
         19779.66666667,   10224.66666667,    5478.96666667,
          6291.7       ,   15482.66666667,    8712.33333333,
         58210.        ,    4488.06666667,    4183.26666667,
          6390.66666667,    8207.03333333,    3981.16666667,
          6114.2       ,    8222.33333333,    9403.36666667,
          5594.36666667,    9381.33333333,   12909.8       ,
         13661.33333333,   10210.2       ,    8553.        ,
         11946.66666667,   51097.        ,   71971.33333333,
          5949.66666667,    6008.16666667,    8499.        ,
          4581.66666667,   16672.66666667,    8439.66666667,
         13364.        ,    6706.8       ,    8470.66666667,
         12512.        ,    7534.9       ,   10605.53333333,
         32641.93333333,    8277.93333333,    4239.7       ,
          8821.66666667,    5442.76666667,    4645.73333333,
          4434.66666667,    5611.56666667,    5049.33333333,
          3815.93333333,    8718.86666667,    8943.        ,
          9594.33333333,   37583.33333333,    5040.63333333,
          3610.66666667,    7993.66666667,    6126.33333333,
          3534.86666667,    6606.66666667,   11245.66666667,
          4555.66666667,    4465.2       ,    5453.66666667,
          4089.13333333,    9390.66666667,   15573.53333333,
          5499.66666667,   16787.33333333,    6980.16666667,
          8161.23333333,    4861.03333333,    4090.        ,
          4475.96666667,    3240.6       ,    3478.63333333,
         11557.96666667,    6149.9       ,   10540.3       ,
          4401.13333333,   12004.43333333,   77638.66666667,
         13544.76666667,    3946.5       ,    3875.96666667,
         12602.13333333,    9929.66666667,    6615.66666667,
          4475.66666667,   15911.33333333,    6086.66666667,
         17970.        ,   12844.66666667,    4561.33333333,
          4913.03333333,    4671.33333333,    4328.33333333,
          3976.2       ,    4571.63333333,    8659.66666667,
          4225.26666667,    8100.6       ,   11055.93333333,
          5031.        ,    4664.33333333,    5473.        ,
          8724.96666667,    9663.03333333,    4163.03333333,
          3964.        ,    4442.56666667,    6139.        ,
          3561.7       ,   50210.        ,    9400.33333333,
          4917.06666667,    5806.3       ,    4222.56666667,
          5984.16666667,    2410.1       ,    3297.36666667,
          4884.46666667,    9684.1       ,    3660.33333333,
          8708.33333333,    5348.66666667,    6458.23333333,
          5626.        ,    8934.        ,    8147.9       ,
          8342.        ,    3605.7       ,    8189.3       ,
          4828.66666667,    3010.4       ,   20739.66666667,
          7816.33333333,    4792.66666667,    3431.26666667,
          5223.56666667,    5692.66666667,    3491.73333333,
         13999.06666667,    9524.        ,    2859.03333333,
          3140.43333333,    4487.66666667,    3085.33333333,
          5202.63333333,    3669.8       ,    6279.9       ,
          4164.13333333,   10114.96666667,    3106.6       ,
          3601.23333333,   10476.        ,    4503.46666667,
          5020.33333333,    6438.66666667,    5526.4       ,
         44366.        ,   29794.33333333,    5569.        ,
          8319.96666667,    6357.33333333,    3303.73333333,
          4570.23333333,    6576.6       ,    3054.8       ,
          3557.3       ,    2968.1       ,    3775.33333333,
          4481.33333333,   12540.46666667,    4001.86666667,
         52109.33333333,    6105.33333333,    3642.33333333,
          3816.        ,   43495.36666667,    3990.3       ,
          5632.56666667,    4603.66666667,    5478.66666667,
         10647.56666667,    5343.        ,    5833.13333333,
          2793.96666667,    4917.        ,    6607.66666667,
          3087.73333333,    4770.03333333,    5270.66666667,
         12547.8       ,    2389.66666667,    5392.66666667,
          5886.        ,    2596.56666667,    4089.66666667,
          9492.33333333,    8808.56666667,   12792.63333333,
          5032.06666667,   47555.33333333,    2748.43333333,
          2903.36666667,    3822.33333333,   16490.06666667,
          4882.        ,    5591.16666667,    3482.        ,
          2532.3       ,    8822.66666667,    3928.83333333,
          2475.26666667,   12444.33333333,    4564.66666667,
          2457.13333333,    2640.66666667,    2320.26666667,
          2574.4       ,    5096.36666667,   17679.23333333,
          7371.49178357,    2494.4       ])

In [85]:
np.cov(New_array.T)

array([[1.46975266e+09, 9.05335963e+07, 3.41962817e+09],
       [9.05335963e+07, 1.54963865e+07, 5.45670574e+08],
       [3.41962817e+09, 5.45670574e+08, 7.31300597e+10]])

In [86]:
np.corrcoef(New_array.T)

array([[1.        , 0.59989111, 0.32984416],
       [0.59989111, 1.        , 0.51258672],
       [0.32984416, 0.51258672, 1.        ]])

In [87]:
# Q1
revenue_q1 = np.nanpercentile(New_array[:,0], 25)

In [88]:
# Q2
revenue_q2 = np.nanpercentile(New_array[:,0], 50)

In [89]:
# Q3
revenue_q3 = np.nanpercentile(New_array[:,0], 75)

In [90]:
# IQR formula = Q3 - Q1
IQR = revenue_q3 - revenue_q1
IQR

np.float64(15360.25)

In [91]:
# Lower boundary
revenue_lower_boundary = revenue_q1 - 1.5 * IQR

# Upper boundary
revenue_upper_boundary = revenue_q3 + 1.5 * IQR

# Oultier
revenue_outlier = (revenue < revenue_lower_boundary) | (revenue > revenue_upper_boundary)

data[revenue_outlier,1]

array(['Walmart', 'Berkshire Hathaway', 'Apple', 'Exxon Mobil',
       'McKesson', 'UnitedHealth Group', 'CVS Health', 'General Motors',
       'AT&T', 'Ford Motor', 'AmerisourceBergen', 'Amazon.com',
       'General Electric', 'Verizon', 'Cardinal Health', 'Costco',
       'Walgreens Boots Alliance', 'Kroger', 'Chevron', 'Fannie Mae',
       'J.P. Morgan Chase', 'Express Scripts Holding', 'Home Depot',
       'Boeing', 'Wells Fargo', 'Bank of America Corp.', 'Alphabet',
       'Microsoft', 'Anthem', 'Citigroup', 'Comcast', 'IBM',
       'State Farm Insurance Cos.', 'Phillips 66', 'Johnson & Johnson',
       'Procter & Gamble', 'Valero Energy', 'Target', 'Freddie Mac',
       'LoweÕs', 'Dell Technologies', 'MetLife', 'Aetna', 'PepsiCo',
       'Archer Daniels Midland', 'UPS', 'Intel', 'Prudential Financial',
       'Albertsons Cos.', 'United Technologies', 'Marathon Petroleum',
       'Disney', 'Humana', 'Pfizer', 'AIG', 'Lockheed Martin', 'Sysco',
       'FedEx', 'Hewlett Packard Enterprise', 'Cisco Systems', 'HP',
       'Dow Chemical'], dtype=object)

In [92]:
# Q1
profits_q1 = np.nanpercentile(New_array[:,1], 25)

# Q3
profits_q3 = np.nanpercentile(New_array[:,1], 75)

# IQR
profits_IQR = profits_q3 - profits_q1

# Lower boundary
profits_lower_boundary = profits_q1 - 1.5 * profits_IQR

# Upper boundary
profits_upper_boundary = profits_q3 + 1.5 * profits_IQR

# Outliers
profits_outlier = (profits < profits_lower_boundary) | (profits > profits_upper_boundary)

data[profits_outlier, 1]

array(['Walmart', 'Berkshire Hathaway', 'Apple', 'Exxon Mobil',
       'UnitedHealth Group', 'CVS Health', 'General Motors', 'AT&T',
       'Ford Motor', 'General Electric', 'Verizon',
       'Walgreens Boots Alliance', 'Fannie Mae', 'J.P. Morgan Chase',
       'Home Depot', 'Boeing', 'Wells Fargo', 'Bank of America Corp.',
       'Alphabet', 'Microsoft', 'Citigroup', 'Comcast', 'IBM',
       'Johnson & Johnson', 'Procter & Gamble', 'Freddie Mac', 'PepsiCo',
       'Intel', 'Prudential Financial', 'United Technologies', 'Disney',
       'Pfizer', 'Lockheed Martin', 'Cisco Systems', 'Dow Chemical',
       'Coca-Cola', 'Delta Air Lines', 'Honeywell International',
       'Morgan Stanley', 'Goldman Sachs Group', 'Oracle',
       'American Express', 'Gilead Sciences', '3M', 'Facebook',
       'Philip Morris International', 'AbbVie', 'McDonaldÕs',
       'ConocoPhillips', 'Qualcomm', 'Amgen', 'U.S. Bancorp',
       'Sears Holdings', 'Union Pacific', 'Bristol-Myers Squibb',
       'Altria Group', 'Halliburton', 'Freeport-McMoRan', 'Visa',
       'FirstEnergy', 'Reynolds American', 'Devon Energy',
       'Baxter International', 'Baker Hughes', 'eBay',
       'Chesapeake Energy', 'Anadarko Petroleum',
       'National Oilwell Varco'], dtype=object)

In [93]:
revenue_quartile = np.nanpercentile(New_array[:,0],[0,25,50,75, 100])
revenue_quartile

array([  5145.  ,   7245.  ,  11384.  ,  22605.25, 485873.  ])

In [94]:
np.array_split(data, 5)

[array([[1, 'Walmart', '23,00,000', 1.0, '$4,85,873', '0.8%', '$13,643.0',
         '-7.2%', '$1,98,825', '$2,18,619'],
        [2, 'Berkshire Hathaway', '3,67,700', 4.0, '$2,23,604', '6.1%',
         '$24,074.0', '0.0%', '$6,20,854', '$4,11,035'],
        [3, 'Apple', '1,16,000', 3.0, '$2,15,639', '-7.7%', '$45,687.0',
         '-14.4%', '$3,21,686', '$7,53,718'],
        [4, 'Exxon Mobil', '72,700', 2.0, '$2,05,004', '-16.7%',
         '$7,840.0', '-51.5%', '$3,30,314', '$3,40,056'],
        [5, 'McKesson', '68,000', 5.0, '$1,92,487', '6.2%', '$2,258.0',
         '53.0%', '$56,563', '$31,439'],
        [6, 'UnitedHealth Group', '2,30,000', 6.0, '$1,84,840', '17.7%',
         '$7,017.0', '20.7%', '$1,22,810', '$1,57,793'],
        [7, 'CVS Health', '2,04,000', 7.0, '$1,77,526', '15.8%',
         '$5,317.0', '1.5%', '$94,462', '$81,310'],
        [8, 'General Motors', '2,25,000', 8.0, '$1,66,380', '9.2%',
         '$9,427.0', '-2.7%', '$2,21,690', '$52,968'],
        [9, 'AT&T', '2,68,540', 10.0, '$1,63,786', '11.6%', '$12,976.0',
         '-2.8%', '$4,03,821', '$2,55,679'],
        [10, 'Ford Motor', '2,01,000', 9.0, '$1,51,800', '1.5%',
         '$4,596.0', '-37.7%', '$2,37,951', '$46,349'],
        [11, 'AmerisourceBergen', '18,500', 12.0, '$1,46,850', '8.0%',
         '$1,427.9', '-', '$33,656', '$19,229'],
        [12, 'Amazon.com', '3,41,400', 18.0, '$1,35,987', '27.1%',
         '$2,371.0', '297.8%', '$83,402', '$4,23,031'],
        [13, 'General Electric', '2,95,000', 11.0, '$1,26,661', '-9.8%',
         '$8,831.0', '-', '$3,65,183', '$2,59,520'],
        [14, 'Verizon', '1,60,900', 13.0, '$1,25,980', '-4.3%',
         '$13,127.0', '-26.6%', '$2,44,180', '$1,98,900'],
        [15, 'Cardinal Health', '37,300', 21.0, '$1,21,546', '18.5%',
         '$1,427.0', '17.4%', '$34,122', '$25,725'],
        [16, 'Costco', '1,72,000', 15.0, '$1,18,719', '2.2%', '$2,350.0',
         '-1.1%', '$33,163', '$73,606'],
        [17, 'Walgreens Boots Alliance', '3,00,000', 19.0, '$1,17,351',
         '13.4%', '$4,173.0', '-1.1%', '$72,688', '$89,645'],
        [18, 'Kroger', '4,43,000', 17.0, '$1,15,337', '5.0%', '$1,975.0',
         '-3.1%', '$36,505', '$26,961'],
        [19, 'Chevron', '55,200', 14.0, '$1,07,567', '-18.0%', '-$497.0',
         '-110.8%', '$2,60,078', '$2,03,263'],
        [20, 'Fannie Mae', '7,000', 16.0, '$1,07,162', '-2.9%',
         '$12,313.0', '12.4%', '$32,87,968', '$3,011'],
        [21, 'J.P. Morgan Chase', '2,43,355', 23.0, '$1,05,486', '4.4%',
         '$24,733.0', '1.2%', '$24,90,972', '$3,13,761'],
        [22, 'Express Scripts Holding', '25,600', 22.0, '$1,00,288',
         '-1.4%', '$3,404.4', '37.5%', '$51,745', '$39,567'],
        [23, 'Home Depot', '4,06,000', 28.0, '$94,595', '6.9%',
         '$7,957.0', '13.5%', '$42,966', '$1,76,368'],
        [24, 'Boeing', '1,50,540', 24.0, '$94,571', '-1.6%', '$4,895.0',
         '-5.4%', '$89,997', '$1,07,546'],
        [25, 'Wells Fargo', '2,69,100', 27.0, '$94,176', '4.6%',
         '$21,938.0', '-4.2%', '$19,30,115', '$2,78,516'],
        [26, 'Bank of America Corp.', '2,08,024', 26.0, '$93,662', '0.7%',
         '$17,906.0', '12.7%', '$21,87,702', '$2,36,182'],
        [27, 'Alphabet', '72,053', 36.0, '$90,272', '20.4%', '$19,478.0',
         '19.1%', '$1,67,497', '$5,79,426'],
        [28, 'Microsoft', '1,14,000', 25.0, '$85,320', '-8.8%',
         '$16,798.0', '37.8%', '$1,93,694', '$5,08,935'],
        [29, 'Anthem', '53,000', 33.0, '$84,863', '7.2%', '$2,469.8',
         '-3.5%', '$65,083', '$43,813'],
        [30, 'Citigroup', '2,19,000', 29.0, '$82,386', '-6.7%',
         '$14,912.0', '-13.5%', '$17,92,077', '$1,65,394'],
        [31, 'Comcast', '1,59,000', 37.0, '$80,403', '7.9%', '$8,695.0',
         '6.5%', '$1,80,500', '$1,78,258'],
        [32, 'IBM', '4,14,400', 31.0, '$79,919', '-3.1%', '$11,872.0',
         '-10.0%', '$1,17,470', '$1,64,251'],
        [33, 'State Farm Insurance Cos.', '68,234', 35.0, '$76,132',
         '0.6%', '$350.3', '-94.4%', '$2,56,030', '-'],
        [34, 'Phillips 66', '14,800', 30.0, '$72,396', '-16.9%',
         '$1,555.0', '-63.2%', '$51,653', '$40,954'],
        [35, 'Johnson & Johnson', '1,26,400', 39.0, '$71,890', '2.6%',
         '$16,540.0', '7.3%', '$1,41,208', '$3,37,642'],
        [36, 'Procter & Gamble', '1,05,000', 34.0, '$71,726', '-8.9%',
         '$10,508.0', '49.3%', '$1,27,136', '$2,29,700'],
        [37, 'Valero Energy', '9,996', 32.0, '$70,166', '-14.2%',
         '$2,289.0', '-42.6%', '$46,173', '$29,746'],
        [38, 'Target', '3,23,000', 38.0, '$69,495', '-5.8%', '$2,737.0',
         '-18.6%', '$37,431', '$30,502'],
        [39, 'Freddie Mac', '5,982', 43.0, '$65,665', '3.4%', '$7,815.0',
         '22.6%', '$20,23,376', '$1,612'],
        [40, 'LoweÕs', '2,40,000', 47.0, '$65,017', '10.1%', '$3,093.0',
         '21.5%', '$34,408', '$70,481'],
        [41, 'Dell Technologies', '1,38,000', nan, '$64,806', '18.1%',
         '-$1,672.0', '-', '$1,18,206', '-'],
        [42, 'MetLife', '58,000', 40.0, '$63,476', '-9.3%', '$800.0',
         '-84.9%', '$8,98,764', '$57,429'],
        [43, 'Aetna', '49,500', 46.0, '$63,155', '4.7%', '$2,271.0',
         '-5.0%', '$69,146', '$44,859'],
        [44, 'PepsiCo', '2,64,000', 44.0, '$62,799', '-0.4%', '$6,329.0',
         '16.1%', '$74,129', '$1,59,763'],
        [45, 'Archer Daniels Midland', '31,800', 41.0, '$62,346', '-7.9%',
         '$1,279.0', '-30.8%', '$39,769', '$26,274'],
        [46, 'UPS', '3,35,520', 48.0, '$60,906', '4.4%', '$3,431.0',
         '-29.2%', '$40,377', '$93,276'],
        [47, 'Intel', '1,06,000', 51.0, '$59,387', '7.3%', '$10,316.0',
         '-9.7%', '$1,13,327', '$1,70,539'],
        [48, 'Prudential Financial', '49,739', 50.0, '$58,779', '2.9%',
         '$4,368.0', '-22.6%', '$7,83,962', '$45,912'],
        [49, 'Albertsons Cos.', '2,74,000', nan, '$58,734', '115.9%',
         '-$502.2', '-', '$23,770', '-'],
        [50, 'United Technologies', '2,01,600', 45.0, '$57,244', '-6.2%',
         '$5,055.0', '-33.6%', '$89,706', '$89,957'],
        [51, 'Marathon Petroleum', '44,460', 42.0, '$55,858', '-13.5%',
         '$1,174.0', '-58.8%', '$44,413', '$26,679'],
        [52, 'Disney', '1,95,000', 53.0, '$55,632', '6.0%', '$9,391.0',
         '12.0%', '$92,033', '$1,79,298'],
        [53, 'Humana', '51,600', 52.0, '$54,379', '0.2%', '$614.0',
         '-51.9%', '$25,396', '$29,743'],
        [54, 'Pfizer', '96,500', 55.0, '$52,824', '8.1%', '$7,215.0',
         '3.7%', '$1,71,615', '$2,03,725'],
        [55, 'AIG', '56,400', 49.0, '$52,367', '-10.2%', '-$849.0',
         '-138.7%', '$4,98,264', '$61,154'],
        [56, 'Lockheed Martin', '97,000', 60.0, '$50,658', '9.8%',
         '$5,302.0', '47.1%', '$47,806', '$77,557'],
        [57, 'Sysco', '51,900', 57.0, '$50,367', '3.5%', '$949.6',
         '38.3%', '$16,722', '$28,048'],
        [58, 'FedEx', '3,35,767', 58.0, '$50,365', '6.1%', '$1,820.0',
         '73.3%', '$46,064', '$52,178'],
        [59, 'Hewlett Packard Enterprise', '1,95,000', nan, '$50,123',
         '-', '$3,161.0', '-', '$79,679', '$39,288'],
        [60, 'Cisco Systems', '73,700', 54.0, '$49,247', '0.2%',
         '$10,739.0', '19.6%', '$1,21,652', '$1,69,266'],
        [61, 'HP', '49,000', 20.0, '$48,238', '-53.3%', '$2,496.0',
         '-45.2%', '$29,010', '$30,231'],
        [62, 'Dow Chemical', '56,000', 56.0, '$48,158', '-1.3%',
         '$4,318.0', '-43.8%', '$79,511', '$77,460'],
        [63, 'HCA Holdings', '2,10,500', 63.0, '$44,747', '2.7%',
         '$2,890.0', '35.7%', '$33,758', '$32,966'],
        [64, 'Coca-Cola', '1,00,300', 62.0, '$41,863', '-5.5%',
         '$6,527.0', '-11.2%', '$87,270', '$1,82,153'],
        [65, 'New York Life Insurance', '11,320', 61.0, '$40,787',
         '-11.1%', '$1,088.1', '324.1%', '$2,87,196', '-'],
        [66, 'Centene', '30,500', 124.0, '$40,721', '78.6%', '$562.0',
         '58.3%', '$20,197', '$12,271'],
        [67, 'American Airlines Group', '1,22,300', 67.0, '$40,180',
         '-2.0%', '$2,676.0', '-64.8%', '$51,274', '$21,326'],
        [68, 'Nationwide', '34,320', 69.0, '$40,074', '-0.4%', '$334.3',
         '-42.4%', '$1,97,790', '-'],
        [69, 'Merck', '68,000', 72.0, '$39,807', '0.8%', '$3,920.0',
         '-11.8%', '$95,377', '$1,74,454'],
        [70, 'Cigna', '41,000', 79.0, '$39,668', '4.7%', '$1,867.0',
         '-10.8%', '$59,360', '$37,604'],
        [71, 'Delta Air Lines', '83,756', 68.0, '$39,639', '-2.6%',
         '$4,373.0', '-3.4%', '$51,261', '$33,586'],
        [72, 'Best Buy', '1,25,000', 71.0, '$39,403', '-0.9%', '$1,228.0',
         '36.9%', '$13,856', '$15,193'],
        [73, 'Honeywell International', '1,31,000', 75.0, '$39,302',
         '1.9%', '$4,809.0', '0.9%', '$54,146', '$94,991'],
        [74, 'Caterpillar', '95,400', 59.0, '$38,537', '-18.0%', '-$67.0',
         '-103.2%', '$74,704', '$54,402'],
        [75, 'Liberty Mutual Insurance Group', '50,000', 73.0, '$38,308',
         '-2.9%', '$1,006.0', '95.7%', '$1,25,592', '-'],
        [76, 'Morgan Stanley', '55,311', 78.0, '$37,949', '0.1%',
         '$5,979.0', '-2.4%', '$8,14,949', '$79,947'],
        [77, 'Massachusetts Mutual Life Insurance', '11,737', 76.0,
         '$37,788', '-1.2%', '$1,273.5', '-10.6%', '$2,71,040', '-'],
        [78, 'Goldman Sachs Group', '34,400', 74.0, '$37,712', '-3.8%',
         '$7,398.0', '21.6%', '$8,60,165', '$91,380'],
        [79, 'Energy Transfer Equity', '30,992', 65.0, '$37,504',
         '-11.0%', '$995.0', '-16.3%', '$79,011', '$21,292'],
        [80, 'TIAA', '12,997', 82.0, '$37,105', '5.5%', '$1,492.3',
         '22.9%', '$5,23,194', '-'],
        [81, 'Oracle', '1,36,000', 77.0, '$37,047', '-3.1%', '$8,901.0',
         '-10.4%', '$1,12,180', '$1,83,556'],
        [82, 'Tyson Foods', '1,14,000', 66.0, '$36,881', '-10.9%',
         '$1,768.0', '44.9%', '$22,373', '$22,028'],
        [83, 'United Continental Holdings', '88,000', 80.0, '$36,556',
         '-3.5%', '$2,263.0', '-69.2%', '$40,140', '$22,225'],
        [84, 'Allstate', '43,275', 81.0, '$36,534', '2.5%', '$1,877.0',
         '-13.5%', '$1,08,610', '$29,754'],
        [85, 'Publix Super Markets', '1,91,000', 87.0, '$34,274', '5.1%',
         '$2,025.7', '3.1%', '$17,464', '-'],
        [86, 'American Express', '56,400', 85.0, '$33,823', '-1.8%',
         '$5,408.0', '4.7%', '$1,58,893', '$71,193'],
        [87, 'TJX', '2,35,000', 89.0, '$33,184', '7.2%', '$2,298.2',
         '0.9%', '$12,884', '$51,053'],
        [88, 'Nike', '70,700', 91.0, '$32,376', '5.8%', '$3,760.0',
         '14.9%', '$21,396', '$92,204'],
        [89, 'Exelon', '34,396', 95.0, '$31,360', '6.5%', '$1,134.0',
         '-50.0%', '$1,14,904', '$33,309'],
        [90, 'General Dynamics', '98,800', 88.0, '$31,353', '-0.4%',
         '$2,955.0', '-0.3%', '$32,872', '$56,791'],
        [91, 'Rite Aid', '70,580', 107.0, '$30,737', '15.9%', '$165.5',
         '-92.2%', '$11,277', '$4,473'],
        [92, 'Gilead Sciences', '9,000', 86.0, '$30,390', '-6.9%',
         '$13,501.0', '-25.4%', '$56,977', '$88,788'],
        [93, 'CHS', '12,157', 84.0, '$30,347', '-12.2%', '$424.2',
         '-45.7%', '$17,318', '-'],
        [94, '3M', '91,584', 93.0, '$30,109', '-0.5%', '$5,050.0', '4.5%',
         '$32,906', '$1,14,338'],
        [95, 'Time Warner', '25,000', 99.0, '$29,318', '4.3%', '$3,926.0',
         '2.4%', '$65,966', '$75,660'],
        [96, 'Charter Communications', '91,500', 292.0, '$29,003',
         '197.3%', '$3,522.0', '-', '$1,49,067', '$1,00,595'],
        [97, 'Northwestern Mutual', '5,646', 100.0, '$28,799', '2.4%',
         '$818.0', '0.4%', '$2,50,441', '-'],
        [98, 'Facebook', '17,048', 157.0, '$27,638', '54.2%', '$10,217.0',
         '177.0%', '$64,961', '$4,10,522'],
        [99, 'Travelers Cos.', '30,900', 105.0, '$27,625', '3.1%',
         '$3,014.0', '-12.4%', '$1,00,245', '$33,689'],
        [100, 'Capital One Financial', '47,300', 112.0, '$27,519', '9.6%',
         '$3,751.0', '-7.4%', '$3,57,033', '$41,831']], dtype=object),
 array([[101, 'Twenty-First Century Fox', '21,500', 96.0, '$27,326',
         '-5.7%', '$2,755.0', '-66.8%', '$48,365', '$59,949'],
        [102, 'USAA', '29,943', 114.0, '$27,131', '11.4%', '$1,779.1',
         '-21.7%', '$1,47,290', '-'],
        [103, 'World Fuel Services', '5,000', 92.0, '$27,016', '-11.1%',
         '$126.5', '-27.5%', '$5,413', '$2,535'],
        [104, 'Philip Morris International', '79,500', 106.0, '$26,685',
         '-0.4%', '$6,967.0', '1.4%', '$36,851', '$1,75,349'],
        [105, 'Deere', '56,767', 97.0, '$26,644', '-7.7%', '$1,523.9',
         '-21.4%', '$57,981', '$34,648'],
        [106, 'Kraft Heinz', '41,000', 153.0, '$26,487', '44.4%',
         '$3,632.0', '472.9%', '$1,20,480', '$1,10,528'],
        [107, 'Tech Data', '9,500', 108.0, '$26,235', '-0.5%', '$195.1',
         '-26.6%', '$7,932', '$3,569'],
        [108, 'Avnet', '17,700', 102.0, '$26,219', '-6.1%', '$506.5',
         '-11.4%', '$11,240', '$5,898'],
        [109, 'Avnet', '90,000', 102.0, '$25,923', '-12.5%', '$1,659.0',
         '-77.2%', '$61,538', '$65,676'],
        [110, 'MacyÕs', '1,48,300', 103.0, '$25,778', '-4.8%', '$619.0',
         '-42.3%', '$19,851', '$9,046'],
        [111, 'AbbVie', '30,000', 123.0, '$25,638', '12.2%', '$5,953.0',
         '15.7%', '$66,099', '$1,03,838'],
        [112, 'McDonaldÕs', '3,75,000', 109.0, '$24,622', '-3.1%',
         '$4,686.5', '3.5%', '$31,024', '$1,06,150'],
        [113, 'DuPont', '46,000', 101.0, '$24,594', '-12.0%', '$2,513.0',
         '28.7%', '$39,964', '$69,451'],
        [114, 'Northrop Grumman', '67,000', 118.0, '$24,508', '4.2%',
         '$2,200.0', '10.6%', '$25,614', '$41,577'],
        [115, 'ConocoPhillips', '13,300', 90.0, '$24,360', '-21.3%',
         '-$3,615.0', '-', '$89,772', '$61,692'],
        [116, 'Raytheon', '63,000', 120.0, '$24,069', '3.5%', '$2,211.0',
         '6.6%', '$30,052', '$44,664'],
        [117, 'Tesoro', '6,308', 98.0, '$24,005', '-14.7%', '$734.0',
         '-52.3%', '$20,398', '$9,515'],
        [118, 'Arrow Electronics', '18,700', 119.0, '$23,825', '2.3%',
         '$522.8', '5.0%', '$14,206', '$6,546'],
        [119, 'Qualcomm', '30,500', 110.0, '$23,554', '-6.8%', '$5,705.0',
         '8.2%', '$52,359', '$84,694'],
        [120, 'Progressive', '31,721', 137.0, '$23,441', '12.4%',
         '$1,031.0', '-18.7%', '$33,428', '$22,760'],
        [121, 'Duke Energy', '28,798', 115.0, '$23,369', '-1.0%',
         '$2,152.0', '-23.6%', '$1,32,761', '$57,397'],
        [122, 'Enterprise Products Partners', '6,800', 104.0, '$23,022',
         '-14.8%', '$2,513.1', '-0.3%', '$52,194', '$58,522'],
        [123, 'Amgen', '19,200', 130.0, '$22,991', '6.1%', '$7,722.0',
         '11.3%', '$77,626', '$1,20,830'],
        [124, 'US Foods Holding', '25,000', 122.0, '$22,919', '-0.9%',
         '$209.8', '25.2%', '$8,945', '$6,207'],
        [125, 'U.S. Bancorp', '71,191', 131.0, '$22,744', '5.8%',
         '$5,888.0', '0.2%', '$4,45,964', '$87,201'],
        [126, 'Aflac', '10,212', 135.0, '$22,559', '8.1%', '$2,659.0',
         '5.0%', '$1,29,819', '$29,053'],
        [127, 'Sears Holdings', '1,40,000', 111.0, '$22,138', '-12.0%',
         '-$2,221.0', '-', '$9,362', '$1,231'],
        [128, 'Dollar General', '1,21,000', 139.0, '$21,987', '7.9%',
         '$1,251.1', '7.4%', '$11,672', '$19,182'],
        [129, 'AutoNation', '26,000', 136.0, '$21,609', '3.6%', '$430.5',
         '-2.7%', '$10,060', '$4,268'],
        [130, 'Community Health Systems', '1,08,000', 125.0, '$21,374',
         '-5.8%', '-$1,721.0', '-', '$21,944', '$1,010'],
        [131, 'Starbucks', '2,54,000', 146.0, '$21,316', '11.2%',
         '$2,817.7', '2.2%', '$14,330', '$85,092'],
        [132, 'Eli Lilly', '41,975', 141.0, '$21,222', '6.3%', '$2,737.6',
         '13.7%', '$38,806', '$92,803'],
        [133, 'International Paper', '55,000', 127.0, '$21,079', '-5.8%',
         '$904.0', '-3.6%', '$33,345', '$20,884'],
        [134, 'Tenet Healthcare', '1,16,475', 140.0, '$21,070', '4.8%',
         '-$192.0', '-', '$24,701', '$1,777'],
        [135, 'Abbott Laboratories', '75,000', 138.0, '$20,853', '0.9%',
         '$1,400.0', '-68.3%', '$52,666', '$76,740'],
        [136, 'Dollar Tree', '1,16,050', 180.0, '$20,719', '33.7%',
         '$896.2', '217.4%', '$15,702', '$18,540'],
        [137, 'Whirlpool', '93,000', 134.0, '$20,718', '-0.8%', '$888.0',
         '13.4%', '$19,153', '$12,762'],
        [138, 'Southwest Airlines', '53,536', 142.0, '$20,425', '3.1%',
         '$2,244.0', '2.9%', '$23,286', '$33,076'],
        [139, 'Emerson Electric', '1,03,500', 128.0, '$20,268', '-9.1%',
         '$1,635.0', '-39.7%', '$21,743', '$38,614'],
        [140, 'Staples', '61,503', 132.0, '$20,217', '-4.0%', '-$1,497.0',
         '-494.8%', '$8,271', '$5,723'],
        [141, 'Plains GP Holdings', '5,100', 121.0, '$20,182', '-12.8%',
         '$94.0', '-20.3%', '$26,103', '$9,127'],
        [142, 'Penske Automotive Group', '24,000', 143.0, '$20,143',
         '4.0%', '$342.9', '5.2%', '$8,861', '$4,001'],
        [143, 'Union Pacific', '42,919', 129.0, '$19,941', '-8.6%',
         '$4,233.0', '-11.3%', '$55,718', '$85,911'],
        [144, 'Danaher', '62,000', 133.0, '$19,912', '-4.8%', '$2,553.7',
         '-23.9%', '$45,295', '$59,359'],
        [145, 'Southern', '32,015', 162.0, '$19,896', '13.8%', '$2,448.0',
         '3.4%', '$1,09,697', '$49,335'],
        [146, 'ManpowerGroup', '28,000', 144.0, '$19,654', '1.7%',
         '$443.7', '5.8%', '$7,574', '$6,938'],
        [147, 'Bristol-Myers Squibb', '25,000', 168.0, '$19,427', '17.3%',
         '$4,457.0', '184.8%', '$33,707', '$89,591'],
        [148, 'Altria Group', '8,300', 149.0, '$19,337', '2.6%',
         '$14,239.0', '171.7%', '$45,932', '$1,38,513'],
        [149, 'Fluor', '61,551', 155.0, '$19,037', '5.1%', '$281.4',
         '-31.8%', '$9,216', '$7,353'],
        [150, 'KohlÕs', '85,000', 145.0, '$18,686', '-2.7%', '$556.0',
         '-17.4%', '$13,574', '$6,862'],
        [151, 'Lear', '1,48,400', 154.0, '$18,558', '1.9%', '$975.1',
         '30.8%', '$9,901', '$9,726'],
        [152, 'Jabil Circuit', '1,38,000', 158.0, '$18,353', '2.5%',
         '$254.1', '-10.5%', '$10,323', '$5,270'],
        [153, 'Hartford Financial Services Group', '16,900', 152.0,
         '$18,300', '-0.4%', '$896.0', '-46.7%', '$2,23,432', '$17,795'],
        [154, 'Thermo Fisher Scientific', '54,800', 164.0, '$18,274',
         '7.7%', '$2,021.8', '2.3%', '$45,908', '$59,964'],
        [155, 'Kimberly-Clark', '42,000', 151.0, '$18,202', '-2.1%',
         '$2,166.0', '113.8%', '$14,602', '$46,828'],
        [156, 'Molina Healthcare', '21,000', 201.0, '$17,782', '25.4%',
         '$52.0', '-63.6%', '$7,449', '$2,601'],
        [157, 'PG&E Corp.', '24,000', 166.0, '$17,666', '4.9%',
         '$1,393.0', '59.4%', '$68,598', '$33,696'],
        [158, 'Supervalu', '38,000', 160.0, '$17,529', '-1.6%', '$178.0',
         '-7.3%', '$4,370', '$1,033'],
        [159, 'Cummins', '55,400', 148.0, '$17,509', '-8.4%', '$1,394.0',
         '-0.4%', '$15,011', '$25,397'],
        [160, 'CenturyLink', '40,000', 159.0, '$17,470', '-2.4%',
         '$626.0', '-28.7%', '$47,017', '$12,883'],
        [161, 'AECOM', '87,000', 156.0, '$17,411', '-3.2%', '$96.1', '-',
         '$13,727', '$5,528'],
        [162, 'Xerox', '1,33,600', 150.0, '$17,126', '-8.2%', '-$477.0',
         '-200.6%', '$18,145', '$7,462'],
        [163, 'Marriott International', '2,26,500', 195.0, '$17,072',
         '17.9%', '$780.0', '-9.2%', '$24,140', '$36,124'],
        [164, 'Paccar', '23,000', 147.0, '$17,033', '-10.9%', '$521.7',
         '-67.5%', '$20,639', '$23,604'],
        [165, 'General Mills', '39,000', 161.0, '$16,563', '-6.1%',
         '$1,697.4', '39.0%', '$21,712', '$33,998'],
        [166, 'PNC Financial Services Group', '50,683', 171.0, '$16,423',
         '0.9%', '$3,903.0', '-4.9%', '$3,66,380', '$58,455'],
        [167, 'American Electric Power', '17,634', 165.0, '$16,380',

In [95]:
rng = np.random.default_rng(seed=42)
rng.choice(data, size=25, axis=0, replace = False)

array([[337, 'Navistar International', '11,300', 281.0, '$8,111',
        '-20.0%', '-$97.0', '-', '$5,653', '$2,416'],
       [185, 'Synchrony Financial', '15,000', nan, '$15,122', '11.0%',
        '$2,251.0', '1.7%', '$90,207', '$27,810'],
       [98, 'Facebook', '17,048', 157.0, '$27,638', '54.2%', '$10,217.0',
        '177.0%', '$64,961', '$4,10,522'],
       [391, 'Jones Lang LaSalle', '77,300', 436.0, '$6,804', '14.0%',
        '$318.2', '-27.5%', '$7,629', '$5,043'],
       [91, 'Rite Aid', '70,580', 107.0, '$30,737', '15.9%', '$165.5',
        '-92.2%', '$11,277', '$4,473'],
       [386, 'Harman International Industries', '26,000', 419.0,
        '$6,912', '12.3%', '$361.7', '5.6%', '$6,054', '-'],
       [313, 'Frontier Communications', '28,332', 461.0, '$8,896',
        '59.5%', '-$373.0', '-', '$29,013', '$2,521'],
       [413, 'Berry Global Group', '21,000', 518.0, '$6,489', '32.9%',
        '$236.0', '174.4%', '$7,653', '$6,256'],
       [373, 'WESCO International', '9,000', 357.0, '$7,336', '-2.4%',
        '$101.6', '-51.8%', '$4,491', '$3,389'],
       [64, 'Coca-Cola', '1,00,300', 62.0, '$41,863', '-5.5%',
        '$6,527.0', '-11.2%', '$87,270', '$1,82,153'],
       [42, 'MetLife', '58,000', 40.0, '$63,476', '-9.3%', '$800.0',
        '-84.9%', '$8,98,764', '$57,429'],
       [211, 'Ecolab', '47,565', 206.0, '$13,153', '-2.9%', '$1,229.6',
        '22.7%', '$18,330', '$36,356'],
       [256, 'Xcel Energy', '11,476', 257.0, '$11,107', '0.7%',
        '$1,123.4', '14.1%', '$41,155', '$22,546'],
       [360, 'EMCOR Group', '31,000', 381.0, '$7,552', '12.3%', '$181.9',
        '5.6%', '$3,894', '$3,756'],
       [43, 'Aetna', '49,500', 46.0, '$63,155', '4.7%', '$2,271.0',
        '-5.0%', '$69,146', '$44,859'],
       [352, 'Zimmer Biomet Holdings', '18,500', 431.0, '$7,684',
        '28.1%', '$305.9', '108.1%', '$26,684', '$24,571'],
       [223, 'Reynolds American', '5,525', 266.0, '$12,503', '17.1%',
        '$6,073.0', '86.7%', '$51,095', '$89,862'],
       [370, 'AGCO', '19,795', 360.0, '$7,411', '-0.8%', '$160.1',
        '-39.9%', '$7,168', '$4,783'],
       [208, 'Newell Brands', '53,400', 434.0, '$13,264', '122.1%',
        '$527.8', '50.8%', '$33,838', '$22,787'],
       [249, 'Las Vegas Sands', '49,000', 241.0, '$11,410', '-2.4%',
        '$1,670.0', '-15.1%', '$20,469', '$45,313'],
       [463, 'Burlington Stores', '40,000', 500.0, '$5,591', '9.0%',
        '$215.9', '43.5%', '$2,575', '$6,836'],
       [476, 'Cincinnati Financial', '4,754', 499.0, '$5,449', '6.0%',
        '$590.7', '-6.8%', '$20,386', '$11,911'],
       [415, 'CalAtlantic Group', '3,055', 640.0, '$6,477', '83.0%',
        '$484.7', '127.0%', '$8,709', '$4,291'],
       [46, 'UPS', '3,35,520', 48.0, '$60,906', '4.4%', '$3,431.0',
        '-29.2%', '$40,377', '$93,276'],
       [253, 'Estee Lauder', '46,000', 261.0, '$11,262', '4.5%',
        '$1,114.6', '2.4%', '$9,223', '$31,068']], dtype=object)

In [96]:
# It shuffles the data permanently.
np.random.shuffle(data)

# Level 7 — Interview Challenge

81. Find the top 10 companies by revenue without using Pandas sorting.
82. Find the top 10 companies by profit.
83. Find the richest company by market value.
84. Find the company having the largest assets.
85. Find average employee count.
86. Find the company closest to the average revenue.
87. Find the company farthest from average revenue.
88. Compute revenue-to-assets ratio.
89. Compute profit margin:
    * Profit Margin = Profit / Revenue

90. Find top 20 companies by profit margin.
91. Find companies with the highest revenue per employee.
92. Find companies with the highest assets per employee.
93. Create a ranking based on profits only.
94. Create a ranking based on market value only.
95. Compare current rank vs profit rank.
96. Find companies whose profit rank is better than their Fortune rank.
97. Find companies whose revenue rank differs by more than 100 positions from their Fortune rank.
98. Find the top 5 companies that dominate in:
 - Revenue
 - Profit
 - Assets
 - Market Value
99. Build a NumPy-only summary table containing:
 - Mean
 - Median
 - Max
 - Min
 - Std

for Revenue, Profit, Assets, and Market Value.

100. Without using any Pandas analytical functions (only Pandas for loading), reproduce a mini statistical report similar to describe() using only NumPy.

In [97]:
df = pd.read_csv('/Users/krishnag02/Learning Phase/Jupyterfiles/Fortune_500.csv', encoding='latin-1')
df.head()

,Rank,Company Name,Number of Employees,Previous Rank,Revenues,Revenue Change,Profits,Profit Change,Assets,Market Value
0,1,Walmart,"23,00,000",1.0,"$4,85,873",0.8%,"$13,643.0",-7.2%,"$1,98,825","$2,18,619"
1,2,Berkshire Hathaway,"3,67,700",4.0,"$2,23,604",6.1%,"$24,074.0",0.0%,"$6,20,854","$4,11,035"
2,3,Apple,"1,16,000",3.0,"$2,15,639",-7.7%,"$45,687.0",-14.4%,"$3,21,686","$7,53,718"
3,4,Exxon Mobil,"72,700",2.0,"$2,05,004",-16.7%,"$7,840.0",-51.5%,"$3,30,314","$3,40,056"
4,5,McKesson,"68,000",5.0,"$1,92,487",6.2%,"$2,258.0",53.0%,"$56,563","$31,439"

In [98]:
data = df.to_numpy()

In [99]:
# Ques 81
data[np.argsort(clean_data[:,0]),1][-10:]

array(['Ford Motor', 'AT&T', 'General Motors', 'CVS Health',
       'UnitedHealth Group', 'McKesson', 'Exxon Mobil', 'Apple',
       'Berkshire Hathaway', 'Walmart'], dtype=object)

In [100]:
# Ques 82
data[np.argsort(clean_data[:,1]),1][-10:]

array(['Altria Group', 'Citigroup', 'Johnson & Johnson', 'Microsoft',
       'Bank of America Corp.', 'Alphabet', 'Wells Fargo',
       'Berkshire Hathaway', 'J.P. Morgan Chase', 'Apple'], dtype=object)

In [101]:
# Ques 83
data[np.argmax(clean_data[:,3]),1]

'Apple'

In [102]:
# Ques 84
data[np.argmax(clean_data[:,2]),1]

'Fannie Mae'

In [103]:
# Ques 85
np.nanmean(No_of_employees)

np.float64(56955.526)

In [104]:
# Ques 86
average_revenue = np.nanmean(clean_data[:,0])

difference = np.abs(clean_data[:,0]-average_revenue)

mask = np.argmin(difference)

data[mask]

array([116, 'Raytheon', '63,000', 120.0, '$24,069', '3.5%', '$2,211.0',
       '6.6%', '$30,052', '$44,664'], dtype=object)

In [105]:
# Ques 87
mask = np.argmax(difference)

data[mask]

array([1, 'Walmart', '23,00,000', 1.0, '$4,85,873', '0.8%', '$13,643.0',
       '-7.2%', '$1,98,825', '$2,18,619'], dtype=object)

In [106]:
# Ques 88
revenue_to_assets_ratio = revenue/assets
revenue_to_assets_ratio

array([ 2.44372187,  0.36015553,  0.67034002,  0.6206337 ,  3.403055  ,
        1.50508916,  1.87933772,  0.75050747,  0.4055906 ,  0.63794647,
        4.36326361,  1.63050047,  0.34684254,  0.51593087,  3.5621007 ,
        3.5798631 ,  1.61444805,  3.159485  ,  0.41359515,  0.03259217,
        0.04234732,  1.93811963,  2.20162454,  1.05082392,  0.04879295,
        0.04281296,  0.53894697,  0.44048861,  1.30391961,  0.04597235,
        0.44544598,  0.6803354 ,  0.29735578,  1.40158364,  0.50910713,
        0.56416751,  1.51963269,  1.85661617,  0.03245319,  1.88958963,
        0.54824628,  0.07062588,  0.91335724,  0.84715833,  1.56770349,
        1.50843302,  0.52403223,  0.07497685,  2.47092974,  0.638129  ,
        1.25769482,  0.60447883,  2.14124272,  0.30780526,  0.1050989 ,
        1.05965778,  3.01202009,  1.09337009,  0.62906161,  0.40481866,
        1.66280593,  0.6056772 ,  1.32552284,  0.4796952 ,  0.14201799,
        2.01619052,  0.78363303,  0.20260883,  0.41736477,  0.66826146,
        0.77327793,  2.84375   ,  0.72585233,  0.5158626 ,  0.30501943,
        0.0465661 ,  0.13941854,  0.04384275,  0.47466808,  0.07092016,
        0.33024603,  1.6484602 ,  0.91071251,  0.33637787,  1.96255153,
        0.21286652,  2.57559764,  1.51318003,  0.27292348,  0.95379046,
        2.72563625,  0.53337312,  1.75233861,  0.9150003 ,  0.44444108,
        0.19456352,  0.11499315,  0.42545527,  0.27557484,  0.07707691,
        0.56499535,  0.18420124,  4.99094772,  0.72413232,  0.45952985,
        0.21984562,  3.30748865,  2.33265125,  0.42125191,  1.29857438,
        0.38787274,  0.79364363,  0.61540386,  0.95682049,  0.2713541 ,
        0.80091175,  1.17683106,  1.67710826,  0.4498558 ,  0.70123848,
        0.17602308,  0.44108518,  0.29617654,  2.56221353,  0.05099963,
        0.17377271,  2.36466567,  1.88373886,  2.14801193,  0.97402479,
        1.48750872,  0.54687419,  0.63214875,  0.8530019 ,  0.39594805,
        1.31951344,  1.08171044,  0.87713648,  0.93216208,  2.44432354,
        0.77316784,  2.27321973,  0.35789153,  0.43960702,  0.18137233,
        2.59493002,  0.57634913,  0.4209919 ,  2.0656467 ,  1.37660233,
        1.87435613,  1.77787465,  0.08190411,  0.39805698,  1.24654157,
        2.38716606,  0.25752937,  4.01121281,  1.1664113 ,  0.37156773,
        1.26837619,  0.94384128,  0.70720795,  0.82528223,  0.76285004,
        0.04482505,  0.25808281,  0.49041548,  1.06463479,  0.17951396,
        4.66136035,  2.08869063,  0.58840741,  1.09328822,  0.42310475,
        2.47973506,  0.04702986,  2.03889619,  0.66552989,  1.73157241,
        0.8108959 ,  1.25340262,  0.9625214 ,  0.91805463,  0.16763666,
        0.53734159,  0.23552745,  1.87795877,  2.47941522,  0.63833666,
        1.2497008 ,  1.36231336,  0.59353082,  0.39555359,  2.31383065,
        0.3280801 ,  1.05548503,  2.69232242,  2.01237766,  0.89777315,
        0.65242821,  0.8946122 ,  2.45216606,  0.68413052,  0.9456598 ,
        0.8137058 ,  0.0509504 ,  0.39198534,  1.59337748,  0.72627817,
        0.71756683,  3.56399132,  0.17109695,  1.21261596,  0.16260507,
        0.86122692,  0.39541111,  0.18366767,  2.42362027,  1.53904529,
        1.34711187,  0.77928629,  0.24470105,  0.55482495,  0.487884  ,
        0.45021786,  0.05435631,  0.6185248 ,  0.40688519,  1.25341411,
        0.47069039,  1.05173458,  1.86244038,  0.25023314,  0.23127886,
        1.75566415,  2.1118705 ,  0.16390169,  0.08392874,  0.26718571,
        0.44496585,  0.28750124,  1.71946508,  1.67052693,  0.05261862,
        0.21699499,  7.68670675,  0.50045898,  0.55742831,  0.72958107,
        0.9422742 ,  0.55419623,  1.22107774,  0.39980773,  0.05066378,
        0.26988215,  0.31256   ,  0.17834426,  1.48967391,  0.71279781,
        2.44016136,  0.24128597,  0.23627571,  0.32752319,  0.74204826,
        0.05032791,  0.57702811,  0.54150915,  0.52306559,  1.23674419,
        0.04381989,  0.33176243,  0.89313106,  1.11657482,  0.54489965,
        1.01841442,  0.11371712,  0.24120253,  1.12019651,  0.21309589,
        0.6537373 ,  1.78029505,  1.22346369,  0.28338874,  0.51702217,
        0.06006914,  2.67436109,  3.57726269,  1.05093046,  0.67677406,
        4.61129727,  1.15069152,  0.66058218,  0.52749931,  1.49497645,
        0.49490995,  0.33560501,  0.3365712 ,  0.45506544,  0.55659757,
        0.35499981,  0.06398554,  0.04471507,  1.09382151,  1.02671194,
        0.56025475,  2.07821101,  0.22612927,  0.58277803,  0.37652535,
        0.87567198,  0.55276039,  0.30662117,  0.64995952,  0.38959492,
        0.09910683,  0.55609076,  2.25754422,  0.49078955,  1.16219134,
        1.72990354,  1.98042377,  1.19280955,  1.38744133,  2.96984572,
        0.47722491,  0.46341733,  0.39841187,  0.07996522,  1.23521585,
        3.35225443,  0.53729897,  0.86300656,  3.21372855,  0.74114565,
        0.32835101,  1.43481337,  1.49795918,  1.01582238,  1.9521932 ,
        0.41064283,  0.20535552,  0.60423703,  0.17270213,  0.62851422,
        0.48867618,  1.21061644,  2.02239583,  1.3926259 ,  4.00777202,
        2.95855718,  0.28796282,  0.75348792,  0.32758399,  1.42902503,
        0.25971689,  0.03421926,  0.23832403,  1.86248168,  1.93939394,
        0.25352587,  0.34486234,  0.62745915,  1.31838094,  0.19618948,
        0.74405941,  0.1601153 ,  0.24804966,  1.34685011,  1.03390067,
        1.19185579,  1.43215885,  1.6334892 ,  1.15113151,  0.34299905,
        1.18223458,  0.42533104,  0.27976797,  0.91856256,  1.1127204 ,
        0.77124398,  0.38095238,  0.30885987,  1.27043226,  1.51298276,
        1.14172448,  0.70216441,  1.60933489,  0.04845369,  0.32431158,
        0.89186001,  0.67160933,  1.25679926,  0.62248922, 15.52402746,
        2.53457944,  0.91730951,  0.31407909,  1.81164475,  0.34767303,
        0.73366174,  0.51985083,  0.69906187,  0.34143328,  0.41108143,
        0.37863855,  1.7121964 ,  0.38597112,  0.85273035,  2.79452055,
        0.11799099,  0.41229852,  0.84790278,  1.78786207,  0.7437134 ,
        0.65774691,  1.65072016,  0.17888973,  0.29594857,  3.04192473,
        2.18797251,  1.16210296,  2.31254585,  0.73961643,  1.39100576,
        0.4877935 ,  0.94332417,  0.25807131,  2.18487997,  1.38466788,
        0.24600186,  0.87767805,  0.71345858,  0.47734139,  0.60637007,
        0.04736917,  0.07265588,  0.59536238,  0.31739458,  0.47962842,
        1.45763132,  0.82805239,  0.46069096,  1.71190407,  1.16656681,
        2.20688351,  1.19876543,  0.78291335,  0.18737653,  1.0003462 ,
        0.03854334,  0.48064731,  1.27512174,  0.99204015,  0.04635112,
        0.98650986,  0.52420024,  0.73336778,  0.6530165 ,  0.21688889,
        0.570221  ,  0.48694517,  2.17126214,  0.63134058,  0.47318773,
        1.5776768 ,  0.63345886,  0.55255554,  0.17471672,  3.31987952,
        0.56502104,  0.48106592,  2.47228481,  0.84031414,  0.24103471,
        0.26729128,  0.17473637,  0.57569002,  0.03973529,  1.81373534,
        1.79601329,  0.89108911,  0.12315484,  0.64484863,  0.45768904,
        1.13123028,  2.4810536 ,  0.23775478,  0.86617767,  2.60207101,
        0.16814864,  0.68236668,  2.95275591,  1.96031449,  3.23383085,
        2.41945996,  0.53096436,  0.10750161,  0.34047603,  2.25558965])

In [107]:
# Ques 89
profit_margin = profits/revenue
profit_margin

array([ 2.80793541e-02,  1.07663548e-01,  2.11867983e-01,  3.82431562e-02,
        1.17306623e-02,  3.79625622e-02,  2.99505425e-02,  5.66594543e-02,
        7.92253306e-02,  3.02766798e-02,  9.72352741e-03,  1.74354902e-02,
        6.97215402e-02,  1.04199079e-01,  1.17404110e-02,  1.97946411e-02,
        3.55599867e-02,  1.71237331e-02, -4.62037614e-03,  1.14900804e-01,
        2.34467133e-01,  3.39462348e-02,  8.41164966e-02,  5.17600533e-02,
        2.32946823e-01,  1.91176785e-01,  2.15770117e-01,  1.96882325e-01,
        2.91033784e-02,  1.81001626e-01,  1.08142731e-01,  1.48550407e-01,
        4.60121894e-03,  2.14790872e-02,  2.30073724e-01,  1.46501966e-01,
        3.26226377e-02,  3.93841284e-02,  1.19013173e-01,  4.75721734e-02,
       -2.58000802e-02,  1.26031886e-02,  3.59591481e-02,  1.00781860e-01,
        2.05145478e-02,  5.63327094e-02,  1.73708051e-01,  7.43122544e-02,
       -8.55041373e-03,  8.83061980e-02,  2.10175803e-02,  1.68805723e-01,
        1.12911234e-02,  1.36585643e-01, -1.62125002e-02,  1.04662640e-01,
        1.88536145e-02,  3.61362057e-02,  6.30648604e-02,  2.18064045e-01,
        5.17434388e-02,  8.96631920e-02,  6.45853353e-02,  1.55913336e-01,
        2.66776179e-02,  1.38012328e-02,  6.66002987e-02,  8.34206718e-03,
        9.84751426e-02,  4.70656449e-02,  1.10320644e-01,  3.11651397e-02,
        1.22360185e-01, -1.73858889e-03,  2.62608332e-02,  1.57553559e-01,
        3.37011750e-02,  1.96170980e-01,  2.65305034e-02,  4.02182994e-02,
        2.40262369e-01,  4.79379626e-02,  6.19050224e-02,  5.13767997e-02,
        5.91031102e-02,  1.59891198e-01,  6.92562681e-02,  1.16135409e-01,
        3.61607143e-02,  9.42493541e-02,  5.38439015e-03,  4.44257980e-01,
        1.39783175e-02,  1.67723936e-01,  1.33910908e-01,  1.21435714e-01,
        2.84037640e-02,  3.69672190e-01,  1.09104072e-01,  1.36305825e-01,
        1.00819732e-01,  6.55744351e-02,  4.68241042e-03,  2.61083005e-01,
        5.71948656e-02,  1.37123872e-01,  7.43663046e-03,  1.93180518e-02,
        6.39972225e-02,  2.40127240e-02,  2.32194399e-01,  1.90337909e-01,
        1.02179393e-01,  8.97666068e-02, -1.48399015e-01,  9.18608999e-02,
        3.05769631e-02,  2.19433368e-02,  2.42209391e-01,  4.39827652e-02,
        9.20878086e-02,  1.09160803e-01,  3.35870558e-01,  9.15397705e-03,
        2.58881463e-01,  1.17868700e-01, -1.00325233e-01,  5.69018056e-02,
        1.99222546e-02, -8.05183868e-02,  1.32187090e-01,  1.28998209e-01,
        4.28862849e-02, -9.11248220e-03,  6.71366230e-02,  4.32549833e-02,
        4.28612800e-02,  1.09865361e-01,  8.06690349e-02, -7.40465945e-02,
        4.65761570e-03,  1.70232835e-02,  2.12276215e-01,  1.28249297e-01,
        1.23039807e-01,  2.25755571e-02,  2.29422968e-01,  7.36360345e-01,
        1.47817408e-02,  2.97548967e-02,  5.25433775e-02,  1.38451479e-02,
        4.89617486e-02,  1.10638065e-01,  1.18997912e-01,  2.92430548e-03,
        7.88520322e-02,  1.01546009e-02,  7.96161974e-02,  3.58328563e-02,
        5.51949917e-03, -2.78523882e-02,  4.56888472e-02,  3.06287794e-02,
        1.02481435e-01,  2.37654509e-01,  3.72954823e-02, -6.89992660e-02,
        4.91300592e-02,  1.80253791e-01,  4.24091897e-03,  1.07286432e-02,
       -3.62749418e-01,  3.93734605e-02, -2.63094560e-01,  3.22437039e-02,
        2.26168463e-01,  4.35679299e-02,  7.45021729e-02,  4.47979140e-02,
        5.78995854e-02,  1.60644949e-01,  5.77809988e-02,  8.33883098e-02,
        1.48855971e-01,  9.60516727e-02,  3.97228484e-01,  2.39886156e-02,
        3.70721789e-03, -2.69481844e-02,  4.71988508e-03,  1.99639290e-02,
        8.76546643e-02, -7.90928816e-02,  1.70049870e-02, -4.36352077e-01,
       -4.78986840e-02,  1.67045939e-02,  3.03533114e-02,  6.97708152e-02,
        8.68542876e-02,  1.49643356e-01,  3.89400074e-02,  9.89483040e-02,
        1.15147920e-01,  2.68885565e-01,  8.94223556e-02,  3.97919180e-02,
        1.85067634e-02,  1.33827871e-01,  9.34843762e-02,  3.90596470e-02,
        4.99046166e-02,  4.37576499e-02,  5.42196355e-02,  5.33271861e-02,
        1.86239803e-02,  2.04272777e-02,  8.68656252e-02,  9.21027517e-02,
        7.97003268e-05, -1.18197075e-02,  4.85723426e-01,  1.15150545e-01,
        7.81863334e-02, -2.22598597e-02,  1.06220752e-01, -7.59238341e-02,
       -6.26669905e-02,  8.79904973e-02, -2.70722309e-01,  7.29044995e-02,
        6.95224719e-02,  1.03105590e-01,  1.10455809e-01,  9.55381242e-02,
       -1.69391926e-02,  1.80880975e-01,  1.11972731e-01,  1.27913953e-01,
        2.98379491e-02,  3.62569061e-02,  4.37953681e-02, -3.11958406e-03,
        2.10261744e-01,  6.08748481e-02,  4.71017641e-03,  3.23416892e-01,
        1.46362840e-01,  8.46234768e-02,  7.10148755e-02,  1.45430464e-01,
        9.89699876e-02,  1.78039006e-01,  2.84356791e-01,  1.01143423e-01,
        1.54846870e-01,  8.43124830e-02,  1.91991974e-02,  8.32694064e-02,
        1.35102866e-02,  1.19540230e-02, -5.38078554e-02,  1.29219701e-01,
        1.58983834e-01, -3.96957893e-02,  3.76670379e-01,  1.98734059e-01,
        1.15995116e-01,  1.16679203e-01,  2.01504466e-01,  8.16556914e-02,
        6.70000944e-02, -2.47247532e-02,  1.42396051e-01,  6.68443091e-02,
        2.27969896e-01, -5.52029236e-02, -4.28808108e-02,  1.34537955e-01,
        4.88536849e-01,  5.97711354e-02,  5.62934286e-02,  1.68689320e-01,
       -2.78223758e-01,  1.08490086e-01,  9.57665434e-03,  1.11899619e-02,
        3.37578958e-02,  7.59282307e-02,  2.29938752e-02,  4.80351171e-02,
        6.80343312e-02,  6.62641747e-02,  9.34684448e-02, -5.17932489e-02,
        1.16488630e-01,  3.93503727e-01,  6.52535151e-02, -4.29276669e-02,
        6.14652094e-02,  8.98680336e-02,  2.04999454e-01,  5.10900683e-02,
        1.30636093e-02,  2.90254939e-02,  3.57576426e-02,  9.78920649e-02,
        9.48046181e-02,  8.09221517e-01,  1.03850876e-01,  3.94574599e-02,
       -4.19289568e-02,  2.11414336e-02,  3.68784687e-02,  6.69704911e-02,
        3.21176202e-02,  2.27126066e-02,  1.88243446e-02,  3.53303146e-02,
        4.10315985e-02,  4.22142110e-02,  1.20761085e-01,  4.61915316e-02,
        1.48524203e-02,  2.14013346e-02,  4.13784880e-02, -7.48299320e-02,
       -3.30983391e-02,  3.47097546e-04,  2.52191666e-03,  2.15170093e-02,
        5.98744568e-02, -2.41990291e-02,  6.69267341e-02,  8.28438571e-02,
       -1.19590679e-02, -8.47163735e-03,  7.07197588e-02,  3.62787175e-02,
        1.29967097e-01,  4.51449551e-02, -5.59070122e-01, -3.90265599e-01,
        7.75455588e-02,  8.81705287e-02,  4.91320561e-02,  8.55009014e-02,
        1.61306987e-02,  7.34324499e-03,  1.55512322e-02,  3.98099948e-02,
        7.85891250e-02,  7.86386203e-02,  2.59312508e-02, -1.43340740e-01,
        2.47121926e-01,  1.23353842e-01,  1.58032787e-02,  2.40863347e-02,
        7.50663834e-02,  5.73857598e-02,  4.30450379e-02,  2.60499734e-02,
        2.53026473e-01,  8.58283433e-02, -5.65408721e-02,  1.25669165e-01,
        9.67741935e-02,  2.16030225e-02,  5.34773801e-02,  6.67391600e-02,
        1.38495093e-02,  1.67583173e-02, -3.32643773e-01, -9.19053549e-02,
        4.15747592e-02,  7.22611376e-02,  3.53222629e-02,  8.10696095e-02,
        3.46443277e-02,  1.05744014e-01, -9.64142857e-02, -1.70121515e-03,
        5.40813383e-02,  5.23292824e-02,  2.41099855e-01, -7.19112529e-02,
        2.27028596e-01,  1.67199767e-02,  4.67666079e-02,  7.49043273e-02,
        6.91447078e-02,  3.86768823e-02,  1.37087264e-03,  6.44690265e-02,
        7.17615816e-02,  1.04250923e-01,  7.43483412e-02,  1.36986301e-02,
        3.11847210e-02, -2.79928262e-02,  1.14445115e-01,  1.12484922e-01,
        2.60909640e-01,  1.46186441e-01,  6.59090909e-02,  1.61102627e-01,
        4.12654746e-02,  2.56127451e-02,  9.98768852e-02,  1.83777128e-01,
        3.63692403e-02,  2.89770097e-02,  7.48340281e-02,  1.31521739e-01,
        2.63633531e-02, -3.10479463e-02,  8.61072043e-02,  1.45810493e-02,
        2.26637349e-02,  2.54319824e-01,  3.58502538e-02,  1.30909959e-01,
        3.44640866e-02, -4.72266497e-02, -3.70202429e-02,  7.45229163e-02,
        7.06461135e-02,  5.26860522e-02,  1.07472021e-01,  8.89658585e-02,
        9.27459424e-02,  1.22251832e-01,  1.15424379e-01,  1.94905313e-01,
        2.38670695e-01,  1.37244984e-01,  7.91221827e-02,  1.55283724e-01,
       -1.32585416e-03,  1.24098639e-01,  1.99658353e-01, -1.83837348e-02,
       -3.01489471e-02,  7.28877464e-02,  1.09852386e-01,  3.66609294e-02,
        1.65295541e-01,  7.77989272e-02,  1.81329169e-01,  9.82297813e-02,
        1.12480472e-01, -1.11634397e-02,  2.29832226e-01,  8.50105189e-02,
        6.41399930e-02,  6.92267042e-02,  3.72019078e-01,  8.12009979e-02,
        1.09126630e-01,  7.40661305e-02,  3.86156323e-02,  6.15136298e-02,
        4.46839080e-01,  3.36993699e-02, -7.02576112e-04,  4.12910206e-02,
        9.59057971e-02, -3.62910543e-04,  1.68937330e-01,  1.38848397e-01,
        1.54393000e-02,  5.82737768e-02,  7.53990094e-02,  1.08405212e-01,
        3.38344066e-01,  4.66900240e-02,  1.45887127e-01, -2.83893609e-02,
        5.44025157e-02,  1.29629630e-03,  4.46832160e-02,  1.67006866e-01,
       -7.11899016e-02,  5.80033463e-02,  1.19016577e-02, -2.62420620e-01,
        6.35114791e-02,  2.28917946e-02,  1.28885519e-01,  1.38429359e-01,
        6.54095238e-02,  2.86478228e-03,  2.93846154e-02,  7.27727535e-02,
        7.39071567e-02, -4.14586961e-02,  3.45367032e-01,  1.11175899e-02])

In [108]:
# Ques 90
data[np.argsort(profit_margin)][-20:]

array([[125, 'U.S. Bancorp', '71,191', 131.0, '$22,744', '5.8%',
        '$5,888.0', '0.2%', '$4,45,964', '$87,201'],
       [405, 'Franklin Resources', '9,059', 344.0, '$6,618', '-16.7%',
        '$1,726.7', '-15.2%', '$16,099', '$23,823'],
       [104, 'Philip Morris International', '79,500', 106.0, '$26,685',
        '-0.4%', '$6,967.0', '1.4%', '$36,851', '$1,75,349'],
       [206, 'Texas Instruments', '29,865', 219.0, '$13,370', '2.8%',
        '$3,595.0', '20.4%', '$16,431', '$80,531'],
       [255, 'BlackRock', '13,000', 250.0, '$11,155', '-2.2%',
        '$3,172.0', '-5.2%', '$2,20,177', '$62,225'],
       [248, 'Biogen', '7,400', 263.0, '$11,449', '6.4%', '$3,702.8',
        '4.4%', '$22,877', '$59,046'],
       [123, 'Amgen', '19,200', 130.0, '$22,991', '6.1%', '$7,722.0',
        '11.3%', '$77,626', '$1,20,830'],
       [477, 'Simon Property Group', '4,050', 488.0, '$5,435', '3.2%',
        '$1,838.9', '0.6%', '$31,104', '$53,732'],
       [499, 'Vistra Energy', '4,431', nan, '$5,164', '-', '-', '-',
        '$15,167', '$6,968'],
       [98, 'Facebook', '17,048', 157.0, '$27,638', '54.2%', '$10,217.0',
        '177.0%', '$64,961', '$4,10,522'],
       [459, 'S&P Global', '20,000', 481.0, '$5,661', '6.6%', '$2,106.0',
        '82.2%', '$8,669', '$33,805'],
       [267, 'MasterCard', '11,900', 294.0, '$10,776', '11.5%',
        '$4,059.0', '6.6%', '$18,675', '$1,21,234'],
       [298, 'Corning', '40,700', 313.0, '$9,390', '3.1%', '$3,695.0',
        '176.0%', '$27,899', '$25,030'],
       [187, 'Visa', '14,200', 204.0, '$15,082', '8.7%', '$5,991.0',
        '-5.3%', '$64,035', '$2,06,242'],
       [92, 'Gilead Sciences', '9,000', 86.0, '$30,390', '-6.9%',
        '$13,501.0', '-25.4%', '$56,977', '$88,788'],
       [465, 'Symantec', '11,000', 400.0, '$5,568', '-14.4%', '$2,488.0',
        '183.4%', '$11,767', '$18,986'],
       [223, 'Reynolds American', '5,525', 266.0, '$12,503', '17.1%',
        '$6,073.0', '86.7%', '$51,095', '$89,862'],
       [281, 'Baxter International', '48,000', 286.0, '$10,163', '2.0%',
        '$4,965.0', '412.9%', '$15,546', '$28,106'],
       [148, 'Altria Group', '8,300', 149.0, '$19,337', '2.6%',
        '$14,239.0', '171.7%', '$45,932', '$1,38,513'],
       [310, 'eBay', '12,600', 300.0, '$8,979', '-5.4%', '$7,266.0',
        '321.2%', '$23,847', '$36,232']], dtype=object)

In [109]:
# Ques 91
revenue_per_employee = revenue/No_of_employees

data[np.argmax(revenue_per_employee)]

array([20, 'Fannie Mae', '7,000', 16.0, '$1,07,162', '-2.9%', '$12,313.0',
       '12.4%', '$32,87,968', '$3,011'], dtype=object)

In [110]:
# Ques 92
assets_per_employee = assets/No_of_employees

data[np.argmax(assets_per_employee)]

array([20, 'Fannie Mae', '7,000', 16.0, '$1,07,162', '-2.9%', '$12,313.0',
       '12.4%', '$32,87,968', '$3,011'], dtype=object)

In [111]:
# Ques 93
profit_order = np.argsort(profits)[::-1]
profit_rank = np.arange(1, len(profit_order)+1)
companies = data[profit_order, 1]
profit = profits[profit_order]

result = np.column_stack((profit_rank, companies, profit))
result

array([[1, 'Apple', 45687.0],
       [2, 'J.P. Morgan Chase', 24733.0],
       [3, 'Berkshire Hathaway', 24074.0],
       ...,
       [498, 'Chesapeake Energy', -4401.0],
       [499, 'Halliburton', -5763.0],
       [500, 'FirstEnergy', -6177.0]], shape=(500, 3), dtype=object)

In [112]:
# Ques 94
market_value_order = np.argsort(market_value)[::-1]
market_value_rank = np.arange(1,len(market_value_order)+1)
companies_market_value = data[market_value_order,1]
market_val = market_value[market_value_order]

result = np.column_stack((market_value_rank, companies_market_value, market_val))
result

array([[1, 'Apple', 753718.0],
       [2, 'Alphabet', 579426.0],
       [3, 'Microsoft', 508935.0],
       ...,
       [498, 'iHeartMedia', 330.0],
       [499, 'TravelCenters of America', 241.0],
       [500, 'A-Mark Precious Metals', 120.0]],
      shape=(500, 3), dtype=object)

In [113]:
# Ques 95
# Step1: rank according to profit
profit_order = np.argsort(profits)[::-1]
profit_rank = np.arange(1,len(profit_order)+1)

companies = data[profit_order, 1]

# Step2: find original rank according to profit_order
original_rank = data[profit_order, 0]

# Step3: combine
compare_profit_original = np.column_stack((profit_rank, original_rank, companies))

In [114]:
# Ques 96
compare_profit_original[compare_profit_original[:,0] < compare_profit_original[:,1]]

array([[1, 3, 'Apple'],
       [2, 21, 'J.P. Morgan Chase'],
       [4, 25, 'Wells Fargo'],
       [5, 27, 'Alphabet'],
       [6, 26, 'Bank of America Corp.'],
       [7, 28, 'Microsoft'],
       [8, 35, 'Johnson & Johnson'],
       [9, 30, 'Citigroup'],
       [10, 148, 'Altria Group'],
       [12, 92, 'Gilead Sciences'],
       [13, 14, 'Verizon'],
       [15, 20, 'Fannie Mae'],
       [16, 32, 'IBM'],
       [17, 60, 'Cisco Systems'],
       [18, 36, 'Procter & Gamble'],
       [19, 47, 'Intel'],
       [20, 98, 'Facebook'],
       [22, 52, 'Disney'],
       [23, 81, 'Oracle'],
       [25, 31, 'Comcast'],
       [28, 39, 'Freddie Mac'],
       [29, 123, 'Amgen'],
       [30, 78, 'Goldman Sachs Group'],
       [31, 310, 'eBay'],
       [32, 54, 'Pfizer'],
       [34, 104, 'Philip Morris International'],
       [35, 64, 'Coca-Cola'],
       [36, 44, 'PepsiCo'],
       [37, 223, 'Reynolds American'],
       [38, 187, 'Visa'],
       [39, 76, 'Morgan Stanley'],
       [40, 111, 'AbbVie'],
       [41, 125, 'U.S. Bancorp'],
       [42, 119, 'Qualcomm'],
       [43, 86, 'American Express'],
       [45, 56, 'Lockheed Martin'],
       [46, 50, 'United Technologies'],
       [47, 94, '3M'],
       [48, 281, 'Baxter International'],
       [50, 73, 'Honeywell International'],
       [51, 112, 'McDonaldÕs'],
       [53, 147, 'Bristol-Myers Squibb'],
       [54, 71, 'Delta Air Lines'],
       [56, 62, 'Dow Chemical'],
       [57, 143, 'Union Pacific'],
       [59, 267, 'MasterCard'],
       [60, 95, 'Time Warner'],
       [61, 69, 'Merck'],
       [62, 166, 'PNC Financial Services Group'],
       [63, 88, 'Nike'],
       [64, 100, 'Capital One Financial'],
       [65, 248, 'Biogen'],
       [66, 298, 'Corning'],
       [67, 106, 'Kraft Heinz'],
       [68, 206, 'Texas Instruments'],
       [69, 177, 'Bank of New York Mellon Corp.'],
       [70, 96, 'Charter Communications'],
       [73, 255, 'BlackRock'],
       [76, 99, 'Travelers Cos.'],
       [77, 90, 'General Dynamics'],
       [78, 170, 'NextEra Energy'],
       [80, 131, 'Starbucks'],
       [81, 101, 'Twenty-First Century Fox'],
       [82, 132, 'Eli Lilly'],
       [85, 126, 'Aflac'],
       [86, 144, 'Danaher'],
       [87, 122, 'Enterprise Products Partners'],
       [88, 113, 'DuPont'],
       [90, 465, 'Symantec'],
       [92, 145, 'Southern'],
       [93, 182, 'Colgate-Palmolive'],
       [94, 245, 'BB&T Corp.'],
       [95, 277, 'Discover Financial Services'],
       [103, 185, 'Synchrony Financial'],
       [104, 138, 'Southwest Airlines'],
       [105, 116, 'Raytheon'],
       [106, 114, 'Northrop Grumman'],
       [107, 155, 'Kimberly-Clark'],
       [108, 121, 'Duke Energy'],
       [109, 271, 'State Street Corp.'],
       [110, 268, 'Priceline Group'],
       [111, 238, 'Dominion Resources'],
       [112, 459, 'S&P Global'],
       [113, 202, 'Illinois Tool Works'],
       [115, 154, 'Thermo Fisher Scientific'],
       [116, 254, 'Celgene'],
       [118, 365, 'PPL'],
       [119, 357, 'Charles Schwab'],
       [120, 303, 'SunTrust Banks'],
       [123, 477, 'Simon Property Group'],
       [125, 499, 'Vistra Energy'],
       [127, 210, 'Marsh & McLennan'],
       [129, 405, 'Franklin Resources'],
       [130, 265, 'Applied Materials'],
       [131, 257, 'CSX'],
       [132, 165, 'General Mills'],
       [133, 249, 'Las Vegas Sands'],
       [134, 284, 'Norfolk Southern'],
       [135, 387, 'Nvidia'],
       [137, 252, 'Stryker'],
       [138, 139, 'Emerson Electric'],
       [139, 422, 'Yum Brands'],
       [140, 389, 'Fifth Third Bancorp'],
       [142, 205, 'Cognizant Technology Solutions'],
       [144, 275, 'Praxair'],
       [145, 240, 'ADP'],
       [147, 186, 'DISH Network'],
       [148, 224, 'Viacom'],
       [151, 437, 'Intercontinental Exchange'],
       [152, 264, 'PayPal Holdings'],
       [154, 159, 'Cummins'],
       [155, 157, 'PG&E Corp.'],
       [156, 280, 'Sempra Energy'],
       [157, 204, 'Monsanto'],
       [158, 227, 'Principal Financial'],
       [159, 455, 'M&T Bank Corp.'],
       [160, 239, 'Ameriprise Financial'],
       [161, 235, 'Edison International'],
       [164, 184, 'Goodyear Tire & Rubber'],
       [165, 193, 'CBS'],
       [167, 234, 'Consolidated Edison'],
       [168, 270, 'AutoZone'],
       [169, 269, 'Liberty Interactive'],
       [170, 211, 'Ecolab'],
       [172, 412, 'Discovery Communications'],
       [173, 207, 'Lincoln National'],
       [174, 201, 'Waste Management'],
       [176, 443, 'Adobe Systems'],
       [177, 436, 'Regions Financial'],
       [178, 220, 'L Brands'],
       [181, 236, 'Sherwin-Williams'],
       [182, 256, 'Xcel Energy'],
       [183, 219, 'Ross Stores'],
       [184, 253, 'Estee Lauder'],
       [185, 297, 'MGM Resorts International'],
       [187, 230, 'VF'],
       [188, 286, 'Ally Financial'],
       [189, 408, 'Constellation Brands'],
       [190, 451, 'Citizens Financial Group'],
       [191, 323, 'OÕReilly Automotive'],
       [193, 341, 'Weyerhaeuser'],
       [196, 225, 'Becton Dickinson'],
       [198, 406, 'Activision Blizzard'],
       [199, 250, 'Stanley Black & Decker'],
       [201, 449, 'American Tower'],
       [203, 358, 'Eversource Energy'],
       [204, 368, 'WEC Energy Group'],
       [205, 258, 'Unum Group'],
       [206, 311, 'Mohawk Industries'],
       [207, 471, 'Fiserv'],
       [208, 440, 'Lam Research'],
       [209, 260, 'Lennar'],
       [211, 484, 'Regions Financial'],
       [214, 295, 'Hormel Foods'],
       [216, 308, 'Public Service Enterprise Group'],
       [217, 232, 'D.R. Horton'],
       [220, 272, 'DTE Energy'],
       [221, 309, 'Eastman Chemical'],
       [222, 416, 'Dr Pepper Snapple Group'],
       [223, 233, 'Bed Bath & Beyond'],
       [224, 302, 'Pacific Life'],
       [225, 424, 'Amphenol'],
       [227, 438, 'Alaska Air Group'],
       [228, 251, 'Parker-Hannifin'],
       [231, 479, 'KeyCorp'],
       [233, 472, 'Host Hotels & Resorts'],
       [234, 403, 'JetBlue Airways'],
       [235, 404, 'Jones Financial'],
       [236, 382, 'Erie Insurance Group'],
       [237, 434, 'St. Jude Medical'],
       [239, 290, 'Laboratory Corp. of America'],
       [240, 442, 'Rockwell Automation'],
       [241, 492, 'Rockwell Collins'],
       [242, 369, 'Hershey'],
       [243, 273, 'L-3 Communications'],
       [245, 398, 'Auto-Owners Insurance'],
       [246, 276, 'Universal Health Services'],
       [249, 435, 'Harley-Davidson'],
       [250, 346, 'J.M. Smucker'],
       [252, 491, 'Liberty Media'],
       [253, 336, 'Level 3 Communications'],
       [255, 348, 'Foot Locker'],
       [257, 431, 'Ameren'],
       [258, 293, 'Fidelity National Financial'],
       [259, 411, 'American Financial Group'],
       [260, 453, 'Clorox'],
       [261, 366, 'Quest Diagnostics'],
       [262, 447, 'Dana Holding'],
       [263, 294, 'Air Products & Chemicals'],
       [268, 299, 'Republic Services'],
       [269, 461, 'Wyndham Worldwide'],
       [271, 345, 'Interpublic Group'],
       [272, 282, 'W.W. Grainger'],
       [273, 353, 'PulteGroup'],
       [274, 354, 'W.R. Berkley'],
       [275, 476, 'Cincinnati Financial'],
       [276, 316, 'Thrivent Financial for Lutherans'],
       [277, 380, 'Huntington Ingalls Industries'],
       [279, 301, 'Fidelity National Information Services'],
       [280, 283, 'Autoliv'],
       [281, 452, 'United Rentals'],
       [282, 361, 'Assurant'],
       [283, 339, 'Campbell Soup'],
       [285, 433, 'Motorola Solutions'],
       [287, 419, 'CMS Energy'],
       [288, 335, 'PVH'],
       [289, 432, 'Hanesbrands'],
       [290, 469, 'Raymond James Financial'],
       [295, 378, 'Alliance Data Systems'],
       [297, 392, 'Dover'],
       [301, 399, 'Yum China Holdings'],
       [302, 333, 'Crown Holdings'],
       [303, 372, 'Masco'],
       [304, 397, 'Sealed Air'],
       [305, 456, 'Ingredion'],
       [306, 415, 'CalAtlantic Group'],
       [307, 393, 'Spirit AeroSystems Holdings'],
       [308, 439, 'Old Republic International'],
       [311, 428, 'Alleghany'],
       [312, 460, 'Markel'],
       [313, 450, 'Packaging Corp. of America'],
       [315, 396, 'Tractor Supply'],
       [316, 407, 'J.B. Hunt Transport Services'],
       [317, 362, 'CenterPoint Energy'],
       [318, 429, 'Expeditors International of Washington'],
       [320, 446, 'NVR'],
       [324, 462, 'Arthur J. Gallagher'],
       [325, 475, 'AmTrust Financial Services'],
       [326, 371, 'Ralph Lauren'],
       [328, 458, 'Owens Corning'],
       [329, 347, 'Steel Dynamics'],
       [330, 497, 'Toll Brothers'],
       [331, 496, 'Michaels Cos.'],
       [332, 385, 'Darden Restaurants'],
       [333, 457, 'UGI'],
       [335, 386, 'Harman International Industries'],
       [336, 342, 'Mutual of Omaha Insurance'],
       [343, 493, 'Robert Half International'],
       [344, 464, 'First American Financial'],
       [346, 489, 'Airgas'],
       [350, 363, 'Harris'],
       [352, 430, 'Avery Dennison'],
       [353, 391, 'Jones Lang LaSalle'],
       [354, 474, 'Mattel'],
       [355, 486, 'Seaboard'],
       [358, 377, 'Mosaic'],
       [359, 481, 'Booz Allen Hamilton Holding'],
       [364, 409, 'NCR'],
       [367, 394, 'Ryder System'],
       [369, 478, 'Western Union'],
       [370, 379, 'Computer Sciences'],
       [372, 381, 'Leidos Holdings'],
       [375, 483, 'Western & Southern Financial Group'],
       [376, 413, 'Berry Global Group'],
       [378, 468, 'NetApp'],
       [379, 423, 'CaseyÕs General Stores'],
       [381, 425, 'Oshkosh'],
       [382, 463, 'Burlington Stores'],
       [383, 448, 'Realogy Holdings'],
       [386, 401, 'Owens-Illinois'],
       [391, 414, 'Sanmina'],
       [392, 466, 'Patterson'],
       [399, 417, 'DillardÕs'],
       [400, 410, 'Asbury Automotive Group'],
       [404, 495, 'Big Lots'],
       [406, 421, 'Builders FirstSource'],
       [412, 490, 'Kelly Services'],
       [424, 473, 'Insight Enterprises'],
       [427, 487, 'Essendant'],
       [428, 500, 'ABM Industries'],
       [434, 494, 'CH2M Hill'],
       [436, 482, 'Chemours'],
       [439, 470, 'TravelCenters of America'],
       [440, 467, 'Olin'],
       [444, 454, 'Genesis Healthcare'],
       [450, 480, 'Delek US Holdings'],
       [457, 498, 'Yahoo'],
       [464, 485, 'Windstream Holdings'],
       [487, 488, 'Apache']], dtype=object)

In [115]:
# Ques 97
revenue_order = np.argsort(revenue)[::-1]
revenue_rank = np.arange(1,len(revenue_order)+1)

companies = data[revenue_order, 1]

original_rank = data[revenue_order, 0]

difference_in_rank = np.abs(revenue_rank - original_rank)

compare = np.column_stack((revenue_rank, original_rank, companies))

data[revenue_order][difference_in_rank > 100]

array([], shape=(0, 10), dtype=object)

In [116]:
profit_order = np.argsort(profits)[::-1]
profit_rank = np.arange(1,len(profit_order)+1)
data[profit_order]

array([[3, 'Apple', '1,16,000', ..., '-14.4%', '$3,21,686', '$7,53,718'],
       [21, 'J.P. Morgan Chase', '2,43,355', ..., '1.2%', '$24,90,972',
        '$3,13,761'],
       [2, 'Berkshire Hathaway', '3,67,700', ..., '0.0%', '$6,20,854',
        '$4,11,035'],
       ...,
       [343, 'Chesapeake Energy', '3,300', ..., '-', '$13,028', '$5,394'],
       [173, 'Halliburton', '50,000', ..., '-', '$27,000', '$42,662'],
       [196, 'FirstEnergy', '15,707', ..., '-', '$43,148', '$14,118']],
      shape=(500, 10), dtype=object)

In [117]:
# Ques 98
revenue_order = np.argsort(revenue)[::-1]
revenue_rank = np.arange(1,len(revenue_order)+1)
revenue_rank_by_company = np.empty(len(revenue), dtype=int)
revenue_rank_by_company[revenue_order] = np.array(revenue_rank)

profit_order = np.argsort(profits)[::-1]
profit_rank = np.arange(1,len(profit_order)+1)
profit_rank_by_company = np.empty(len(revenue), dtype=int)
profit_rank_by_company[profit_order] = np.array(profit_rank)

assets_order = np.argsort(assets)[::-1]
assets_rank = np.arange(1,len(assets_order)+1)
assets_rank_by_company = np.empty(len(revenue), dtype=int)
assets_rank_by_company[assets_order] = np.array(assets_rank)

market_value_order = np.argsort(market_value)[::-1]
market_value_rank = np.arange(1,len(market_value_order)+1)
market_value_rank_by_company = np.empty(len(revenue), dtype=int)
market_value_rank_by_company[market_value_order] = np.array(market_value_rank)

sum_of_rank = revenue_rank_by_company + profit_rank_by_company + assets_rank_by_company + market_value_rank_by_company

index_to_compare = np.argsort(sum_of_rank)

data[index_to_compare][:5]

array([[2, 'Berkshire Hathaway', '3,67,700', 4.0, '$2,23,604', '6.1%',
        '$24,074.0', '0.0%', '$6,20,854', '$4,11,035'],
       [3, 'Apple', '1,16,000', 3.0, '$2,15,639', '-7.7%', '$45,687.0',
        '-14.4%', '$3,21,686', '$7,53,718'],
       [21, 'J.P. Morgan Chase', '2,43,355', 23.0, '$1,05,486', '4.4%',
        '$24,733.0', '1.2%', '$24,90,972', '$3,13,761'],
       [25, 'Wells Fargo', '2,69,100', 27.0, '$94,176', '4.6%',
        '$21,938.0', '-4.2%', '$19,30,115', '$2,78,516'],
       [26, 'Bank of America Corp.', '2,08,024', 26.0, '$93,662', '0.7%',
        '$17,906.0', '12.7%', '$21,87,702', '$2,36,182']], dtype=object)

In [118]:
# Ques 99
mean = np.nanmean(clean_data,axis=0)
median = np.nanmedian(clean_data, axis=0)
min_values = np.nanmin(clean_data, axis=0)
max_values = np.nanmax(clean_data, axis=0)
std = np.nanstd(clean_data, axis=0)

table_2 = np.vstack((mean, median, min_values, max_values, std))
table_2

array([[ 2.41117480e+04,  1.78347535e+03,  8.03893400e+04,
         4.13223979e+04],
       [ 1.13840000e+04,  6.87950000e+02,  1.93245000e+04,
         1.92055000e+04],
       [ 5.14500000e+03, -6.17700000e+03,  4.37000000e+02,
         1.20000000e+02],
       [ 4.85873000e+05,  4.56870000e+04,  3.28796800e+06,
         7.53718000e+05],
       [ 3.82989968e+04,  3.93260648e+03,  2.70155140e+05,
         7.32324719e+04]])

In [119]:
# Ques 100
count = np.count_nonzero(~np.isnan(clean_data), axis=0)
mean = np.nanmean(clean_data,axis=0)
std = np.nanstd(clean_data, axis=0)
min_values = np.nanmin(clean_data, axis=0)
_25_ = np.nanpercentile(clean_data, 25, axis=0)
_50_ = np.nanpercentile(clean_data, 50, axis=0)
_75_ = np.nanpercentile(clean_data, 75, axis=0)
max_values = np.nanmax(clean_data, axis=0)

table_3 = np.vstack((count, mean, std, min_values, _25_, _50_, _75_, max_values))
table_3

array([[ 5.00000000e+02,  5.00000000e+02,  5.00000000e+02,
         5.00000000e+02],
       [ 2.41117480e+04,  1.78347535e+03,  8.03893400e+04,
         4.13223979e+04],
       [ 3.82989968e+04,  3.93260648e+03,  2.70155140e+05,
         7.32324719e+04],
       [ 5.14500000e+03, -6.17700000e+03,  4.37000000e+02,
         1.20000000e+02],
       [ 7.24500000e+03,  2.39900000e+02,  8.43650000e+03,
         7.46500000e+03],
       [ 1.13840000e+04,  6.87950000e+02,  1.93245000e+04,
         1.92055000e+04],
       [ 2.26052500e+04,  1.78019384e+03,  4.81260000e+04,
         4.13223979e+04],
       [ 4.85873000e+05,  4.56870000e+04,  3.28796800e+06,
         7.53718000e+05]])

# Remaining Topics

Reshaping, Combining & Splitting

**Easy**

101. Take the first 100 rows of clean_data and reshape them into an array with 20 rows. Print the resulting shape.

102. Take the Revenue, Profit, and Assets columns from clean_data. Create a 1D array from them using both ravel() and flatten(). Print their shapes.

**Medium**

103. Find the top 10 companies by Revenue and the top 10 companies by Profit. Combine the two resulting company datasets vertically into a single NumPy array.

104. Create a NumPy array containing the following columns in this exact order:

    Rank
    Company Name
    Revenue
    Profit
    Assets
    Market Value

**Hard**

105. Split the complete data array into 5 equal parts and calculate the average Revenue for each part.

In [120]:
clean_data[:100].reshape(20,20)

array([[ 4.85873000e+05,  1.36430000e+04,  1.98825000e+05,
         2.18619000e+05,  2.23604000e+05,  2.40740000e+04,
         6.20854000e+05,  4.11035000e+05,  2.15639000e+05,
         4.56870000e+04,  3.21686000e+05,  7.53718000e+05,
         2.05004000e+05,  7.84000000e+03,  3.30314000e+05,
         3.40056000e+05,  1.92487000e+05,  2.25800000e+03,
         5.65630000e+04,  3.14390000e+04],
       [ 1.84840000e+05,  7.01700000e+03,  1.22810000e+05,
         1.57793000e+05,  1.77526000e+05,  5.31700000e+03,
         9.44620000e+04,  8.13100000e+04,  1.66380000e+05,
         9.42700000e+03,  2.21690000e+05,  5.29680000e+04,
         1.63786000e+05,  1.29760000e+04,  4.03821000e+05,
         2.55679000e+05,  1.51800000e+05,  4.59600000e+03,
         2.37951000e+05,  4.63490000e+04],
       [ 1.46850000e+05,  1.42790000e+03,  3.36560000e+04,
         1.92290000e+04,  1.35987000e+05,  2.37100000e+03,
         8.34020000e+04,  4.23031000e+05,  1.26661000e+05,
         8.83100000e+03,  3.65183000e+05,  2.59520000e+05,
         1.25980000e+05,  1.31270000e+04,  2.44180000e+05,
         1.98900000e+05,  1.21546000e+05,  1.42700000e+03,
         3.41220000e+04,  2.57250000e+04],
       [ 1.18719000e+05,  2.35000000e+03,  3.31630000e+04,
         7.36060000e+04,  1.17351000e+05,  4.17300000e+03,
         7.26880000e+04,  8.96450000e+04,  1.15337000e+05,
         1.97500000e+03,  3.65050000e+04,  2.69610000e+04,
         1.07567000e+05, -4.97000000e+02,  2.60078000e+05,
         2.03263000e+05,  1.07162000e+05,  1.23130000e+04,
         3.28796800e+06,  3.01100000e+03],
       [ 1.05486000e+05,  2.47330000e+04,  2.49097200e+06,
         3.13761000e+05,  1.00288000e+05,  3.40440000e+03,
         5.17450000e+04,  3.95670000e+04,  9.45950000e+04,
         7.95700000e+03,  4.29660000e+04,  1.76368000e+05,
         9.45710000e+04,  4.89500000e+03,  8.99970000e+04,
         1.07546000e+05,  9.41760000e+04,  2.19380000e+04,
         1.93011500e+06,  2.78516000e+05],
       [ 9.36620000e+04,  1.79060000e+04,  2.18770200e+06,
         2.36182000e+05,  9.02720000e+04,  1.94780000e+04,
         1.67497000e+05,  5.79426000e+05,  8.53200000e+04,
         1.67980000e+04,  1.93694000e+05,  5.08935000e+05,
         8.48630000e+04,  2.46980000e+03,  6.50830000e+04,
         4.38130000e+04,  8.23860000e+04,  1.49120000e+04,
         1.79207700e+06,  1.65394000e+05],
       [ 8.04030000e+04,  8.69500000e+03,  1.80500000e+05,
         1.78258000e+05,  7.99190000e+04,  1.18720000e+04,
         1.17470000e+05,  1.64251000e+05,  7.61320000e+04,
         3.50300000e+02,  2.56030000e+05,  4.13223979e+04,
         7.23960000e+04,  1.55500000e+03,  5.16530000e+04,
         4.09540000e+04,  7.18900000e+04,  1.65400000e+04,
         1.41208000e+05,  3.37642000e+05],
       [ 7.17260000e+04,  1.05080000e+04,  1.27136000e+05,
         2.29700000e+05,  7.01660000e+04,  2.28900000e+03,
         4.61730000e+04,  2.97460000e+04,  6.94950000e+04,
         2.73700000e+03,  3.74310000e+04,  3.05020000e+04,
         6.56650000e+04,  7.81500000e+03,  2.02337600e+06,
         1.61200000e+03,  6.50170000e+04,  3.09300000e+03,
         3.44080000e+04,  7.04810000e+04],
       [ 6.48060000e+04, -1.67200000e+03,  1.18206000e+05,
         4.13223979e+04,  6.34760000e+04,  8.00000000e+02,
         8.98764000e+05,  5.74290000e+04,  6.31550000e+04,
         2.27100000e+03,  6.91460000e+04,  4.48590000e+04,
         6.27990000e+04,  6.32900000e+03,  7.41290000e+04,
         1.59763000e+05,  6.23460000e+04,  1.27900000e+03,
         3.97690000e+04,  2.62740000e+04],
       [ 6.09060000e+04,  3.43100000e+03,  4.03770000e+04,
         9.32760000e+04,  5.93870000e+04,  1.03160000e+04,
         1.13327000e+05,  1.70539000e+05,  5.87790000e+04,
         4.36800000e+03,  7.83962000e+05,  4.59120000e+04,
         5.87340000e+04, -5.02200000e+02,  2.37700000e+04,
         4.13223979e+04,  5.72440000e+04,  5.05500000e+03,
         8.97060000e+04,  8.99570000e+04],
       [ 5.58580000e+04,  1.17400000e+03,  4.44130000e+04,
         2.66790000e+04,  5.56320000e+04,  9.39100000e+03,
         9.20330000e+04,  1.79298000e+05,  5.43790000e+04,
         6.14000000e+02,  2.53960000e+04,  2.97430000e+04,
         5.28240000e+04,  7.21500000e+03,  1.71615000e+05,
         2.03725000e+05,  5.23670000e+04, -8.49000000e+02,
         4.98264000e+05,  6.11540000e+04],
       [ 5.06580000e+04,  5.30200000e+03,  4.78060000e+04,
         7.75570000e+04,  5.03670000e+04,  9.49600000e+02,
         1.67220000e+04,  2.80480000e+04,  5.03650000e+04,
         1.82000000e+03,  4.60640000e+04,  5.21780000e+04,
         5.01230000e+04,  3.16100000e+03,  7.96790000e+04,
         3.92880000e+04,  4.92470000e+04,  1.07390000e+04,
         1.21652000e+05,  1.69266000e+05],
       [ 4.82380000e+04,  2.49600000e+03,  2.90100000e+04,
         3.02310000e+04,  4.81580000e+04,  4.31800000e+03,
         7.95110000e+04,  7.74600000e+04,  4.47470000e+04,
         2.89000000e+03,  3.37580000e+04,  3.29660000e+04,
         4.18630000e+04,  6.52700000e+03,  8.72700000e+04,
         1.82153000e+05,  4.07870000e+04,  1.08810000e+03,
         2.87196000e+05,  4.13223979e+04],
       [ 4.07210000e+04,  5.62000000e+02,  2.01970000e+04,
         1.22710000e+04,  4.01800000e+04,  2.67600000e+03,
         5.12740000e+04,  2.13260000e+04,  4.00740000e+04,
         3.34300000e+02,  1.97790000e+05,  4.13223979e+04,
         3.98070000e+04,  3.92000000e+03,  9.53770000e+04,
         1.74454000e+05,  3.96680000e+04,  1.86700000e+03,
         5.93600000e+04,  3.76040000e+04],
       [ 3.96390000e+04,  4.37300000e+03,  5.12610000e+04,
         3.35860000e+04,  3.94030000e+04,  1.22800000e+03,
         1.38560000e+04,  1.51930000e+04,  3.93020000e+04,
         4.80900000e+03,  5.41460000e+04,  9.49910000e+04,
         3.85370000e+04, -6.70000000e+01,  7.47040000e+04,
         5.44020000e+04,  3.83080000e+04,  1.00600000e+03,
         1.25592000e+05,  4.13223979e+04],
       [ 3.79490000e+04,  5.97900000e+03,  8.14949000e+05,
         7.99470000e+04,  3.77880000e+04,  1.27350000e+03,
         2.71040000e+05,  4.13223979e+04,  3.77120000e+04,
         7.39800000e+03,  8.60165000e+05,  9.13800000e+04,
         3.75040000e+04,  9.95000000e+02,  7.90110000e+04,
         2.12920000e+04,  3.71050000e+04,  1.49230000e+03,
         5.23194000e+05,  4.13223979e+04],
       [ 3.70470000e+04,  8.90100000e+03,  1.12180000e+05,
         1.83556000e+05,  3.68810000e+04,  1.76800000e+03,
         2.23730000e+04,  2.20280000e+04,  3.65560000e+04,
         2.26300000e+03,  4.01400000e+04,  2.22250000e+04,
         3.65340000e+04,  1.87700000e+03,  1.08610000e+05,
         2.97540000e+04,  3.42740000e+04,  2.02570000e+03,
         1.74640000e+04,  4.13223979e+04],
       [ 3.38230000e+04,  5.40800000e+03,  1.58893000e+05,
         7.11930000e+04,  3.31840000e+04,  2.29820000e+03,
         1.28840000e+04,  5.10530000e+04,  3.23760000e+04,
         3.76000000e+03,  2.13960000e+04,  9.22040000e+04,
         3.13600000e+04,  1.13400000e+03,  1.14904000e+05,
         3.33090000e+04,  3.13530000e+04,  2.95500000e+03,
         3.28720000e+04,  5.67910000e+04],
       [ 3.07370000e+04,  1.65500000e+02,  1.12770000e+04,
         4.47300000e+03,  3.03900000e+04,  1.35010000e+04,
         5.69770000e+04,  8.87880000e+04,  3.03470000e+04,
         4.24200000e+02,  1.73180000e+04,  4.13223979e+04,
         3.01090000e+04,  5.05000000e+03,  3.29060000e+04,
         1.14338000e+05,  2.93180000e+04,  3.92600000e+03,
         6.59660000e+04,  7.56600000e+04],
       [ 2.90030000e+04,  3.52200000e+03,  1.49067000e+05,
         1.00595000e+05,  2.87990000e+04,  8.18000000e+02,
         2.50441000e+05,  4.13223979e+04,  2.76380000e+04,
         1.02170000e+04,  6.49610000e+04,  4.10522000e+05,
         2.76250000e+04,  3.01400000e+03,  1.00245000e+05,
         3.36890000e+04,  2.75190000e+04,  3.75100000e+03,
         3.57033000e+05,  4.18310000e+04]])

In [121]:
clean_data[:,:3].flatten()

array([4.85873e+05, 1.36430e+04, 1.98825e+05, ..., 5.14500e+03,
       5.72000e+01, 2.28100e+03], shape=(1500,))

In [122]:
clean_data[:,:3].ravel()

array([4.85873e+05, 1.36430e+04, 1.98825e+05, ..., 5.14500e+03,
       5.72000e+01, 2.28100e+03], shape=(1500,))

In [123]:
np.vstack((data[revenue_order][:10],data[profit_order][:10]))

array([[1, 'Walmart', '23,00,000', 1.0, '$4,85,873', '0.8%', '$13,643.0',
        '-7.2%', '$1,98,825', '$2,18,619'],
       [2, 'Berkshire Hathaway', '3,67,700', 4.0, '$2,23,604', '6.1%',
        '$24,074.0', '0.0%', '$6,20,854', '$4,11,035'],
       [3, 'Apple', '1,16,000', 3.0, '$2,15,639', '-7.7%', '$45,687.0',
        '-14.4%', '$3,21,686', '$7,53,718'],
       [4, 'Exxon Mobil', '72,700', 2.0, '$2,05,004', '-16.7%',
        '$7,840.0', '-51.5%', '$3,30,314', '$3,40,056'],
       [5, 'McKesson', '68,000', 5.0, '$1,92,487', '6.2%', '$2,258.0',
        '53.0%', '$56,563', '$31,439'],
       [6, 'UnitedHealth Group', '2,30,000', 6.0, '$1,84,840', '17.7%',
        '$7,017.0', '20.7%', '$1,22,810', '$1,57,793'],
       [7, 'CVS Health', '2,04,000', 7.0, '$1,77,526', '15.8%',
        '$5,317.0', '1.5%', '$94,462', '$81,310'],
       [8, 'General Motors', '2,25,000', 8.0, '$1,66,380', '9.2%',
        '$9,427.0', '-2.7%', '$2,21,690', '$52,968'],
       [9, 'AT&T', '2,68,540', 10.0, '$1,63,786', '11.6%', '$12,976.0',
        '-2.8%', '$4,03,821', '$2,55,679'],
       [10, 'Ford Motor', '2,01,000', 9.0, '$1,51,800', '1.5%',
        '$4,596.0', '-37.7%', '$2,37,951', '$46,349'],
       [3, 'Apple', '1,16,000', 3.0, '$2,15,639', '-7.7%', '$45,687.0',
        '-14.4%', '$3,21,686', '$7,53,718'],
       [21, 'J.P. Morgan Chase', '2,43,355', 23.0, '$1,05,486', '4.4%',
        '$24,733.0', '1.2%', '$24,90,972', '$3,13,761'],
       [2, 'Berkshire Hathaway', '3,67,700', 4.0, '$2,23,604', '6.1%',
        '$24,074.0', '0.0%', '$6,20,854', '$4,11,035'],
       [25, 'Wells Fargo', '2,69,100', 27.0, '$94,176', '4.6%',
        '$21,938.0', '-4.2%', '$19,30,115', '$2,78,516'],
       [27, 'Alphabet', '72,053', 36.0, '$90,272', '20.4%', '$19,478.0',
        '19.1%', '$1,67,497', '$5,79,426'],
       [26, 'Bank of America Corp.', '2,08,024', 26.0, '$93,662', '0.7%',
        '$17,906.0', '12.7%', '$21,87,702', '$2,36,182'],
       [28, 'Microsoft', '1,14,000', 25.0, '$85,320', '-8.8%',
        '$16,798.0', '37.8%', '$1,93,694', '$5,08,935'],
       [35, 'Johnson & Johnson', '1,26,400', 39.0, '$71,890', '2.6%',
        '$16,540.0', '7.3%', '$1,41,208', '$3,37,642'],
       [30, 'Citigroup', '2,19,000', 29.0, '$82,386', '-6.7%',
        '$14,912.0', '-13.5%', '$17,92,077', '$1,65,394'],
       [148, 'Altria Group', '8,300', 149.0, '$19,337', '2.6%',
        '$14,239.0', '171.7%', '$45,932', '$1,38,513']], dtype=object)

In [124]:
New_array_1 = np.column_stack((data[:,:2],clean_data))

In [125]:
splitted = np.array_split(New_array_1,5)

Part_1 = np.mean(splitted[0][:,2])
Part_2 = np.mean(splitted[1][:,2])
Part_3 = np.mean(splitted[2][:,2])
Part_4 = np.mean(splitted[3][:,2])
Part_5 = np.mean(splitted[4][:,2])